/*
  Warnings:

  - The values [SIXTYFOURTH,DOTTED_SIXTYFOURTH,HUNDREDTWENTYEIGHTH,DOTTED_HUNDREDTWENTYEIGHTH,TRIPLET_EIGHTH,TRIPLET_SIXTEENTH,QUADRUPLET_EIGHTH,QUINTUPLET_SIXTEENTH,QUINTUPLET_THIRTYSECOND,SEXTUPLET_SIXTEENTH,SEXTUPLET_THIRTYSECOND,SEPTUPLET_SIXTEENTH,SEPTUPLET_HUNDREDTWENTYEIGHTH] on the enum `NOTE_VALUE` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "NOTE_VALUE_new" AS ENUM ('WHOLE', 'HALF', 'DOTTED_HALF', 'QUARTER', 'DOTTED_QUARTER', 'EIGHTH', 'DOTTED_EIGHTH', 'SIXTEENTH', 'DOTTED_SIXTEENTH', 'THIRTYSECOND', 'DOTTED_THIRTYSECOND');
ALTER TABLE "MetronomeMark" ALTER COLUMN "beatUnit" TYPE "NOTE_VALUE_new" USING ("beatUnit"::text::"NOTE_VALUE_new");
ALTER TYPE "NOTE_VALUE" RENAME TO "NOTE_VALUE_old";
ALTER TYPE "NOTE_VALUE_new" RENAME TO "NOTE_VALUE";
DROP TYPE "NOTE_VALUE_old";
COMMIT;
