
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Contribution` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Contribution
 * 
 */
export type ContributionModel = runtime.Types.Result.DefaultSelection<Prisma.$ContributionPayload>

export type AggregateContribution = {
  _count: ContributionCountAggregateOutputType | null
  _min: ContributionMinAggregateOutputType | null
  _max: ContributionMaxAggregateOutputType | null
}

export type ContributionMinAggregateOutputType = {
  id: string | null
  mMSourceId: string | null
  personId: string | null
  organizationId: string | null
  role: $Enums.CONTRIBUTION_ROLE | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ContributionMaxAggregateOutputType = {
  id: string | null
  mMSourceId: string | null
  personId: string | null
  organizationId: string | null
  role: $Enums.CONTRIBUTION_ROLE | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ContributionCountAggregateOutputType = {
  id: number
  mMSourceId: number
  personId: number
  organizationId: number
  role: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ContributionMinAggregateInputType = {
  id?: true
  mMSourceId?: true
  personId?: true
  organizationId?: true
  role?: true
  createdAt?: true
  updatedAt?: true
}

export type ContributionMaxAggregateInputType = {
  id?: true
  mMSourceId?: true
  personId?: true
  organizationId?: true
  role?: true
  createdAt?: true
  updatedAt?: true
}

export type ContributionCountAggregateInputType = {
  id?: true
  mMSourceId?: true
  personId?: true
  organizationId?: true
  role?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ContributionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Contribution to aggregate.
   */
  where?: Prisma.ContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contributions to fetch.
   */
  orderBy?: Prisma.ContributionOrderByWithRelationInput | Prisma.ContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contributions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Contributions
  **/
  _count?: true | ContributionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ContributionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ContributionMaxAggregateInputType
}

export type GetContributionAggregateType<T extends ContributionAggregateArgs> = {
      [P in keyof T & keyof AggregateContribution]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateContribution[P]>
    : Prisma.GetScalarType<T[P], AggregateContribution[P]>
}




export type ContributionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContributionWhereInput
  orderBy?: Prisma.ContributionOrderByWithAggregationInput | Prisma.ContributionOrderByWithAggregationInput[]
  by: Prisma.ContributionScalarFieldEnum[] | Prisma.ContributionScalarFieldEnum
  having?: Prisma.ContributionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ContributionCountAggregateInputType | true
  _min?: ContributionMinAggregateInputType
  _max?: ContributionMaxAggregateInputType
}

export type ContributionGroupByOutputType = {
  id: string
  mMSourceId: string
  personId: string | null
  organizationId: string | null
  role: $Enums.CONTRIBUTION_ROLE
  createdAt: Date
  updatedAt: Date
  _count: ContributionCountAggregateOutputType | null
  _min: ContributionMinAggregateOutputType | null
  _max: ContributionMaxAggregateOutputType | null
}

type GetContributionGroupByPayload<T extends ContributionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ContributionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ContributionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ContributionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ContributionGroupByOutputType[P]>
      }
    >
  >



export type ContributionWhereInput = {
  AND?: Prisma.ContributionWhereInput | Prisma.ContributionWhereInput[]
  OR?: Prisma.ContributionWhereInput[]
  NOT?: Prisma.ContributionWhereInput | Prisma.ContributionWhereInput[]
  id?: Prisma.UuidFilter<"Contribution"> | string
  mMSourceId?: Prisma.UuidFilter<"Contribution"> | string
  personId?: Prisma.UuidNullableFilter<"Contribution"> | string | null
  organizationId?: Prisma.UuidNullableFilter<"Contribution"> | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFilter<"Contribution"> | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFilter<"Contribution"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Contribution"> | Date | string
  mMSource?: Prisma.XOR<Prisma.MMSourceScalarRelationFilter, Prisma.MMSourceWhereInput>
  person?: Prisma.XOR<Prisma.PersonNullableScalarRelationFilter, Prisma.PersonWhereInput> | null
  organization?: Prisma.XOR<Prisma.OrganizationNullableScalarRelationFilter, Prisma.OrganizationWhereInput> | null
}

export type ContributionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  mMSourceId?: Prisma.SortOrder
  personId?: Prisma.SortOrderInput | Prisma.SortOrder
  organizationId?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mMSource?: Prisma.MMSourceOrderByWithRelationInput
  person?: Prisma.PersonOrderByWithRelationInput
  organization?: Prisma.OrganizationOrderByWithRelationInput
}

export type ContributionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ContributionWhereInput | Prisma.ContributionWhereInput[]
  OR?: Prisma.ContributionWhereInput[]
  NOT?: Prisma.ContributionWhereInput | Prisma.ContributionWhereInput[]
  mMSourceId?: Prisma.UuidFilter<"Contribution"> | string
  personId?: Prisma.UuidNullableFilter<"Contribution"> | string | null
  organizationId?: Prisma.UuidNullableFilter<"Contribution"> | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFilter<"Contribution"> | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFilter<"Contribution"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Contribution"> | Date | string
  mMSource?: Prisma.XOR<Prisma.MMSourceScalarRelationFilter, Prisma.MMSourceWhereInput>
  person?: Prisma.XOR<Prisma.PersonNullableScalarRelationFilter, Prisma.PersonWhereInput> | null
  organization?: Prisma.XOR<Prisma.OrganizationNullableScalarRelationFilter, Prisma.OrganizationWhereInput> | null
}, "id">

export type ContributionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  mMSourceId?: Prisma.SortOrder
  personId?: Prisma.SortOrderInput | Prisma.SortOrder
  organizationId?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ContributionCountOrderByAggregateInput
  _max?: Prisma.ContributionMaxOrderByAggregateInput
  _min?: Prisma.ContributionMinOrderByAggregateInput
}

export type ContributionScalarWhereWithAggregatesInput = {
  AND?: Prisma.ContributionScalarWhereWithAggregatesInput | Prisma.ContributionScalarWhereWithAggregatesInput[]
  OR?: Prisma.ContributionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ContributionScalarWhereWithAggregatesInput | Prisma.ContributionScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Contribution"> | string
  mMSourceId?: Prisma.UuidWithAggregatesFilter<"Contribution"> | string
  personId?: Prisma.UuidNullableWithAggregatesFilter<"Contribution"> | string | null
  organizationId?: Prisma.UuidNullableWithAggregatesFilter<"Contribution"> | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEWithAggregatesFilter<"Contribution"> | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Contribution"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Contribution"> | Date | string
}

export type ContributionCreateInput = {
  id?: string
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
  mMSource: Prisma.MMSourceCreateNestedOneWithoutContributionsInput
  person?: Prisma.PersonCreateNestedOneWithoutContributionsInput
  organization?: Prisma.OrganizationCreateNestedOneWithoutContributionsInput
}

export type ContributionUncheckedCreateInput = {
  id?: string
  mMSourceId: string
  personId?: string | null
  organizationId?: string | null
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ContributionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mMSource?: Prisma.MMSourceUpdateOneRequiredWithoutContributionsNestedInput
  person?: Prisma.PersonUpdateOneWithoutContributionsNestedInput
  organization?: Prisma.OrganizationUpdateOneWithoutContributionsNestedInput
}

export type ContributionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mMSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  personId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributionCreateManyInput = {
  id?: string
  mMSourceId: string
  personId?: string | null
  organizationId?: string | null
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ContributionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mMSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  personId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributionListRelationFilter = {
  every?: Prisma.ContributionWhereInput
  some?: Prisma.ContributionWhereInput
  none?: Prisma.ContributionWhereInput
}

export type ContributionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ContributionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mMSourceId?: Prisma.SortOrder
  personId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ContributionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mMSourceId?: Prisma.SortOrder
  personId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ContributionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mMSourceId?: Prisma.SortOrder
  personId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ContributionCreateNestedManyWithoutMMSourceInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutMMSourceInput, Prisma.ContributionUncheckedCreateWithoutMMSourceInput> | Prisma.ContributionCreateWithoutMMSourceInput[] | Prisma.ContributionUncheckedCreateWithoutMMSourceInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutMMSourceInput | Prisma.ContributionCreateOrConnectWithoutMMSourceInput[]
  createMany?: Prisma.ContributionCreateManyMMSourceInputEnvelope
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
}

export type ContributionUncheckedCreateNestedManyWithoutMMSourceInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutMMSourceInput, Prisma.ContributionUncheckedCreateWithoutMMSourceInput> | Prisma.ContributionCreateWithoutMMSourceInput[] | Prisma.ContributionUncheckedCreateWithoutMMSourceInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutMMSourceInput | Prisma.ContributionCreateOrConnectWithoutMMSourceInput[]
  createMany?: Prisma.ContributionCreateManyMMSourceInputEnvelope
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
}

export type ContributionUpdateManyWithoutMMSourceNestedInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutMMSourceInput, Prisma.ContributionUncheckedCreateWithoutMMSourceInput> | Prisma.ContributionCreateWithoutMMSourceInput[] | Prisma.ContributionUncheckedCreateWithoutMMSourceInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutMMSourceInput | Prisma.ContributionCreateOrConnectWithoutMMSourceInput[]
  upsert?: Prisma.ContributionUpsertWithWhereUniqueWithoutMMSourceInput | Prisma.ContributionUpsertWithWhereUniqueWithoutMMSourceInput[]
  createMany?: Prisma.ContributionCreateManyMMSourceInputEnvelope
  set?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  disconnect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  delete?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  update?: Prisma.ContributionUpdateWithWhereUniqueWithoutMMSourceInput | Prisma.ContributionUpdateWithWhereUniqueWithoutMMSourceInput[]
  updateMany?: Prisma.ContributionUpdateManyWithWhereWithoutMMSourceInput | Prisma.ContributionUpdateManyWithWhereWithoutMMSourceInput[]
  deleteMany?: Prisma.ContributionScalarWhereInput | Prisma.ContributionScalarWhereInput[]
}

export type ContributionUncheckedUpdateManyWithoutMMSourceNestedInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutMMSourceInput, Prisma.ContributionUncheckedCreateWithoutMMSourceInput> | Prisma.ContributionCreateWithoutMMSourceInput[] | Prisma.ContributionUncheckedCreateWithoutMMSourceInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutMMSourceInput | Prisma.ContributionCreateOrConnectWithoutMMSourceInput[]
  upsert?: Prisma.ContributionUpsertWithWhereUniqueWithoutMMSourceInput | Prisma.ContributionUpsertWithWhereUniqueWithoutMMSourceInput[]
  createMany?: Prisma.ContributionCreateManyMMSourceInputEnvelope
  set?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  disconnect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  delete?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  update?: Prisma.ContributionUpdateWithWhereUniqueWithoutMMSourceInput | Prisma.ContributionUpdateWithWhereUniqueWithoutMMSourceInput[]
  updateMany?: Prisma.ContributionUpdateManyWithWhereWithoutMMSourceInput | Prisma.ContributionUpdateManyWithWhereWithoutMMSourceInput[]
  deleteMany?: Prisma.ContributionScalarWhereInput | Prisma.ContributionScalarWhereInput[]
}

export type EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput = {
  set?: $Enums.CONTRIBUTION_ROLE
}

export type ContributionCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutOrganizationInput, Prisma.ContributionUncheckedCreateWithoutOrganizationInput> | Prisma.ContributionCreateWithoutOrganizationInput[] | Prisma.ContributionUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutOrganizationInput | Prisma.ContributionCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.ContributionCreateManyOrganizationInputEnvelope
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
}

export type ContributionUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutOrganizationInput, Prisma.ContributionUncheckedCreateWithoutOrganizationInput> | Prisma.ContributionCreateWithoutOrganizationInput[] | Prisma.ContributionUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutOrganizationInput | Prisma.ContributionCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.ContributionCreateManyOrganizationInputEnvelope
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
}

export type ContributionUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutOrganizationInput, Prisma.ContributionUncheckedCreateWithoutOrganizationInput> | Prisma.ContributionCreateWithoutOrganizationInput[] | Prisma.ContributionUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutOrganizationInput | Prisma.ContributionCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.ContributionUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.ContributionUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.ContributionCreateManyOrganizationInputEnvelope
  set?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  disconnect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  delete?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  update?: Prisma.ContributionUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.ContributionUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.ContributionUpdateManyWithWhereWithoutOrganizationInput | Prisma.ContributionUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.ContributionScalarWhereInput | Prisma.ContributionScalarWhereInput[]
}

export type ContributionUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutOrganizationInput, Prisma.ContributionUncheckedCreateWithoutOrganizationInput> | Prisma.ContributionCreateWithoutOrganizationInput[] | Prisma.ContributionUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutOrganizationInput | Prisma.ContributionCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.ContributionUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.ContributionUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.ContributionCreateManyOrganizationInputEnvelope
  set?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  disconnect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  delete?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  update?: Prisma.ContributionUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.ContributionUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.ContributionUpdateManyWithWhereWithoutOrganizationInput | Prisma.ContributionUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.ContributionScalarWhereInput | Prisma.ContributionScalarWhereInput[]
}

export type ContributionCreateNestedManyWithoutPersonInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutPersonInput, Prisma.ContributionUncheckedCreateWithoutPersonInput> | Prisma.ContributionCreateWithoutPersonInput[] | Prisma.ContributionUncheckedCreateWithoutPersonInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutPersonInput | Prisma.ContributionCreateOrConnectWithoutPersonInput[]
  createMany?: Prisma.ContributionCreateManyPersonInputEnvelope
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
}

export type ContributionUncheckedCreateNestedManyWithoutPersonInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutPersonInput, Prisma.ContributionUncheckedCreateWithoutPersonInput> | Prisma.ContributionCreateWithoutPersonInput[] | Prisma.ContributionUncheckedCreateWithoutPersonInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutPersonInput | Prisma.ContributionCreateOrConnectWithoutPersonInput[]
  createMany?: Prisma.ContributionCreateManyPersonInputEnvelope
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
}

export type ContributionUpdateManyWithoutPersonNestedInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutPersonInput, Prisma.ContributionUncheckedCreateWithoutPersonInput> | Prisma.ContributionCreateWithoutPersonInput[] | Prisma.ContributionUncheckedCreateWithoutPersonInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutPersonInput | Prisma.ContributionCreateOrConnectWithoutPersonInput[]
  upsert?: Prisma.ContributionUpsertWithWhereUniqueWithoutPersonInput | Prisma.ContributionUpsertWithWhereUniqueWithoutPersonInput[]
  createMany?: Prisma.ContributionCreateManyPersonInputEnvelope
  set?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  disconnect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  delete?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  update?: Prisma.ContributionUpdateWithWhereUniqueWithoutPersonInput | Prisma.ContributionUpdateWithWhereUniqueWithoutPersonInput[]
  updateMany?: Prisma.ContributionUpdateManyWithWhereWithoutPersonInput | Prisma.ContributionUpdateManyWithWhereWithoutPersonInput[]
  deleteMany?: Prisma.ContributionScalarWhereInput | Prisma.ContributionScalarWhereInput[]
}

export type ContributionUncheckedUpdateManyWithoutPersonNestedInput = {
  create?: Prisma.XOR<Prisma.ContributionCreateWithoutPersonInput, Prisma.ContributionUncheckedCreateWithoutPersonInput> | Prisma.ContributionCreateWithoutPersonInput[] | Prisma.ContributionUncheckedCreateWithoutPersonInput[]
  connectOrCreate?: Prisma.ContributionCreateOrConnectWithoutPersonInput | Prisma.ContributionCreateOrConnectWithoutPersonInput[]
  upsert?: Prisma.ContributionUpsertWithWhereUniqueWithoutPersonInput | Prisma.ContributionUpsertWithWhereUniqueWithoutPersonInput[]
  createMany?: Prisma.ContributionCreateManyPersonInputEnvelope
  set?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  disconnect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  delete?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  connect?: Prisma.ContributionWhereUniqueInput | Prisma.ContributionWhereUniqueInput[]
  update?: Prisma.ContributionUpdateWithWhereUniqueWithoutPersonInput | Prisma.ContributionUpdateWithWhereUniqueWithoutPersonInput[]
  updateMany?: Prisma.ContributionUpdateManyWithWhereWithoutPersonInput | Prisma.ContributionUpdateManyWithWhereWithoutPersonInput[]
  deleteMany?: Prisma.ContributionScalarWhereInput | Prisma.ContributionScalarWhereInput[]
}

export type ContributionCreateWithoutMMSourceInput = {
  id?: string
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
  person?: Prisma.PersonCreateNestedOneWithoutContributionsInput
  organization?: Prisma.OrganizationCreateNestedOneWithoutContributionsInput
}

export type ContributionUncheckedCreateWithoutMMSourceInput = {
  id?: string
  personId?: string | null
  organizationId?: string | null
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ContributionCreateOrConnectWithoutMMSourceInput = {
  where: Prisma.ContributionWhereUniqueInput
  create: Prisma.XOR<Prisma.ContributionCreateWithoutMMSourceInput, Prisma.ContributionUncheckedCreateWithoutMMSourceInput>
}

export type ContributionCreateManyMMSourceInputEnvelope = {
  data: Prisma.ContributionCreateManyMMSourceInput | Prisma.ContributionCreateManyMMSourceInput[]
  skipDuplicates?: boolean
}

export type ContributionUpsertWithWhereUniqueWithoutMMSourceInput = {
  where: Prisma.ContributionWhereUniqueInput
  update: Prisma.XOR<Prisma.ContributionUpdateWithoutMMSourceInput, Prisma.ContributionUncheckedUpdateWithoutMMSourceInput>
  create: Prisma.XOR<Prisma.ContributionCreateWithoutMMSourceInput, Prisma.ContributionUncheckedCreateWithoutMMSourceInput>
}

export type ContributionUpdateWithWhereUniqueWithoutMMSourceInput = {
  where: Prisma.ContributionWhereUniqueInput
  data: Prisma.XOR<Prisma.ContributionUpdateWithoutMMSourceInput, Prisma.ContributionUncheckedUpdateWithoutMMSourceInput>
}

export type ContributionUpdateManyWithWhereWithoutMMSourceInput = {
  where: Prisma.ContributionScalarWhereInput
  data: Prisma.XOR<Prisma.ContributionUpdateManyMutationInput, Prisma.ContributionUncheckedUpdateManyWithoutMMSourceInput>
}

export type ContributionScalarWhereInput = {
  AND?: Prisma.ContributionScalarWhereInput | Prisma.ContributionScalarWhereInput[]
  OR?: Prisma.ContributionScalarWhereInput[]
  NOT?: Prisma.ContributionScalarWhereInput | Prisma.ContributionScalarWhereInput[]
  id?: Prisma.UuidFilter<"Contribution"> | string
  mMSourceId?: Prisma.UuidFilter<"Contribution"> | string
  personId?: Prisma.UuidNullableFilter<"Contribution"> | string | null
  organizationId?: Prisma.UuidNullableFilter<"Contribution"> | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFilter<"Contribution"> | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFilter<"Contribution"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Contribution"> | Date | string
}

export type ContributionCreateWithoutOrganizationInput = {
  id?: string
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
  mMSource: Prisma.MMSourceCreateNestedOneWithoutContributionsInput
  person?: Prisma.PersonCreateNestedOneWithoutContributionsInput
}

export type ContributionUncheckedCreateWithoutOrganizationInput = {
  id?: string
  mMSourceId: string
  personId?: string | null
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ContributionCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.ContributionWhereUniqueInput
  create: Prisma.XOR<Prisma.ContributionCreateWithoutOrganizationInput, Prisma.ContributionUncheckedCreateWithoutOrganizationInput>
}

export type ContributionCreateManyOrganizationInputEnvelope = {
  data: Prisma.ContributionCreateManyOrganizationInput | Prisma.ContributionCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type ContributionUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.ContributionWhereUniqueInput
  update: Prisma.XOR<Prisma.ContributionUpdateWithoutOrganizationInput, Prisma.ContributionUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.ContributionCreateWithoutOrganizationInput, Prisma.ContributionUncheckedCreateWithoutOrganizationInput>
}

export type ContributionUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.ContributionWhereUniqueInput
  data: Prisma.XOR<Prisma.ContributionUpdateWithoutOrganizationInput, Prisma.ContributionUncheckedUpdateWithoutOrganizationInput>
}

export type ContributionUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.ContributionScalarWhereInput
  data: Prisma.XOR<Prisma.ContributionUpdateManyMutationInput, Prisma.ContributionUncheckedUpdateManyWithoutOrganizationInput>
}

export type ContributionCreateWithoutPersonInput = {
  id?: string
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
  mMSource: Prisma.MMSourceCreateNestedOneWithoutContributionsInput
  organization?: Prisma.OrganizationCreateNestedOneWithoutContributionsInput
}

export type ContributionUncheckedCreateWithoutPersonInput = {
  id?: string
  mMSourceId: string
  organizationId?: string | null
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ContributionCreateOrConnectWithoutPersonInput = {
  where: Prisma.ContributionWhereUniqueInput
  create: Prisma.XOR<Prisma.ContributionCreateWithoutPersonInput, Prisma.ContributionUncheckedCreateWithoutPersonInput>
}

export type ContributionCreateManyPersonInputEnvelope = {
  data: Prisma.ContributionCreateManyPersonInput | Prisma.ContributionCreateManyPersonInput[]
  skipDuplicates?: boolean
}

export type ContributionUpsertWithWhereUniqueWithoutPersonInput = {
  where: Prisma.ContributionWhereUniqueInput
  update: Prisma.XOR<Prisma.ContributionUpdateWithoutPersonInput, Prisma.ContributionUncheckedUpdateWithoutPersonInput>
  create: Prisma.XOR<Prisma.ContributionCreateWithoutPersonInput, Prisma.ContributionUncheckedCreateWithoutPersonInput>
}

export type ContributionUpdateWithWhereUniqueWithoutPersonInput = {
  where: Prisma.ContributionWhereUniqueInput
  data: Prisma.XOR<Prisma.ContributionUpdateWithoutPersonInput, Prisma.ContributionUncheckedUpdateWithoutPersonInput>
}

export type ContributionUpdateManyWithWhereWithoutPersonInput = {
  where: Prisma.ContributionScalarWhereInput
  data: Prisma.XOR<Prisma.ContributionUpdateManyMutationInput, Prisma.ContributionUncheckedUpdateManyWithoutPersonInput>
}

export type ContributionCreateManyMMSourceInput = {
  id?: string
  personId?: string | null
  organizationId?: string | null
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ContributionUpdateWithoutMMSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  person?: Prisma.PersonUpdateOneWithoutContributionsNestedInput
  organization?: Prisma.OrganizationUpdateOneWithoutContributionsNestedInput
}

export type ContributionUncheckedUpdateWithoutMMSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  personId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributionUncheckedUpdateManyWithoutMMSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  personId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributionCreateManyOrganizationInput = {
  id?: string
  mMSourceId: string
  personId?: string | null
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ContributionUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mMSource?: Prisma.MMSourceUpdateOneRequiredWithoutContributionsNestedInput
  person?: Prisma.PersonUpdateOneWithoutContributionsNestedInput
}

export type ContributionUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mMSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  personId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributionUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mMSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  personId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributionCreateManyPersonInput = {
  id?: string
  mMSourceId: string
  organizationId?: string | null
  role: $Enums.CONTRIBUTION_ROLE
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ContributionUpdateWithoutPersonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mMSource?: Prisma.MMSourceUpdateOneRequiredWithoutContributionsNestedInput
  organization?: Prisma.OrganizationUpdateOneWithoutContributionsNestedInput
}

export type ContributionUncheckedUpdateWithoutPersonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mMSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributionUncheckedUpdateManyWithoutPersonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mMSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumCONTRIBUTION_ROLEFieldUpdateOperationsInput | $Enums.CONTRIBUTION_ROLE
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ContributionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mMSourceId?: boolean
  personId?: boolean
  organizationId?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
  person?: boolean | Prisma.Contribution$personArgs<ExtArgs>
  organization?: boolean | Prisma.Contribution$organizationArgs<ExtArgs>
}, ExtArgs["result"]["contribution"]>

export type ContributionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mMSourceId?: boolean
  personId?: boolean
  organizationId?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
  person?: boolean | Prisma.Contribution$personArgs<ExtArgs>
  organization?: boolean | Prisma.Contribution$organizationArgs<ExtArgs>
}, ExtArgs["result"]["contribution"]>

export type ContributionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mMSourceId?: boolean
  personId?: boolean
  organizationId?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
  person?: boolean | Prisma.Contribution$personArgs<ExtArgs>
  organization?: boolean | Prisma.Contribution$organizationArgs<ExtArgs>
}, ExtArgs["result"]["contribution"]>

export type ContributionSelectScalar = {
  id?: boolean
  mMSourceId?: boolean
  personId?: boolean
  organizationId?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ContributionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "mMSourceId" | "personId" | "organizationId" | "role" | "createdAt" | "updatedAt", ExtArgs["result"]["contribution"]>
export type ContributionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
  person?: boolean | Prisma.Contribution$personArgs<ExtArgs>
  organization?: boolean | Prisma.Contribution$organizationArgs<ExtArgs>
}
export type ContributionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
  person?: boolean | Prisma.Contribution$personArgs<ExtArgs>
  organization?: boolean | Prisma.Contribution$organizationArgs<ExtArgs>
}
export type ContributionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
  person?: boolean | Prisma.Contribution$personArgs<ExtArgs>
  organization?: boolean | Prisma.Contribution$organizationArgs<ExtArgs>
}

export type $ContributionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Contribution"
  objects: {
    mMSource: Prisma.$MMSourcePayload<ExtArgs>
    person: Prisma.$PersonPayload<ExtArgs> | null
    organization: Prisma.$OrganizationPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    mMSourceId: string
    personId: string | null
    organizationId: string | null
    role: $Enums.CONTRIBUTION_ROLE
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["contribution"]>
  composites: {}
}

export type ContributionGetPayload<S extends boolean | null | undefined | ContributionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ContributionPayload, S>

export type ContributionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ContributionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ContributionCountAggregateInputType | true
  }

export interface ContributionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Contribution'], meta: { name: 'Contribution' } }
  /**
   * Find zero or one Contribution that matches the filter.
   * @param {ContributionFindUniqueArgs} args - Arguments to find a Contribution
   * @example
   * // Get one Contribution
   * const contribution = await prisma.contribution.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ContributionFindUniqueArgs>(args: Prisma.SelectSubset<T, ContributionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Contribution that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ContributionFindUniqueOrThrowArgs} args - Arguments to find a Contribution
   * @example
   * // Get one Contribution
   * const contribution = await prisma.contribution.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ContributionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ContributionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Contribution that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributionFindFirstArgs} args - Arguments to find a Contribution
   * @example
   * // Get one Contribution
   * const contribution = await prisma.contribution.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ContributionFindFirstArgs>(args?: Prisma.SelectSubset<T, ContributionFindFirstArgs<ExtArgs>>): Prisma.Prisma__ContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Contribution that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributionFindFirstOrThrowArgs} args - Arguments to find a Contribution
   * @example
   * // Get one Contribution
   * const contribution = await prisma.contribution.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ContributionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ContributionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Contributions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Contributions
   * const contributions = await prisma.contribution.findMany()
   * 
   * // Get first 10 Contributions
   * const contributions = await prisma.contribution.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const contributionWithIdOnly = await prisma.contribution.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ContributionFindManyArgs>(args?: Prisma.SelectSubset<T, ContributionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Contribution.
   * @param {ContributionCreateArgs} args - Arguments to create a Contribution.
   * @example
   * // Create one Contribution
   * const Contribution = await prisma.contribution.create({
   *   data: {
   *     // ... data to create a Contribution
   *   }
   * })
   * 
   */
  create<T extends ContributionCreateArgs>(args: Prisma.SelectSubset<T, ContributionCreateArgs<ExtArgs>>): Prisma.Prisma__ContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Contributions.
   * @param {ContributionCreateManyArgs} args - Arguments to create many Contributions.
   * @example
   * // Create many Contributions
   * const contribution = await prisma.contribution.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ContributionCreateManyArgs>(args?: Prisma.SelectSubset<T, ContributionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Contributions and returns the data saved in the database.
   * @param {ContributionCreateManyAndReturnArgs} args - Arguments to create many Contributions.
   * @example
   * // Create many Contributions
   * const contribution = await prisma.contribution.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Contributions and only return the `id`
   * const contributionWithIdOnly = await prisma.contribution.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ContributionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ContributionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Contribution.
   * @param {ContributionDeleteArgs} args - Arguments to delete one Contribution.
   * @example
   * // Delete one Contribution
   * const Contribution = await prisma.contribution.delete({
   *   where: {
   *     // ... filter to delete one Contribution
   *   }
   * })
   * 
   */
  delete<T extends ContributionDeleteArgs>(args: Prisma.SelectSubset<T, ContributionDeleteArgs<ExtArgs>>): Prisma.Prisma__ContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Contribution.
   * @param {ContributionUpdateArgs} args - Arguments to update one Contribution.
   * @example
   * // Update one Contribution
   * const contribution = await prisma.contribution.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ContributionUpdateArgs>(args: Prisma.SelectSubset<T, ContributionUpdateArgs<ExtArgs>>): Prisma.Prisma__ContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Contributions.
   * @param {ContributionDeleteManyArgs} args - Arguments to filter Contributions to delete.
   * @example
   * // Delete a few Contributions
   * const { count } = await prisma.contribution.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ContributionDeleteManyArgs>(args?: Prisma.SelectSubset<T, ContributionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Contributions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Contributions
   * const contribution = await prisma.contribution.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ContributionUpdateManyArgs>(args: Prisma.SelectSubset<T, ContributionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Contributions and returns the data updated in the database.
   * @param {ContributionUpdateManyAndReturnArgs} args - Arguments to update many Contributions.
   * @example
   * // Update many Contributions
   * const contribution = await prisma.contribution.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Contributions and only return the `id`
   * const contributionWithIdOnly = await prisma.contribution.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ContributionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ContributionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Contribution.
   * @param {ContributionUpsertArgs} args - Arguments to update or create a Contribution.
   * @example
   * // Update or create a Contribution
   * const contribution = await prisma.contribution.upsert({
   *   create: {
   *     // ... data to create a Contribution
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Contribution we want to update
   *   }
   * })
   */
  upsert<T extends ContributionUpsertArgs>(args: Prisma.SelectSubset<T, ContributionUpsertArgs<ExtArgs>>): Prisma.Prisma__ContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Contributions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributionCountArgs} args - Arguments to filter Contributions to count.
   * @example
   * // Count the number of Contributions
   * const count = await prisma.contribution.count({
   *   where: {
   *     // ... the filter for the Contributions we want to count
   *   }
   * })
  **/
  count<T extends ContributionCountArgs>(
    args?: Prisma.Subset<T, ContributionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ContributionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Contribution.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ContributionAggregateArgs>(args: Prisma.Subset<T, ContributionAggregateArgs>): Prisma.PrismaPromise<GetContributionAggregateType<T>>

  /**
   * Group by Contribution.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ContributionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ContributionGroupByArgs['orderBy'] }
      : { orderBy?: ContributionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ContributionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetContributionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Contribution model
 */
readonly fields: ContributionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Contribution.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContributionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mMSource<T extends Prisma.MMSourceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MMSourceDefaultArgs<ExtArgs>>): Prisma.Prisma__MMSourceClient<runtime.Types.Result.GetResult<Prisma.$MMSourcePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  person<T extends Prisma.Contribution$personArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Contribution$personArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  organization<T extends Prisma.Contribution$organizationArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Contribution$organizationArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Contribution model
 */
export interface ContributionFieldRefs {
  readonly id: Prisma.FieldRef<"Contribution", 'String'>
  readonly mMSourceId: Prisma.FieldRef<"Contribution", 'String'>
  readonly personId: Prisma.FieldRef<"Contribution", 'String'>
  readonly organizationId: Prisma.FieldRef<"Contribution", 'String'>
  readonly role: Prisma.FieldRef<"Contribution", 'CONTRIBUTION_ROLE'>
  readonly createdAt: Prisma.FieldRef<"Contribution", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Contribution", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Contribution findUnique
 */
export type ContributionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
  /**
   * Filter, which Contribution to fetch.
   */
  where: Prisma.ContributionWhereUniqueInput
}

/**
 * Contribution findUniqueOrThrow
 */
export type ContributionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
  /**
   * Filter, which Contribution to fetch.
   */
  where: Prisma.ContributionWhereUniqueInput
}

/**
 * Contribution findFirst
 */
export type ContributionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
  /**
   * Filter, which Contribution to fetch.
   */
  where?: Prisma.ContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contributions to fetch.
   */
  orderBy?: Prisma.ContributionOrderByWithRelationInput | Prisma.ContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Contributions.
   */
  cursor?: Prisma.ContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contributions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Contributions.
   */
  distinct?: Prisma.ContributionScalarFieldEnum | Prisma.ContributionScalarFieldEnum[]
}

/**
 * Contribution findFirstOrThrow
 */
export type ContributionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
  /**
   * Filter, which Contribution to fetch.
   */
  where?: Prisma.ContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contributions to fetch.
   */
  orderBy?: Prisma.ContributionOrderByWithRelationInput | Prisma.ContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Contributions.
   */
  cursor?: Prisma.ContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contributions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Contributions.
   */
  distinct?: Prisma.ContributionScalarFieldEnum | Prisma.ContributionScalarFieldEnum[]
}

/**
 * Contribution findMany
 */
export type ContributionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
  /**
   * Filter, which Contributions to fetch.
   */
  where?: Prisma.ContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contributions to fetch.
   */
  orderBy?: Prisma.ContributionOrderByWithRelationInput | Prisma.ContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Contributions.
   */
  cursor?: Prisma.ContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contributions.
   */
  skip?: number
  distinct?: Prisma.ContributionScalarFieldEnum | Prisma.ContributionScalarFieldEnum[]
}

/**
 * Contribution create
 */
export type ContributionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
  /**
   * The data needed to create a Contribution.
   */
  data: Prisma.XOR<Prisma.ContributionCreateInput, Prisma.ContributionUncheckedCreateInput>
}

/**
 * Contribution createMany
 */
export type ContributionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Contributions.
   */
  data: Prisma.ContributionCreateManyInput | Prisma.ContributionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Contribution createManyAndReturn
 */
export type ContributionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * The data used to create many Contributions.
   */
  data: Prisma.ContributionCreateManyInput | Prisma.ContributionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Contribution update
 */
export type ContributionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
  /**
   * The data needed to update a Contribution.
   */
  data: Prisma.XOR<Prisma.ContributionUpdateInput, Prisma.ContributionUncheckedUpdateInput>
  /**
   * Choose, which Contribution to update.
   */
  where: Prisma.ContributionWhereUniqueInput
}

/**
 * Contribution updateMany
 */
export type ContributionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Contributions.
   */
  data: Prisma.XOR<Prisma.ContributionUpdateManyMutationInput, Prisma.ContributionUncheckedUpdateManyInput>
  /**
   * Filter which Contributions to update
   */
  where?: Prisma.ContributionWhereInput
  /**
   * Limit how many Contributions to update.
   */
  limit?: number
}

/**
 * Contribution updateManyAndReturn
 */
export type ContributionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * The data used to update Contributions.
   */
  data: Prisma.XOR<Prisma.ContributionUpdateManyMutationInput, Prisma.ContributionUncheckedUpdateManyInput>
  /**
   * Filter which Contributions to update
   */
  where?: Prisma.ContributionWhereInput
  /**
   * Limit how many Contributions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Contribution upsert
 */
export type ContributionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
  /**
   * The filter to search for the Contribution to update in case it exists.
   */
  where: Prisma.ContributionWhereUniqueInput
  /**
   * In case the Contribution found by the `where` argument doesn't exist, create a new Contribution with this data.
   */
  create: Prisma.XOR<Prisma.ContributionCreateInput, Prisma.ContributionUncheckedCreateInput>
  /**
   * In case the Contribution was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ContributionUpdateInput, Prisma.ContributionUncheckedUpdateInput>
}

/**
 * Contribution delete
 */
export type ContributionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
  /**
   * Filter which Contribution to delete.
   */
  where: Prisma.ContributionWhereUniqueInput
}

/**
 * Contribution deleteMany
 */
export type ContributionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Contributions to delete
   */
  where?: Prisma.ContributionWhereInput
  /**
   * Limit how many Contributions to delete.
   */
  limit?: number
}

/**
 * Contribution.person
 */
export type Contribution$personArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  where?: Prisma.PersonWhereInput
}

/**
 * Contribution.organization
 */
export type Contribution$organizationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
  where?: Prisma.OrganizationWhereInput
}

/**
 * Contribution without action
 */
export type ContributionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
}
