
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MMSourcesOnPieceVersions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MMSourcesOnPieceVersions
 * 
 */
export type MMSourcesOnPieceVersionsModel = runtime.Types.Result.DefaultSelection<Prisma.$MMSourcesOnPieceVersionsPayload>

export type AggregateMMSourcesOnPieceVersions = {
  _count: MMSourcesOnPieceVersionsCountAggregateOutputType | null
  _avg: MMSourcesOnPieceVersionsAvgAggregateOutputType | null
  _sum: MMSourcesOnPieceVersionsSumAggregateOutputType | null
  _min: MMSourcesOnPieceVersionsMinAggregateOutputType | null
  _max: MMSourcesOnPieceVersionsMaxAggregateOutputType | null
}

export type MMSourcesOnPieceVersionsAvgAggregateOutputType = {
  rank: number | null
}

export type MMSourcesOnPieceVersionsSumAggregateOutputType = {
  rank: number | null
}

export type MMSourcesOnPieceVersionsMinAggregateOutputType = {
  id: string | null
  pieceVersionId: string | null
  mMSourceId: string | null
  rank: number | null
}

export type MMSourcesOnPieceVersionsMaxAggregateOutputType = {
  id: string | null
  pieceVersionId: string | null
  mMSourceId: string | null
  rank: number | null
}

export type MMSourcesOnPieceVersionsCountAggregateOutputType = {
  id: number
  pieceVersionId: number
  mMSourceId: number
  rank: number
  _all: number
}


export type MMSourcesOnPieceVersionsAvgAggregateInputType = {
  rank?: true
}

export type MMSourcesOnPieceVersionsSumAggregateInputType = {
  rank?: true
}

export type MMSourcesOnPieceVersionsMinAggregateInputType = {
  id?: true
  pieceVersionId?: true
  mMSourceId?: true
  rank?: true
}

export type MMSourcesOnPieceVersionsMaxAggregateInputType = {
  id?: true
  pieceVersionId?: true
  mMSourceId?: true
  rank?: true
}

export type MMSourcesOnPieceVersionsCountAggregateInputType = {
  id?: true
  pieceVersionId?: true
  mMSourceId?: true
  rank?: true
  _all?: true
}

export type MMSourcesOnPieceVersionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MMSourcesOnPieceVersions to aggregate.
   */
  where?: Prisma.MMSourcesOnPieceVersionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MMSourcesOnPieceVersions to fetch.
   */
  orderBy?: Prisma.MMSourcesOnPieceVersionsOrderByWithRelationInput | Prisma.MMSourcesOnPieceVersionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MMSourcesOnPieceVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MMSourcesOnPieceVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MMSourcesOnPieceVersions
  **/
  _count?: true | MMSourcesOnPieceVersionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MMSourcesOnPieceVersionsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MMSourcesOnPieceVersionsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MMSourcesOnPieceVersionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MMSourcesOnPieceVersionsMaxAggregateInputType
}

export type GetMMSourcesOnPieceVersionsAggregateType<T extends MMSourcesOnPieceVersionsAggregateArgs> = {
      [P in keyof T & keyof AggregateMMSourcesOnPieceVersions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMMSourcesOnPieceVersions[P]>
    : Prisma.GetScalarType<T[P], AggregateMMSourcesOnPieceVersions[P]>
}




export type MMSourcesOnPieceVersionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MMSourcesOnPieceVersionsWhereInput
  orderBy?: Prisma.MMSourcesOnPieceVersionsOrderByWithAggregationInput | Prisma.MMSourcesOnPieceVersionsOrderByWithAggregationInput[]
  by: Prisma.MMSourcesOnPieceVersionsScalarFieldEnum[] | Prisma.MMSourcesOnPieceVersionsScalarFieldEnum
  having?: Prisma.MMSourcesOnPieceVersionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MMSourcesOnPieceVersionsCountAggregateInputType | true
  _avg?: MMSourcesOnPieceVersionsAvgAggregateInputType
  _sum?: MMSourcesOnPieceVersionsSumAggregateInputType
  _min?: MMSourcesOnPieceVersionsMinAggregateInputType
  _max?: MMSourcesOnPieceVersionsMaxAggregateInputType
}

export type MMSourcesOnPieceVersionsGroupByOutputType = {
  id: string
  pieceVersionId: string
  mMSourceId: string
  rank: number
  _count: MMSourcesOnPieceVersionsCountAggregateOutputType | null
  _avg: MMSourcesOnPieceVersionsAvgAggregateOutputType | null
  _sum: MMSourcesOnPieceVersionsSumAggregateOutputType | null
  _min: MMSourcesOnPieceVersionsMinAggregateOutputType | null
  _max: MMSourcesOnPieceVersionsMaxAggregateOutputType | null
}

type GetMMSourcesOnPieceVersionsGroupByPayload<T extends MMSourcesOnPieceVersionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MMSourcesOnPieceVersionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MMSourcesOnPieceVersionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MMSourcesOnPieceVersionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MMSourcesOnPieceVersionsGroupByOutputType[P]>
      }
    >
  >



export type MMSourcesOnPieceVersionsWhereInput = {
  AND?: Prisma.MMSourcesOnPieceVersionsWhereInput | Prisma.MMSourcesOnPieceVersionsWhereInput[]
  OR?: Prisma.MMSourcesOnPieceVersionsWhereInput[]
  NOT?: Prisma.MMSourcesOnPieceVersionsWhereInput | Prisma.MMSourcesOnPieceVersionsWhereInput[]
  id?: Prisma.UuidFilter<"MMSourcesOnPieceVersions"> | string
  pieceVersionId?: Prisma.UuidFilter<"MMSourcesOnPieceVersions"> | string
  mMSourceId?: Prisma.UuidFilter<"MMSourcesOnPieceVersions"> | string
  rank?: Prisma.IntFilter<"MMSourcesOnPieceVersions"> | number
  pieceVersion?: Prisma.XOR<Prisma.PieceVersionScalarRelationFilter, Prisma.PieceVersionWhereInput>
  mMSource?: Prisma.XOR<Prisma.MMSourceScalarRelationFilter, Prisma.MMSourceWhereInput>
}

export type MMSourcesOnPieceVersionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pieceVersionId?: Prisma.SortOrder
  mMSourceId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  pieceVersion?: Prisma.PieceVersionOrderByWithRelationInput
  mMSource?: Prisma.MMSourceOrderByWithRelationInput
}

export type MMSourcesOnPieceVersionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  mMSourceId_rank?: Prisma.MMSourcesOnPieceVersionsMMSourceIdRankCompoundUniqueInput
  mMSourceId_pieceVersionId?: Prisma.MMSourcesOnPieceVersionsMMSourceIdPieceVersionIdCompoundUniqueInput
  AND?: Prisma.MMSourcesOnPieceVersionsWhereInput | Prisma.MMSourcesOnPieceVersionsWhereInput[]
  OR?: Prisma.MMSourcesOnPieceVersionsWhereInput[]
  NOT?: Prisma.MMSourcesOnPieceVersionsWhereInput | Prisma.MMSourcesOnPieceVersionsWhereInput[]
  pieceVersionId?: Prisma.UuidFilter<"MMSourcesOnPieceVersions"> | string
  mMSourceId?: Prisma.UuidFilter<"MMSourcesOnPieceVersions"> | string
  rank?: Prisma.IntFilter<"MMSourcesOnPieceVersions"> | number
  pieceVersion?: Prisma.XOR<Prisma.PieceVersionScalarRelationFilter, Prisma.PieceVersionWhereInput>
  mMSource?: Prisma.XOR<Prisma.MMSourceScalarRelationFilter, Prisma.MMSourceWhereInput>
}, "id" | "mMSourceId_rank" | "mMSourceId_pieceVersionId">

export type MMSourcesOnPieceVersionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pieceVersionId?: Prisma.SortOrder
  mMSourceId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  _count?: Prisma.MMSourcesOnPieceVersionsCountOrderByAggregateInput
  _avg?: Prisma.MMSourcesOnPieceVersionsAvgOrderByAggregateInput
  _max?: Prisma.MMSourcesOnPieceVersionsMaxOrderByAggregateInput
  _min?: Prisma.MMSourcesOnPieceVersionsMinOrderByAggregateInput
  _sum?: Prisma.MMSourcesOnPieceVersionsSumOrderByAggregateInput
}

export type MMSourcesOnPieceVersionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.MMSourcesOnPieceVersionsScalarWhereWithAggregatesInput | Prisma.MMSourcesOnPieceVersionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.MMSourcesOnPieceVersionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MMSourcesOnPieceVersionsScalarWhereWithAggregatesInput | Prisma.MMSourcesOnPieceVersionsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"MMSourcesOnPieceVersions"> | string
  pieceVersionId?: Prisma.UuidWithAggregatesFilter<"MMSourcesOnPieceVersions"> | string
  mMSourceId?: Prisma.UuidWithAggregatesFilter<"MMSourcesOnPieceVersions"> | string
  rank?: Prisma.IntWithAggregatesFilter<"MMSourcesOnPieceVersions"> | number
}

export type MMSourcesOnPieceVersionsCreateInput = {
  id?: string
  rank: number
  pieceVersion: Prisma.PieceVersionCreateNestedOneWithoutMMSourcesInput
  mMSource: Prisma.MMSourceCreateNestedOneWithoutPieceVersionsInput
}

export type MMSourcesOnPieceVersionsUncheckedCreateInput = {
  id?: string
  pieceVersionId: string
  mMSourceId: string
  rank: number
}

export type MMSourcesOnPieceVersionsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  pieceVersion?: Prisma.PieceVersionUpdateOneRequiredWithoutMMSourcesNestedInput
  mMSource?: Prisma.MMSourceUpdateOneRequiredWithoutPieceVersionsNestedInput
}

export type MMSourcesOnPieceVersionsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pieceVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  mMSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MMSourcesOnPieceVersionsCreateManyInput = {
  id?: string
  pieceVersionId: string
  mMSourceId: string
  rank: number
}

export type MMSourcesOnPieceVersionsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MMSourcesOnPieceVersionsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pieceVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  mMSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MMSourcesOnPieceVersionsListRelationFilter = {
  every?: Prisma.MMSourcesOnPieceVersionsWhereInput
  some?: Prisma.MMSourcesOnPieceVersionsWhereInput
  none?: Prisma.MMSourcesOnPieceVersionsWhereInput
}

export type MMSourcesOnPieceVersionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MMSourcesOnPieceVersionsMMSourceIdRankCompoundUniqueInput = {
  mMSourceId: string
  rank: number
}

export type MMSourcesOnPieceVersionsMMSourceIdPieceVersionIdCompoundUniqueInput = {
  mMSourceId: string
  pieceVersionId: string
}

export type MMSourcesOnPieceVersionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pieceVersionId?: Prisma.SortOrder
  mMSourceId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
}

export type MMSourcesOnPieceVersionsAvgOrderByAggregateInput = {
  rank?: Prisma.SortOrder
}

export type MMSourcesOnPieceVersionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pieceVersionId?: Prisma.SortOrder
  mMSourceId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
}

export type MMSourcesOnPieceVersionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pieceVersionId?: Prisma.SortOrder
  mMSourceId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
}

export type MMSourcesOnPieceVersionsSumOrderByAggregateInput = {
  rank?: Prisma.SortOrder
}

export type MMSourcesOnPieceVersionsCreateNestedManyWithoutPieceVersionInput = {
  create?: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput> | Prisma.MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput[] | Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput[]
  connectOrCreate?: Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutPieceVersionInput | Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutPieceVersionInput[]
  createMany?: Prisma.MMSourcesOnPieceVersionsCreateManyPieceVersionInputEnvelope
  connect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
}

export type MMSourcesOnPieceVersionsUncheckedCreateNestedManyWithoutPieceVersionInput = {
  create?: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput> | Prisma.MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput[] | Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput[]
  connectOrCreate?: Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutPieceVersionInput | Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutPieceVersionInput[]
  createMany?: Prisma.MMSourcesOnPieceVersionsCreateManyPieceVersionInputEnvelope
  connect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
}

export type MMSourcesOnPieceVersionsUpdateManyWithoutPieceVersionNestedInput = {
  create?: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput> | Prisma.MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput[] | Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput[]
  connectOrCreate?: Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutPieceVersionInput | Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutPieceVersionInput[]
  upsert?: Prisma.MMSourcesOnPieceVersionsUpsertWithWhereUniqueWithoutPieceVersionInput | Prisma.MMSourcesOnPieceVersionsUpsertWithWhereUniqueWithoutPieceVersionInput[]
  createMany?: Prisma.MMSourcesOnPieceVersionsCreateManyPieceVersionInputEnvelope
  set?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  disconnect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  delete?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  connect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  update?: Prisma.MMSourcesOnPieceVersionsUpdateWithWhereUniqueWithoutPieceVersionInput | Prisma.MMSourcesOnPieceVersionsUpdateWithWhereUniqueWithoutPieceVersionInput[]
  updateMany?: Prisma.MMSourcesOnPieceVersionsUpdateManyWithWhereWithoutPieceVersionInput | Prisma.MMSourcesOnPieceVersionsUpdateManyWithWhereWithoutPieceVersionInput[]
  deleteMany?: Prisma.MMSourcesOnPieceVersionsScalarWhereInput | Prisma.MMSourcesOnPieceVersionsScalarWhereInput[]
}

export type MMSourcesOnPieceVersionsUncheckedUpdateManyWithoutPieceVersionNestedInput = {
  create?: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput> | Prisma.MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput[] | Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput[]
  connectOrCreate?: Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutPieceVersionInput | Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutPieceVersionInput[]
  upsert?: Prisma.MMSourcesOnPieceVersionsUpsertWithWhereUniqueWithoutPieceVersionInput | Prisma.MMSourcesOnPieceVersionsUpsertWithWhereUniqueWithoutPieceVersionInput[]
  createMany?: Prisma.MMSourcesOnPieceVersionsCreateManyPieceVersionInputEnvelope
  set?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  disconnect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  delete?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  connect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  update?: Prisma.MMSourcesOnPieceVersionsUpdateWithWhereUniqueWithoutPieceVersionInput | Prisma.MMSourcesOnPieceVersionsUpdateWithWhereUniqueWithoutPieceVersionInput[]
  updateMany?: Prisma.MMSourcesOnPieceVersionsUpdateManyWithWhereWithoutPieceVersionInput | Prisma.MMSourcesOnPieceVersionsUpdateManyWithWhereWithoutPieceVersionInput[]
  deleteMany?: Prisma.MMSourcesOnPieceVersionsScalarWhereInput | Prisma.MMSourcesOnPieceVersionsScalarWhereInput[]
}

export type MMSourcesOnPieceVersionsCreateNestedManyWithoutMMSourceInput = {
  create?: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutMMSourceInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput> | Prisma.MMSourcesOnPieceVersionsCreateWithoutMMSourceInput[] | Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput[]
  connectOrCreate?: Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutMMSourceInput | Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutMMSourceInput[]
  createMany?: Prisma.MMSourcesOnPieceVersionsCreateManyMMSourceInputEnvelope
  connect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
}

export type MMSourcesOnPieceVersionsUncheckedCreateNestedManyWithoutMMSourceInput = {
  create?: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutMMSourceInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput> | Prisma.MMSourcesOnPieceVersionsCreateWithoutMMSourceInput[] | Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput[]
  connectOrCreate?: Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutMMSourceInput | Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutMMSourceInput[]
  createMany?: Prisma.MMSourcesOnPieceVersionsCreateManyMMSourceInputEnvelope
  connect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
}

export type MMSourcesOnPieceVersionsUpdateManyWithoutMMSourceNestedInput = {
  create?: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutMMSourceInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput> | Prisma.MMSourcesOnPieceVersionsCreateWithoutMMSourceInput[] | Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput[]
  connectOrCreate?: Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutMMSourceInput | Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutMMSourceInput[]
  upsert?: Prisma.MMSourcesOnPieceVersionsUpsertWithWhereUniqueWithoutMMSourceInput | Prisma.MMSourcesOnPieceVersionsUpsertWithWhereUniqueWithoutMMSourceInput[]
  createMany?: Prisma.MMSourcesOnPieceVersionsCreateManyMMSourceInputEnvelope
  set?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  disconnect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  delete?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  connect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  update?: Prisma.MMSourcesOnPieceVersionsUpdateWithWhereUniqueWithoutMMSourceInput | Prisma.MMSourcesOnPieceVersionsUpdateWithWhereUniqueWithoutMMSourceInput[]
  updateMany?: Prisma.MMSourcesOnPieceVersionsUpdateManyWithWhereWithoutMMSourceInput | Prisma.MMSourcesOnPieceVersionsUpdateManyWithWhereWithoutMMSourceInput[]
  deleteMany?: Prisma.MMSourcesOnPieceVersionsScalarWhereInput | Prisma.MMSourcesOnPieceVersionsScalarWhereInput[]
}

export type MMSourcesOnPieceVersionsUncheckedUpdateManyWithoutMMSourceNestedInput = {
  create?: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutMMSourceInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput> | Prisma.MMSourcesOnPieceVersionsCreateWithoutMMSourceInput[] | Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput[]
  connectOrCreate?: Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutMMSourceInput | Prisma.MMSourcesOnPieceVersionsCreateOrConnectWithoutMMSourceInput[]
  upsert?: Prisma.MMSourcesOnPieceVersionsUpsertWithWhereUniqueWithoutMMSourceInput | Prisma.MMSourcesOnPieceVersionsUpsertWithWhereUniqueWithoutMMSourceInput[]
  createMany?: Prisma.MMSourcesOnPieceVersionsCreateManyMMSourceInputEnvelope
  set?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  disconnect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  delete?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  connect?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput | Prisma.MMSourcesOnPieceVersionsWhereUniqueInput[]
  update?: Prisma.MMSourcesOnPieceVersionsUpdateWithWhereUniqueWithoutMMSourceInput | Prisma.MMSourcesOnPieceVersionsUpdateWithWhereUniqueWithoutMMSourceInput[]
  updateMany?: Prisma.MMSourcesOnPieceVersionsUpdateManyWithWhereWithoutMMSourceInput | Prisma.MMSourcesOnPieceVersionsUpdateManyWithWhereWithoutMMSourceInput[]
  deleteMany?: Prisma.MMSourcesOnPieceVersionsScalarWhereInput | Prisma.MMSourcesOnPieceVersionsScalarWhereInput[]
}

export type MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput = {
  id?: string
  rank: number
  mMSource: Prisma.MMSourceCreateNestedOneWithoutPieceVersionsInput
}

export type MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput = {
  id?: string
  mMSourceId: string
  rank: number
}

export type MMSourcesOnPieceVersionsCreateOrConnectWithoutPieceVersionInput = {
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  create: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput>
}

export type MMSourcesOnPieceVersionsCreateManyPieceVersionInputEnvelope = {
  data: Prisma.MMSourcesOnPieceVersionsCreateManyPieceVersionInput | Prisma.MMSourcesOnPieceVersionsCreateManyPieceVersionInput[]
  skipDuplicates?: boolean
}

export type MMSourcesOnPieceVersionsUpsertWithWhereUniqueWithoutPieceVersionInput = {
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  update: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsUpdateWithoutPieceVersionInput, Prisma.MMSourcesOnPieceVersionsUncheckedUpdateWithoutPieceVersionInput>
  create: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutPieceVersionInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutPieceVersionInput>
}

export type MMSourcesOnPieceVersionsUpdateWithWhereUniqueWithoutPieceVersionInput = {
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  data: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsUpdateWithoutPieceVersionInput, Prisma.MMSourcesOnPieceVersionsUncheckedUpdateWithoutPieceVersionInput>
}

export type MMSourcesOnPieceVersionsUpdateManyWithWhereWithoutPieceVersionInput = {
  where: Prisma.MMSourcesOnPieceVersionsScalarWhereInput
  data: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsUpdateManyMutationInput, Prisma.MMSourcesOnPieceVersionsUncheckedUpdateManyWithoutPieceVersionInput>
}

export type MMSourcesOnPieceVersionsScalarWhereInput = {
  AND?: Prisma.MMSourcesOnPieceVersionsScalarWhereInput | Prisma.MMSourcesOnPieceVersionsScalarWhereInput[]
  OR?: Prisma.MMSourcesOnPieceVersionsScalarWhereInput[]
  NOT?: Prisma.MMSourcesOnPieceVersionsScalarWhereInput | Prisma.MMSourcesOnPieceVersionsScalarWhereInput[]
  id?: Prisma.UuidFilter<"MMSourcesOnPieceVersions"> | string
  pieceVersionId?: Prisma.UuidFilter<"MMSourcesOnPieceVersions"> | string
  mMSourceId?: Prisma.UuidFilter<"MMSourcesOnPieceVersions"> | string
  rank?: Prisma.IntFilter<"MMSourcesOnPieceVersions"> | number
}

export type MMSourcesOnPieceVersionsCreateWithoutMMSourceInput = {
  id?: string
  rank: number
  pieceVersion: Prisma.PieceVersionCreateNestedOneWithoutMMSourcesInput
}

export type MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput = {
  id?: string
  pieceVersionId: string
  rank: number
}

export type MMSourcesOnPieceVersionsCreateOrConnectWithoutMMSourceInput = {
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  create: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutMMSourceInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput>
}

export type MMSourcesOnPieceVersionsCreateManyMMSourceInputEnvelope = {
  data: Prisma.MMSourcesOnPieceVersionsCreateManyMMSourceInput | Prisma.MMSourcesOnPieceVersionsCreateManyMMSourceInput[]
  skipDuplicates?: boolean
}

export type MMSourcesOnPieceVersionsUpsertWithWhereUniqueWithoutMMSourceInput = {
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  update: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsUpdateWithoutMMSourceInput, Prisma.MMSourcesOnPieceVersionsUncheckedUpdateWithoutMMSourceInput>
  create: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateWithoutMMSourceInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateWithoutMMSourceInput>
}

export type MMSourcesOnPieceVersionsUpdateWithWhereUniqueWithoutMMSourceInput = {
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  data: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsUpdateWithoutMMSourceInput, Prisma.MMSourcesOnPieceVersionsUncheckedUpdateWithoutMMSourceInput>
}

export type MMSourcesOnPieceVersionsUpdateManyWithWhereWithoutMMSourceInput = {
  where: Prisma.MMSourcesOnPieceVersionsScalarWhereInput
  data: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsUpdateManyMutationInput, Prisma.MMSourcesOnPieceVersionsUncheckedUpdateManyWithoutMMSourceInput>
}

export type MMSourcesOnPieceVersionsCreateManyPieceVersionInput = {
  id?: string
  mMSourceId: string
  rank: number
}

export type MMSourcesOnPieceVersionsUpdateWithoutPieceVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  mMSource?: Prisma.MMSourceUpdateOneRequiredWithoutPieceVersionsNestedInput
}

export type MMSourcesOnPieceVersionsUncheckedUpdateWithoutPieceVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mMSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MMSourcesOnPieceVersionsUncheckedUpdateManyWithoutPieceVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mMSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MMSourcesOnPieceVersionsCreateManyMMSourceInput = {
  id?: string
  pieceVersionId: string
  rank: number
}

export type MMSourcesOnPieceVersionsUpdateWithoutMMSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  pieceVersion?: Prisma.PieceVersionUpdateOneRequiredWithoutMMSourcesNestedInput
}

export type MMSourcesOnPieceVersionsUncheckedUpdateWithoutMMSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pieceVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MMSourcesOnPieceVersionsUncheckedUpdateManyWithoutMMSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pieceVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
}



export type MMSourcesOnPieceVersionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pieceVersionId?: boolean
  mMSourceId?: boolean
  rank?: boolean
  pieceVersion?: boolean | Prisma.PieceVersionDefaultArgs<ExtArgs>
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mMSourcesOnPieceVersions"]>

export type MMSourcesOnPieceVersionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pieceVersionId?: boolean
  mMSourceId?: boolean
  rank?: boolean
  pieceVersion?: boolean | Prisma.PieceVersionDefaultArgs<ExtArgs>
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mMSourcesOnPieceVersions"]>

export type MMSourcesOnPieceVersionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pieceVersionId?: boolean
  mMSourceId?: boolean
  rank?: boolean
  pieceVersion?: boolean | Prisma.PieceVersionDefaultArgs<ExtArgs>
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mMSourcesOnPieceVersions"]>

export type MMSourcesOnPieceVersionsSelectScalar = {
  id?: boolean
  pieceVersionId?: boolean
  mMSourceId?: boolean
  rank?: boolean
}

export type MMSourcesOnPieceVersionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pieceVersionId" | "mMSourceId" | "rank", ExtArgs["result"]["mMSourcesOnPieceVersions"]>
export type MMSourcesOnPieceVersionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pieceVersion?: boolean | Prisma.PieceVersionDefaultArgs<ExtArgs>
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
}
export type MMSourcesOnPieceVersionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pieceVersion?: boolean | Prisma.PieceVersionDefaultArgs<ExtArgs>
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
}
export type MMSourcesOnPieceVersionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pieceVersion?: boolean | Prisma.PieceVersionDefaultArgs<ExtArgs>
  mMSource?: boolean | Prisma.MMSourceDefaultArgs<ExtArgs>
}

export type $MMSourcesOnPieceVersionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MMSourcesOnPieceVersions"
  objects: {
    pieceVersion: Prisma.$PieceVersionPayload<ExtArgs>
    mMSource: Prisma.$MMSourcePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pieceVersionId: string
    mMSourceId: string
    rank: number
  }, ExtArgs["result"]["mMSourcesOnPieceVersions"]>
  composites: {}
}

export type MMSourcesOnPieceVersionsGetPayload<S extends boolean | null | undefined | MMSourcesOnPieceVersionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload, S>

export type MMSourcesOnPieceVersionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MMSourcesOnPieceVersionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MMSourcesOnPieceVersionsCountAggregateInputType | true
  }

export interface MMSourcesOnPieceVersionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MMSourcesOnPieceVersions'], meta: { name: 'MMSourcesOnPieceVersions' } }
  /**
   * Find zero or one MMSourcesOnPieceVersions that matches the filter.
   * @param {MMSourcesOnPieceVersionsFindUniqueArgs} args - Arguments to find a MMSourcesOnPieceVersions
   * @example
   * // Get one MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MMSourcesOnPieceVersionsFindUniqueArgs>(args: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MMSourcesOnPieceVersionsClient<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MMSourcesOnPieceVersions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MMSourcesOnPieceVersionsFindUniqueOrThrowArgs} args - Arguments to find a MMSourcesOnPieceVersions
   * @example
   * // Get one MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MMSourcesOnPieceVersionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MMSourcesOnPieceVersionsClient<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MMSourcesOnPieceVersions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MMSourcesOnPieceVersionsFindFirstArgs} args - Arguments to find a MMSourcesOnPieceVersions
   * @example
   * // Get one MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MMSourcesOnPieceVersionsFindFirstArgs>(args?: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__MMSourcesOnPieceVersionsClient<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MMSourcesOnPieceVersions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MMSourcesOnPieceVersionsFindFirstOrThrowArgs} args - Arguments to find a MMSourcesOnPieceVersions
   * @example
   * // Get one MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MMSourcesOnPieceVersionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MMSourcesOnPieceVersionsClient<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MMSourcesOnPieceVersions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MMSourcesOnPieceVersionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.findMany()
   * 
   * // Get first 10 MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mMSourcesOnPieceVersionsWithIdOnly = await prisma.mMSourcesOnPieceVersions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MMSourcesOnPieceVersionsFindManyArgs>(args?: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MMSourcesOnPieceVersions.
   * @param {MMSourcesOnPieceVersionsCreateArgs} args - Arguments to create a MMSourcesOnPieceVersions.
   * @example
   * // Create one MMSourcesOnPieceVersions
   * const MMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.create({
   *   data: {
   *     // ... data to create a MMSourcesOnPieceVersions
   *   }
   * })
   * 
   */
  create<T extends MMSourcesOnPieceVersionsCreateArgs>(args: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsCreateArgs<ExtArgs>>): Prisma.Prisma__MMSourcesOnPieceVersionsClient<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MMSourcesOnPieceVersions.
   * @param {MMSourcesOnPieceVersionsCreateManyArgs} args - Arguments to create many MMSourcesOnPieceVersions.
   * @example
   * // Create many MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MMSourcesOnPieceVersionsCreateManyArgs>(args?: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MMSourcesOnPieceVersions and returns the data saved in the database.
   * @param {MMSourcesOnPieceVersionsCreateManyAndReturnArgs} args - Arguments to create many MMSourcesOnPieceVersions.
   * @example
   * // Create many MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MMSourcesOnPieceVersions and only return the `id`
   * const mMSourcesOnPieceVersionsWithIdOnly = await prisma.mMSourcesOnPieceVersions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MMSourcesOnPieceVersionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MMSourcesOnPieceVersions.
   * @param {MMSourcesOnPieceVersionsDeleteArgs} args - Arguments to delete one MMSourcesOnPieceVersions.
   * @example
   * // Delete one MMSourcesOnPieceVersions
   * const MMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.delete({
   *   where: {
   *     // ... filter to delete one MMSourcesOnPieceVersions
   *   }
   * })
   * 
   */
  delete<T extends MMSourcesOnPieceVersionsDeleteArgs>(args: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsDeleteArgs<ExtArgs>>): Prisma.Prisma__MMSourcesOnPieceVersionsClient<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MMSourcesOnPieceVersions.
   * @param {MMSourcesOnPieceVersionsUpdateArgs} args - Arguments to update one MMSourcesOnPieceVersions.
   * @example
   * // Update one MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MMSourcesOnPieceVersionsUpdateArgs>(args: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsUpdateArgs<ExtArgs>>): Prisma.Prisma__MMSourcesOnPieceVersionsClient<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MMSourcesOnPieceVersions.
   * @param {MMSourcesOnPieceVersionsDeleteManyArgs} args - Arguments to filter MMSourcesOnPieceVersions to delete.
   * @example
   * // Delete a few MMSourcesOnPieceVersions
   * const { count } = await prisma.mMSourcesOnPieceVersions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MMSourcesOnPieceVersionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MMSourcesOnPieceVersions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MMSourcesOnPieceVersionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MMSourcesOnPieceVersionsUpdateManyArgs>(args: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MMSourcesOnPieceVersions and returns the data updated in the database.
   * @param {MMSourcesOnPieceVersionsUpdateManyAndReturnArgs} args - Arguments to update many MMSourcesOnPieceVersions.
   * @example
   * // Update many MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MMSourcesOnPieceVersions and only return the `id`
   * const mMSourcesOnPieceVersionsWithIdOnly = await prisma.mMSourcesOnPieceVersions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MMSourcesOnPieceVersionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MMSourcesOnPieceVersions.
   * @param {MMSourcesOnPieceVersionsUpsertArgs} args - Arguments to update or create a MMSourcesOnPieceVersions.
   * @example
   * // Update or create a MMSourcesOnPieceVersions
   * const mMSourcesOnPieceVersions = await prisma.mMSourcesOnPieceVersions.upsert({
   *   create: {
   *     // ... data to create a MMSourcesOnPieceVersions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MMSourcesOnPieceVersions we want to update
   *   }
   * })
   */
  upsert<T extends MMSourcesOnPieceVersionsUpsertArgs>(args: Prisma.SelectSubset<T, MMSourcesOnPieceVersionsUpsertArgs<ExtArgs>>): Prisma.Prisma__MMSourcesOnPieceVersionsClient<runtime.Types.Result.GetResult<Prisma.$MMSourcesOnPieceVersionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MMSourcesOnPieceVersions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MMSourcesOnPieceVersionsCountArgs} args - Arguments to filter MMSourcesOnPieceVersions to count.
   * @example
   * // Count the number of MMSourcesOnPieceVersions
   * const count = await prisma.mMSourcesOnPieceVersions.count({
   *   where: {
   *     // ... the filter for the MMSourcesOnPieceVersions we want to count
   *   }
   * })
  **/
  count<T extends MMSourcesOnPieceVersionsCountArgs>(
    args?: Prisma.Subset<T, MMSourcesOnPieceVersionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MMSourcesOnPieceVersionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MMSourcesOnPieceVersions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MMSourcesOnPieceVersionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MMSourcesOnPieceVersionsAggregateArgs>(args: Prisma.Subset<T, MMSourcesOnPieceVersionsAggregateArgs>): Prisma.PrismaPromise<GetMMSourcesOnPieceVersionsAggregateType<T>>

  /**
   * Group by MMSourcesOnPieceVersions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MMSourcesOnPieceVersionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MMSourcesOnPieceVersionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MMSourcesOnPieceVersionsGroupByArgs['orderBy'] }
      : { orderBy?: MMSourcesOnPieceVersionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MMSourcesOnPieceVersionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMMSourcesOnPieceVersionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MMSourcesOnPieceVersions model
 */
readonly fields: MMSourcesOnPieceVersionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MMSourcesOnPieceVersions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MMSourcesOnPieceVersionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pieceVersion<T extends Prisma.PieceVersionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PieceVersionDefaultArgs<ExtArgs>>): Prisma.Prisma__PieceVersionClient<runtime.Types.Result.GetResult<Prisma.$PieceVersionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  mMSource<T extends Prisma.MMSourceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MMSourceDefaultArgs<ExtArgs>>): Prisma.Prisma__MMSourceClient<runtime.Types.Result.GetResult<Prisma.$MMSourcePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MMSourcesOnPieceVersions model
 */
export interface MMSourcesOnPieceVersionsFieldRefs {
  readonly id: Prisma.FieldRef<"MMSourcesOnPieceVersions", 'String'>
  readonly pieceVersionId: Prisma.FieldRef<"MMSourcesOnPieceVersions", 'String'>
  readonly mMSourceId: Prisma.FieldRef<"MMSourcesOnPieceVersions", 'String'>
  readonly rank: Prisma.FieldRef<"MMSourcesOnPieceVersions", 'Int'>
}
    

// Custom InputTypes
/**
 * MMSourcesOnPieceVersions findUnique
 */
export type MMSourcesOnPieceVersionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsInclude<ExtArgs> | null
  /**
   * Filter, which MMSourcesOnPieceVersions to fetch.
   */
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
}

/**
 * MMSourcesOnPieceVersions findUniqueOrThrow
 */
export type MMSourcesOnPieceVersionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsInclude<ExtArgs> | null
  /**
   * Filter, which MMSourcesOnPieceVersions to fetch.
   */
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
}

/**
 * MMSourcesOnPieceVersions findFirst
 */
export type MMSourcesOnPieceVersionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsInclude<ExtArgs> | null
  /**
   * Filter, which MMSourcesOnPieceVersions to fetch.
   */
  where?: Prisma.MMSourcesOnPieceVersionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MMSourcesOnPieceVersions to fetch.
   */
  orderBy?: Prisma.MMSourcesOnPieceVersionsOrderByWithRelationInput | Prisma.MMSourcesOnPieceVersionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MMSourcesOnPieceVersions.
   */
  cursor?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MMSourcesOnPieceVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MMSourcesOnPieceVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MMSourcesOnPieceVersions.
   */
  distinct?: Prisma.MMSourcesOnPieceVersionsScalarFieldEnum | Prisma.MMSourcesOnPieceVersionsScalarFieldEnum[]
}

/**
 * MMSourcesOnPieceVersions findFirstOrThrow
 */
export type MMSourcesOnPieceVersionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsInclude<ExtArgs> | null
  /**
   * Filter, which MMSourcesOnPieceVersions to fetch.
   */
  where?: Prisma.MMSourcesOnPieceVersionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MMSourcesOnPieceVersions to fetch.
   */
  orderBy?: Prisma.MMSourcesOnPieceVersionsOrderByWithRelationInput | Prisma.MMSourcesOnPieceVersionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MMSourcesOnPieceVersions.
   */
  cursor?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MMSourcesOnPieceVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MMSourcesOnPieceVersions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MMSourcesOnPieceVersions.
   */
  distinct?: Prisma.MMSourcesOnPieceVersionsScalarFieldEnum | Prisma.MMSourcesOnPieceVersionsScalarFieldEnum[]
}

/**
 * MMSourcesOnPieceVersions findMany
 */
export type MMSourcesOnPieceVersionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsInclude<ExtArgs> | null
  /**
   * Filter, which MMSourcesOnPieceVersions to fetch.
   */
  where?: Prisma.MMSourcesOnPieceVersionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MMSourcesOnPieceVersions to fetch.
   */
  orderBy?: Prisma.MMSourcesOnPieceVersionsOrderByWithRelationInput | Prisma.MMSourcesOnPieceVersionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MMSourcesOnPieceVersions.
   */
  cursor?: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MMSourcesOnPieceVersions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MMSourcesOnPieceVersions.
   */
  skip?: number
  distinct?: Prisma.MMSourcesOnPieceVersionsScalarFieldEnum | Prisma.MMSourcesOnPieceVersionsScalarFieldEnum[]
}

/**
 * MMSourcesOnPieceVersions create
 */
export type MMSourcesOnPieceVersionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsInclude<ExtArgs> | null
  /**
   * The data needed to create a MMSourcesOnPieceVersions.
   */
  data: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateInput>
}

/**
 * MMSourcesOnPieceVersions createMany
 */
export type MMSourcesOnPieceVersionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MMSourcesOnPieceVersions.
   */
  data: Prisma.MMSourcesOnPieceVersionsCreateManyInput | Prisma.MMSourcesOnPieceVersionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MMSourcesOnPieceVersions createManyAndReturn
 */
export type MMSourcesOnPieceVersionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * The data used to create many MMSourcesOnPieceVersions.
   */
  data: Prisma.MMSourcesOnPieceVersionsCreateManyInput | Prisma.MMSourcesOnPieceVersionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MMSourcesOnPieceVersions update
 */
export type MMSourcesOnPieceVersionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsInclude<ExtArgs> | null
  /**
   * The data needed to update a MMSourcesOnPieceVersions.
   */
  data: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsUpdateInput, Prisma.MMSourcesOnPieceVersionsUncheckedUpdateInput>
  /**
   * Choose, which MMSourcesOnPieceVersions to update.
   */
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
}

/**
 * MMSourcesOnPieceVersions updateMany
 */
export type MMSourcesOnPieceVersionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MMSourcesOnPieceVersions.
   */
  data: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsUpdateManyMutationInput, Prisma.MMSourcesOnPieceVersionsUncheckedUpdateManyInput>
  /**
   * Filter which MMSourcesOnPieceVersions to update
   */
  where?: Prisma.MMSourcesOnPieceVersionsWhereInput
  /**
   * Limit how many MMSourcesOnPieceVersions to update.
   */
  limit?: number
}

/**
 * MMSourcesOnPieceVersions updateManyAndReturn
 */
export type MMSourcesOnPieceVersionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * The data used to update MMSourcesOnPieceVersions.
   */
  data: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsUpdateManyMutationInput, Prisma.MMSourcesOnPieceVersionsUncheckedUpdateManyInput>
  /**
   * Filter which MMSourcesOnPieceVersions to update
   */
  where?: Prisma.MMSourcesOnPieceVersionsWhereInput
  /**
   * Limit how many MMSourcesOnPieceVersions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MMSourcesOnPieceVersions upsert
 */
export type MMSourcesOnPieceVersionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsInclude<ExtArgs> | null
  /**
   * The filter to search for the MMSourcesOnPieceVersions to update in case it exists.
   */
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
  /**
   * In case the MMSourcesOnPieceVersions found by the `where` argument doesn't exist, create a new MMSourcesOnPieceVersions with this data.
   */
  create: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsCreateInput, Prisma.MMSourcesOnPieceVersionsUncheckedCreateInput>
  /**
   * In case the MMSourcesOnPieceVersions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MMSourcesOnPieceVersionsUpdateInput, Prisma.MMSourcesOnPieceVersionsUncheckedUpdateInput>
}

/**
 * MMSourcesOnPieceVersions delete
 */
export type MMSourcesOnPieceVersionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsInclude<ExtArgs> | null
  /**
   * Filter which MMSourcesOnPieceVersions to delete.
   */
  where: Prisma.MMSourcesOnPieceVersionsWhereUniqueInput
}

/**
 * MMSourcesOnPieceVersions deleteMany
 */
export type MMSourcesOnPieceVersionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MMSourcesOnPieceVersions to delete
   */
  where?: Prisma.MMSourcesOnPieceVersionsWhereInput
  /**
   * Limit how many MMSourcesOnPieceVersions to delete.
   */
  limit?: number
}

/**
 * MMSourcesOnPieceVersions without action
 */
export type MMSourcesOnPieceVersionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MMSourcesOnPieceVersions
   */
  select?: Prisma.MMSourcesOnPieceVersionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MMSourcesOnPieceVersions
   */
  omit?: Prisma.MMSourcesOnPieceVersionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MMSourcesOnPieceVersionsInclude<ExtArgs> | null
}
