
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Person` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Person
 * 
 */
export type PersonModel = runtime.Types.Result.DefaultSelection<Prisma.$PersonPayload>

export type AggregatePerson = {
  _count: PersonCountAggregateOutputType | null
  _avg: PersonAvgAggregateOutputType | null
  _sum: PersonSumAggregateOutputType | null
  _min: PersonMinAggregateOutputType | null
  _max: PersonMaxAggregateOutputType | null
}

export type PersonAvgAggregateOutputType = {
  birthYear: number | null
  deathYear: number | null
}

export type PersonSumAggregateOutputType = {
  birthYear: number | null
  deathYear: number | null
}

export type PersonMinAggregateOutputType = {
  id: string | null
  firstName: string | null
  lastName: string | null
  birthYear: number | null
  deathYear: number | null
  creatorId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PersonMaxAggregateOutputType = {
  id: string | null
  firstName: string | null
  lastName: string | null
  birthYear: number | null
  deathYear: number | null
  creatorId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PersonCountAggregateOutputType = {
  id: number
  firstName: number
  lastName: number
  birthYear: number
  deathYear: number
  creatorId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PersonAvgAggregateInputType = {
  birthYear?: true
  deathYear?: true
}

export type PersonSumAggregateInputType = {
  birthYear?: true
  deathYear?: true
}

export type PersonMinAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  birthYear?: true
  deathYear?: true
  creatorId?: true
  createdAt?: true
  updatedAt?: true
}

export type PersonMaxAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  birthYear?: true
  deathYear?: true
  creatorId?: true
  createdAt?: true
  updatedAt?: true
}

export type PersonCountAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  birthYear?: true
  deathYear?: true
  creatorId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PersonAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Person to aggregate.
   */
  where?: Prisma.PersonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PersonOrderByWithRelationInput | Prisma.PersonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PersonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned People
  **/
  _count?: true | PersonCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PersonAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PersonSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PersonMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PersonMaxAggregateInputType
}

export type GetPersonAggregateType<T extends PersonAggregateArgs> = {
      [P in keyof T & keyof AggregatePerson]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePerson[P]>
    : Prisma.GetScalarType<T[P], AggregatePerson[P]>
}




export type PersonGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PersonWhereInput
  orderBy?: Prisma.PersonOrderByWithAggregationInput | Prisma.PersonOrderByWithAggregationInput[]
  by: Prisma.PersonScalarFieldEnum[] | Prisma.PersonScalarFieldEnum
  having?: Prisma.PersonScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PersonCountAggregateInputType | true
  _avg?: PersonAvgAggregateInputType
  _sum?: PersonSumAggregateInputType
  _min?: PersonMinAggregateInputType
  _max?: PersonMaxAggregateInputType
}

export type PersonGroupByOutputType = {
  id: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear: number | null
  creatorId: string | null
  createdAt: Date
  updatedAt: Date
  _count: PersonCountAggregateOutputType | null
  _avg: PersonAvgAggregateOutputType | null
  _sum: PersonSumAggregateOutputType | null
  _min: PersonMinAggregateOutputType | null
  _max: PersonMaxAggregateOutputType | null
}

type GetPersonGroupByPayload<T extends PersonGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PersonGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PersonGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PersonGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PersonGroupByOutputType[P]>
      }
    >
  >



export type PersonWhereInput = {
  AND?: Prisma.PersonWhereInput | Prisma.PersonWhereInput[]
  OR?: Prisma.PersonWhereInput[]
  NOT?: Prisma.PersonWhereInput | Prisma.PersonWhereInput[]
  id?: Prisma.UuidFilter<"Person"> | string
  firstName?: Prisma.StringFilter<"Person"> | string
  lastName?: Prisma.StringFilter<"Person"> | string
  birthYear?: Prisma.IntFilter<"Person"> | number
  deathYear?: Prisma.IntNullableFilter<"Person"> | number | null
  creatorId?: Prisma.UuidNullableFilter<"Person"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Person"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Person"> | Date | string
  collections?: Prisma.CollectionListRelationFilter
  compositions?: Prisma.PieceListRelationFilter
  contributions?: Prisma.ContributionListRelationFilter
  creator?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type PersonOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  birthYear?: Prisma.SortOrder
  deathYear?: Prisma.SortOrderInput | Prisma.SortOrder
  creatorId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  collections?: Prisma.CollectionOrderByRelationAggregateInput
  compositions?: Prisma.PieceOrderByRelationAggregateInput
  contributions?: Prisma.ContributionOrderByRelationAggregateInput
  creator?: Prisma.UserOrderByWithRelationInput
}

export type PersonWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  firstName_lastName?: Prisma.PersonFirstNameLastNameCompoundUniqueInput
  AND?: Prisma.PersonWhereInput | Prisma.PersonWhereInput[]
  OR?: Prisma.PersonWhereInput[]
  NOT?: Prisma.PersonWhereInput | Prisma.PersonWhereInput[]
  firstName?: Prisma.StringFilter<"Person"> | string
  lastName?: Prisma.StringFilter<"Person"> | string
  birthYear?: Prisma.IntFilter<"Person"> | number
  deathYear?: Prisma.IntNullableFilter<"Person"> | number | null
  creatorId?: Prisma.UuidNullableFilter<"Person"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Person"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Person"> | Date | string
  collections?: Prisma.CollectionListRelationFilter
  compositions?: Prisma.PieceListRelationFilter
  contributions?: Prisma.ContributionListRelationFilter
  creator?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "firstName_lastName">

export type PersonOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  birthYear?: Prisma.SortOrder
  deathYear?: Prisma.SortOrderInput | Prisma.SortOrder
  creatorId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PersonCountOrderByAggregateInput
  _avg?: Prisma.PersonAvgOrderByAggregateInput
  _max?: Prisma.PersonMaxOrderByAggregateInput
  _min?: Prisma.PersonMinOrderByAggregateInput
  _sum?: Prisma.PersonSumOrderByAggregateInput
}

export type PersonScalarWhereWithAggregatesInput = {
  AND?: Prisma.PersonScalarWhereWithAggregatesInput | Prisma.PersonScalarWhereWithAggregatesInput[]
  OR?: Prisma.PersonScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PersonScalarWhereWithAggregatesInput | Prisma.PersonScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Person"> | string
  firstName?: Prisma.StringWithAggregatesFilter<"Person"> | string
  lastName?: Prisma.StringWithAggregatesFilter<"Person"> | string
  birthYear?: Prisma.IntWithAggregatesFilter<"Person"> | number
  deathYear?: Prisma.IntNullableWithAggregatesFilter<"Person"> | number | null
  creatorId?: Prisma.UuidNullableWithAggregatesFilter<"Person"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Person"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Person"> | Date | string
}

export type PersonCreateInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionCreateNestedManyWithoutComposerInput
  compositions?: Prisma.PieceCreateNestedManyWithoutComposerInput
  contributions?: Prisma.ContributionCreateNestedManyWithoutPersonInput
  creator?: Prisma.UserCreateNestedOneWithoutPersonsInput
}

export type PersonUncheckedCreateInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  creatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionUncheckedCreateNestedManyWithoutComposerInput
  compositions?: Prisma.PieceUncheckedCreateNestedManyWithoutComposerInput
  contributions?: Prisma.ContributionUncheckedCreateNestedManyWithoutPersonInput
}

export type PersonUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUpdateManyWithoutComposerNestedInput
  compositions?: Prisma.PieceUpdateManyWithoutComposerNestedInput
  contributions?: Prisma.ContributionUpdateManyWithoutPersonNestedInput
  creator?: Prisma.UserUpdateOneWithoutPersonsNestedInput
}

export type PersonUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  creatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUncheckedUpdateManyWithoutComposerNestedInput
  compositions?: Prisma.PieceUncheckedUpdateManyWithoutComposerNestedInput
  contributions?: Prisma.ContributionUncheckedUpdateManyWithoutPersonNestedInput
}

export type PersonCreateManyInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  creatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PersonUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  creatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonScalarRelationFilter = {
  is?: Prisma.PersonWhereInput
  isNot?: Prisma.PersonWhereInput
}

export type PersonNullableScalarRelationFilter = {
  is?: Prisma.PersonWhereInput | null
  isNot?: Prisma.PersonWhereInput | null
}

export type PersonFirstNameLastNameCompoundUniqueInput = {
  firstName: string
  lastName: string
}

export type PersonCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  birthYear?: Prisma.SortOrder
  deathYear?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PersonAvgOrderByAggregateInput = {
  birthYear?: Prisma.SortOrder
  deathYear?: Prisma.SortOrder
}

export type PersonMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  birthYear?: Prisma.SortOrder
  deathYear?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PersonMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  birthYear?: Prisma.SortOrder
  deathYear?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PersonSumOrderByAggregateInput = {
  birthYear?: Prisma.SortOrder
  deathYear?: Prisma.SortOrder
}

export type PersonListRelationFilter = {
  every?: Prisma.PersonWhereInput
  some?: Prisma.PersonWhereInput
  none?: Prisma.PersonWhereInput
}

export type PersonOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PersonCreateNestedOneWithoutCollectionsInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutCollectionsInput, Prisma.PersonUncheckedCreateWithoutCollectionsInput>
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutCollectionsInput
  connect?: Prisma.PersonWhereUniqueInput
}

export type PersonUpdateOneRequiredWithoutCollectionsNestedInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutCollectionsInput, Prisma.PersonUncheckedCreateWithoutCollectionsInput>
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutCollectionsInput
  upsert?: Prisma.PersonUpsertWithoutCollectionsInput
  connect?: Prisma.PersonWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PersonUpdateToOneWithWhereWithoutCollectionsInput, Prisma.PersonUpdateWithoutCollectionsInput>, Prisma.PersonUncheckedUpdateWithoutCollectionsInput>
}

export type PersonCreateNestedOneWithoutCompositionsInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutCompositionsInput, Prisma.PersonUncheckedCreateWithoutCompositionsInput>
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutCompositionsInput
  connect?: Prisma.PersonWhereUniqueInput
}

export type PersonUpdateOneRequiredWithoutCompositionsNestedInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutCompositionsInput, Prisma.PersonUncheckedCreateWithoutCompositionsInput>
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutCompositionsInput
  upsert?: Prisma.PersonUpsertWithoutCompositionsInput
  connect?: Prisma.PersonWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PersonUpdateToOneWithWhereWithoutCompositionsInput, Prisma.PersonUpdateWithoutCompositionsInput>, Prisma.PersonUncheckedUpdateWithoutCompositionsInput>
}

export type PersonCreateNestedOneWithoutContributionsInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutContributionsInput, Prisma.PersonUncheckedCreateWithoutContributionsInput>
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutContributionsInput
  connect?: Prisma.PersonWhereUniqueInput
}

export type PersonUpdateOneWithoutContributionsNestedInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutContributionsInput, Prisma.PersonUncheckedCreateWithoutContributionsInput>
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutContributionsInput
  upsert?: Prisma.PersonUpsertWithoutContributionsInput
  disconnect?: Prisma.PersonWhereInput | boolean
  delete?: Prisma.PersonWhereInput | boolean
  connect?: Prisma.PersonWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PersonUpdateToOneWithWhereWithoutContributionsInput, Prisma.PersonUpdateWithoutContributionsInput>, Prisma.PersonUncheckedUpdateWithoutContributionsInput>
}

export type PersonCreateNestedManyWithoutCreatorInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutCreatorInput, Prisma.PersonUncheckedCreateWithoutCreatorInput> | Prisma.PersonCreateWithoutCreatorInput[] | Prisma.PersonUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutCreatorInput | Prisma.PersonCreateOrConnectWithoutCreatorInput[]
  createMany?: Prisma.PersonCreateManyCreatorInputEnvelope
  connect?: Prisma.PersonWhereUniqueInput | Prisma.PersonWhereUniqueInput[]
}

export type PersonUncheckedCreateNestedManyWithoutCreatorInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutCreatorInput, Prisma.PersonUncheckedCreateWithoutCreatorInput> | Prisma.PersonCreateWithoutCreatorInput[] | Prisma.PersonUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutCreatorInput | Prisma.PersonCreateOrConnectWithoutCreatorInput[]
  createMany?: Prisma.PersonCreateManyCreatorInputEnvelope
  connect?: Prisma.PersonWhereUniqueInput | Prisma.PersonWhereUniqueInput[]
}

export type PersonUpdateManyWithoutCreatorNestedInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutCreatorInput, Prisma.PersonUncheckedCreateWithoutCreatorInput> | Prisma.PersonCreateWithoutCreatorInput[] | Prisma.PersonUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutCreatorInput | Prisma.PersonCreateOrConnectWithoutCreatorInput[]
  upsert?: Prisma.PersonUpsertWithWhereUniqueWithoutCreatorInput | Prisma.PersonUpsertWithWhereUniqueWithoutCreatorInput[]
  createMany?: Prisma.PersonCreateManyCreatorInputEnvelope
  set?: Prisma.PersonWhereUniqueInput | Prisma.PersonWhereUniqueInput[]
  disconnect?: Prisma.PersonWhereUniqueInput | Prisma.PersonWhereUniqueInput[]
  delete?: Prisma.PersonWhereUniqueInput | Prisma.PersonWhereUniqueInput[]
  connect?: Prisma.PersonWhereUniqueInput | Prisma.PersonWhereUniqueInput[]
  update?: Prisma.PersonUpdateWithWhereUniqueWithoutCreatorInput | Prisma.PersonUpdateWithWhereUniqueWithoutCreatorInput[]
  updateMany?: Prisma.PersonUpdateManyWithWhereWithoutCreatorInput | Prisma.PersonUpdateManyWithWhereWithoutCreatorInput[]
  deleteMany?: Prisma.PersonScalarWhereInput | Prisma.PersonScalarWhereInput[]
}

export type PersonUncheckedUpdateManyWithoutCreatorNestedInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutCreatorInput, Prisma.PersonUncheckedCreateWithoutCreatorInput> | Prisma.PersonCreateWithoutCreatorInput[] | Prisma.PersonUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutCreatorInput | Prisma.PersonCreateOrConnectWithoutCreatorInput[]
  upsert?: Prisma.PersonUpsertWithWhereUniqueWithoutCreatorInput | Prisma.PersonUpsertWithWhereUniqueWithoutCreatorInput[]
  createMany?: Prisma.PersonCreateManyCreatorInputEnvelope
  set?: Prisma.PersonWhereUniqueInput | Prisma.PersonWhereUniqueInput[]
  disconnect?: Prisma.PersonWhereUniqueInput | Prisma.PersonWhereUniqueInput[]
  delete?: Prisma.PersonWhereUniqueInput | Prisma.PersonWhereUniqueInput[]
  connect?: Prisma.PersonWhereUniqueInput | Prisma.PersonWhereUniqueInput[]
  update?: Prisma.PersonUpdateWithWhereUniqueWithoutCreatorInput | Prisma.PersonUpdateWithWhereUniqueWithoutCreatorInput[]
  updateMany?: Prisma.PersonUpdateManyWithWhereWithoutCreatorInput | Prisma.PersonUpdateManyWithWhereWithoutCreatorInput[]
  deleteMany?: Prisma.PersonScalarWhereInput | Prisma.PersonScalarWhereInput[]
}

export type PersonCreateWithoutCollectionsInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  compositions?: Prisma.PieceCreateNestedManyWithoutComposerInput
  contributions?: Prisma.ContributionCreateNestedManyWithoutPersonInput
  creator?: Prisma.UserCreateNestedOneWithoutPersonsInput
}

export type PersonUncheckedCreateWithoutCollectionsInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  creatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  compositions?: Prisma.PieceUncheckedCreateNestedManyWithoutComposerInput
  contributions?: Prisma.ContributionUncheckedCreateNestedManyWithoutPersonInput
}

export type PersonCreateOrConnectWithoutCollectionsInput = {
  where: Prisma.PersonWhereUniqueInput
  create: Prisma.XOR<Prisma.PersonCreateWithoutCollectionsInput, Prisma.PersonUncheckedCreateWithoutCollectionsInput>
}

export type PersonUpsertWithoutCollectionsInput = {
  update: Prisma.XOR<Prisma.PersonUpdateWithoutCollectionsInput, Prisma.PersonUncheckedUpdateWithoutCollectionsInput>
  create: Prisma.XOR<Prisma.PersonCreateWithoutCollectionsInput, Prisma.PersonUncheckedCreateWithoutCollectionsInput>
  where?: Prisma.PersonWhereInput
}

export type PersonUpdateToOneWithWhereWithoutCollectionsInput = {
  where?: Prisma.PersonWhereInput
  data: Prisma.XOR<Prisma.PersonUpdateWithoutCollectionsInput, Prisma.PersonUncheckedUpdateWithoutCollectionsInput>
}

export type PersonUpdateWithoutCollectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  compositions?: Prisma.PieceUpdateManyWithoutComposerNestedInput
  contributions?: Prisma.ContributionUpdateManyWithoutPersonNestedInput
  creator?: Prisma.UserUpdateOneWithoutPersonsNestedInput
}

export type PersonUncheckedUpdateWithoutCollectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  creatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  compositions?: Prisma.PieceUncheckedUpdateManyWithoutComposerNestedInput
  contributions?: Prisma.ContributionUncheckedUpdateManyWithoutPersonNestedInput
}

export type PersonCreateWithoutCompositionsInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionCreateNestedManyWithoutComposerInput
  contributions?: Prisma.ContributionCreateNestedManyWithoutPersonInput
  creator?: Prisma.UserCreateNestedOneWithoutPersonsInput
}

export type PersonUncheckedCreateWithoutCompositionsInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  creatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionUncheckedCreateNestedManyWithoutComposerInput
  contributions?: Prisma.ContributionUncheckedCreateNestedManyWithoutPersonInput
}

export type PersonCreateOrConnectWithoutCompositionsInput = {
  where: Prisma.PersonWhereUniqueInput
  create: Prisma.XOR<Prisma.PersonCreateWithoutCompositionsInput, Prisma.PersonUncheckedCreateWithoutCompositionsInput>
}

export type PersonUpsertWithoutCompositionsInput = {
  update: Prisma.XOR<Prisma.PersonUpdateWithoutCompositionsInput, Prisma.PersonUncheckedUpdateWithoutCompositionsInput>
  create: Prisma.XOR<Prisma.PersonCreateWithoutCompositionsInput, Prisma.PersonUncheckedCreateWithoutCompositionsInput>
  where?: Prisma.PersonWhereInput
}

export type PersonUpdateToOneWithWhereWithoutCompositionsInput = {
  where?: Prisma.PersonWhereInput
  data: Prisma.XOR<Prisma.PersonUpdateWithoutCompositionsInput, Prisma.PersonUncheckedUpdateWithoutCompositionsInput>
}

export type PersonUpdateWithoutCompositionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUpdateManyWithoutComposerNestedInput
  contributions?: Prisma.ContributionUpdateManyWithoutPersonNestedInput
  creator?: Prisma.UserUpdateOneWithoutPersonsNestedInput
}

export type PersonUncheckedUpdateWithoutCompositionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  creatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUncheckedUpdateManyWithoutComposerNestedInput
  contributions?: Prisma.ContributionUncheckedUpdateManyWithoutPersonNestedInput
}

export type PersonCreateWithoutContributionsInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionCreateNestedManyWithoutComposerInput
  compositions?: Prisma.PieceCreateNestedManyWithoutComposerInput
  creator?: Prisma.UserCreateNestedOneWithoutPersonsInput
}

export type PersonUncheckedCreateWithoutContributionsInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  creatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionUncheckedCreateNestedManyWithoutComposerInput
  compositions?: Prisma.PieceUncheckedCreateNestedManyWithoutComposerInput
}

export type PersonCreateOrConnectWithoutContributionsInput = {
  where: Prisma.PersonWhereUniqueInput
  create: Prisma.XOR<Prisma.PersonCreateWithoutContributionsInput, Prisma.PersonUncheckedCreateWithoutContributionsInput>
}

export type PersonUpsertWithoutContributionsInput = {
  update: Prisma.XOR<Prisma.PersonUpdateWithoutContributionsInput, Prisma.PersonUncheckedUpdateWithoutContributionsInput>
  create: Prisma.XOR<Prisma.PersonCreateWithoutContributionsInput, Prisma.PersonUncheckedCreateWithoutContributionsInput>
  where?: Prisma.PersonWhereInput
}

export type PersonUpdateToOneWithWhereWithoutContributionsInput = {
  where?: Prisma.PersonWhereInput
  data: Prisma.XOR<Prisma.PersonUpdateWithoutContributionsInput, Prisma.PersonUncheckedUpdateWithoutContributionsInput>
}

export type PersonUpdateWithoutContributionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUpdateManyWithoutComposerNestedInput
  compositions?: Prisma.PieceUpdateManyWithoutComposerNestedInput
  creator?: Prisma.UserUpdateOneWithoutPersonsNestedInput
}

export type PersonUncheckedUpdateWithoutContributionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  creatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUncheckedUpdateManyWithoutComposerNestedInput
  compositions?: Prisma.PieceUncheckedUpdateManyWithoutComposerNestedInput
}

export type PersonCreateWithoutCreatorInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionCreateNestedManyWithoutComposerInput
  compositions?: Prisma.PieceCreateNestedManyWithoutComposerInput
  contributions?: Prisma.ContributionCreateNestedManyWithoutPersonInput
}

export type PersonUncheckedCreateWithoutCreatorInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionUncheckedCreateNestedManyWithoutComposerInput
  compositions?: Prisma.PieceUncheckedCreateNestedManyWithoutComposerInput
  contributions?: Prisma.ContributionUncheckedCreateNestedManyWithoutPersonInput
}

export type PersonCreateOrConnectWithoutCreatorInput = {
  where: Prisma.PersonWhereUniqueInput
  create: Prisma.XOR<Prisma.PersonCreateWithoutCreatorInput, Prisma.PersonUncheckedCreateWithoutCreatorInput>
}

export type PersonCreateManyCreatorInputEnvelope = {
  data: Prisma.PersonCreateManyCreatorInput | Prisma.PersonCreateManyCreatorInput[]
  skipDuplicates?: boolean
}

export type PersonUpsertWithWhereUniqueWithoutCreatorInput = {
  where: Prisma.PersonWhereUniqueInput
  update: Prisma.XOR<Prisma.PersonUpdateWithoutCreatorInput, Prisma.PersonUncheckedUpdateWithoutCreatorInput>
  create: Prisma.XOR<Prisma.PersonCreateWithoutCreatorInput, Prisma.PersonUncheckedCreateWithoutCreatorInput>
}

export type PersonUpdateWithWhereUniqueWithoutCreatorInput = {
  where: Prisma.PersonWhereUniqueInput
  data: Prisma.XOR<Prisma.PersonUpdateWithoutCreatorInput, Prisma.PersonUncheckedUpdateWithoutCreatorInput>
}

export type PersonUpdateManyWithWhereWithoutCreatorInput = {
  where: Prisma.PersonScalarWhereInput
  data: Prisma.XOR<Prisma.PersonUpdateManyMutationInput, Prisma.PersonUncheckedUpdateManyWithoutCreatorInput>
}

export type PersonScalarWhereInput = {
  AND?: Prisma.PersonScalarWhereInput | Prisma.PersonScalarWhereInput[]
  OR?: Prisma.PersonScalarWhereInput[]
  NOT?: Prisma.PersonScalarWhereInput | Prisma.PersonScalarWhereInput[]
  id?: Prisma.UuidFilter<"Person"> | string
  firstName?: Prisma.StringFilter<"Person"> | string
  lastName?: Prisma.StringFilter<"Person"> | string
  birthYear?: Prisma.IntFilter<"Person"> | number
  deathYear?: Prisma.IntNullableFilter<"Person"> | number | null
  creatorId?: Prisma.UuidNullableFilter<"Person"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Person"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Person"> | Date | string
}

export type PersonCreateManyCreatorInput = {
  id?: string
  firstName: string
  lastName: string
  birthYear: number
  deathYear?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PersonUpdateWithoutCreatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUpdateManyWithoutComposerNestedInput
  compositions?: Prisma.PieceUpdateManyWithoutComposerNestedInput
  contributions?: Prisma.ContributionUpdateManyWithoutPersonNestedInput
}

export type PersonUncheckedUpdateWithoutCreatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUncheckedUpdateManyWithoutComposerNestedInput
  compositions?: Prisma.PieceUncheckedUpdateManyWithoutComposerNestedInput
  contributions?: Prisma.ContributionUncheckedUpdateManyWithoutPersonNestedInput
}

export type PersonUncheckedUpdateManyWithoutCreatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  birthYear?: Prisma.IntFieldUpdateOperationsInput | number
  deathYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PersonCountOutputType
 */

export type PersonCountOutputType = {
  collections: number
  compositions: number
  contributions: number
}

export type PersonCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collections?: boolean | PersonCountOutputTypeCountCollectionsArgs
  compositions?: boolean | PersonCountOutputTypeCountCompositionsArgs
  contributions?: boolean | PersonCountOutputTypeCountContributionsArgs
}

/**
 * PersonCountOutputType without action
 */
export type PersonCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonCountOutputType
   */
  select?: Prisma.PersonCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PersonCountOutputType without action
 */
export type PersonCountOutputTypeCountCollectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CollectionWhereInput
}

/**
 * PersonCountOutputType without action
 */
export type PersonCountOutputTypeCountCompositionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PieceWhereInput
}

/**
 * PersonCountOutputType without action
 */
export type PersonCountOutputTypeCountContributionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContributionWhereInput
}


export type PersonSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  birthYear?: boolean
  deathYear?: boolean
  creatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  collections?: boolean | Prisma.Person$collectionsArgs<ExtArgs>
  compositions?: boolean | Prisma.Person$compositionsArgs<ExtArgs>
  contributions?: boolean | Prisma.Person$contributionsArgs<ExtArgs>
  creator?: boolean | Prisma.Person$creatorArgs<ExtArgs>
  _count?: boolean | Prisma.PersonCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["person"]>

export type PersonSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  birthYear?: boolean
  deathYear?: boolean
  creatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  creator?: boolean | Prisma.Person$creatorArgs<ExtArgs>
}, ExtArgs["result"]["person"]>

export type PersonSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  birthYear?: boolean
  deathYear?: boolean
  creatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  creator?: boolean | Prisma.Person$creatorArgs<ExtArgs>
}, ExtArgs["result"]["person"]>

export type PersonSelectScalar = {
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  birthYear?: boolean
  deathYear?: boolean
  creatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PersonOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "firstName" | "lastName" | "birthYear" | "deathYear" | "creatorId" | "createdAt" | "updatedAt", ExtArgs["result"]["person"]>
export type PersonInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collections?: boolean | Prisma.Person$collectionsArgs<ExtArgs>
  compositions?: boolean | Prisma.Person$compositionsArgs<ExtArgs>
  contributions?: boolean | Prisma.Person$contributionsArgs<ExtArgs>
  creator?: boolean | Prisma.Person$creatorArgs<ExtArgs>
  _count?: boolean | Prisma.PersonCountOutputTypeDefaultArgs<ExtArgs>
}
export type PersonIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  creator?: boolean | Prisma.Person$creatorArgs<ExtArgs>
}
export type PersonIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  creator?: boolean | Prisma.Person$creatorArgs<ExtArgs>
}

export type $PersonPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Person"
  objects: {
    collections: Prisma.$CollectionPayload<ExtArgs>[]
    compositions: Prisma.$PiecePayload<ExtArgs>[]
    contributions: Prisma.$ContributionPayload<ExtArgs>[]
    creator: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    firstName: string
    lastName: string
    birthYear: number
    deathYear: number | null
    creatorId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["person"]>
  composites: {}
}

export type PersonGetPayload<S extends boolean | null | undefined | PersonDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PersonPayload, S>

export type PersonCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PersonFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PersonCountAggregateInputType | true
  }

export interface PersonDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Person'], meta: { name: 'Person' } }
  /**
   * Find zero or one Person that matches the filter.
   * @param {PersonFindUniqueArgs} args - Arguments to find a Person
   * @example
   * // Get one Person
   * const person = await prisma.person.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PersonFindUniqueArgs>(args: Prisma.SelectSubset<T, PersonFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Person that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PersonFindUniqueOrThrowArgs} args - Arguments to find a Person
   * @example
   * // Get one Person
   * const person = await prisma.person.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PersonFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PersonFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Person that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonFindFirstArgs} args - Arguments to find a Person
   * @example
   * // Get one Person
   * const person = await prisma.person.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PersonFindFirstArgs>(args?: Prisma.SelectSubset<T, PersonFindFirstArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Person that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonFindFirstOrThrowArgs} args - Arguments to find a Person
   * @example
   * // Get one Person
   * const person = await prisma.person.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PersonFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PersonFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more People that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all People
   * const people = await prisma.person.findMany()
   * 
   * // Get first 10 People
   * const people = await prisma.person.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const personWithIdOnly = await prisma.person.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PersonFindManyArgs>(args?: Prisma.SelectSubset<T, PersonFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Person.
   * @param {PersonCreateArgs} args - Arguments to create a Person.
   * @example
   * // Create one Person
   * const Person = await prisma.person.create({
   *   data: {
   *     // ... data to create a Person
   *   }
   * })
   * 
   */
  create<T extends PersonCreateArgs>(args: Prisma.SelectSubset<T, PersonCreateArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many People.
   * @param {PersonCreateManyArgs} args - Arguments to create many People.
   * @example
   * // Create many People
   * const person = await prisma.person.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PersonCreateManyArgs>(args?: Prisma.SelectSubset<T, PersonCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many People and returns the data saved in the database.
   * @param {PersonCreateManyAndReturnArgs} args - Arguments to create many People.
   * @example
   * // Create many People
   * const person = await prisma.person.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many People and only return the `id`
   * const personWithIdOnly = await prisma.person.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PersonCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PersonCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Person.
   * @param {PersonDeleteArgs} args - Arguments to delete one Person.
   * @example
   * // Delete one Person
   * const Person = await prisma.person.delete({
   *   where: {
   *     // ... filter to delete one Person
   *   }
   * })
   * 
   */
  delete<T extends PersonDeleteArgs>(args: Prisma.SelectSubset<T, PersonDeleteArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Person.
   * @param {PersonUpdateArgs} args - Arguments to update one Person.
   * @example
   * // Update one Person
   * const person = await prisma.person.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PersonUpdateArgs>(args: Prisma.SelectSubset<T, PersonUpdateArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more People.
   * @param {PersonDeleteManyArgs} args - Arguments to filter People to delete.
   * @example
   * // Delete a few People
   * const { count } = await prisma.person.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PersonDeleteManyArgs>(args?: Prisma.SelectSubset<T, PersonDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more People.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many People
   * const person = await prisma.person.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PersonUpdateManyArgs>(args: Prisma.SelectSubset<T, PersonUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more People and returns the data updated in the database.
   * @param {PersonUpdateManyAndReturnArgs} args - Arguments to update many People.
   * @example
   * // Update many People
   * const person = await prisma.person.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more People and only return the `id`
   * const personWithIdOnly = await prisma.person.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PersonUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PersonUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Person.
   * @param {PersonUpsertArgs} args - Arguments to update or create a Person.
   * @example
   * // Update or create a Person
   * const person = await prisma.person.upsert({
   *   create: {
   *     // ... data to create a Person
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Person we want to update
   *   }
   * })
   */
  upsert<T extends PersonUpsertArgs>(args: Prisma.SelectSubset<T, PersonUpsertArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of People.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonCountArgs} args - Arguments to filter People to count.
   * @example
   * // Count the number of People
   * const count = await prisma.person.count({
   *   where: {
   *     // ... the filter for the People we want to count
   *   }
   * })
  **/
  count<T extends PersonCountArgs>(
    args?: Prisma.Subset<T, PersonCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PersonCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Person.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PersonAggregateArgs>(args: Prisma.Subset<T, PersonAggregateArgs>): Prisma.PrismaPromise<GetPersonAggregateType<T>>

  /**
   * Group by Person.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PersonGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PersonGroupByArgs['orderBy'] }
      : { orderBy?: PersonGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PersonGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPersonGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Person model
 */
readonly fields: PersonFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Person.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PersonClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  collections<T extends Prisma.Person$collectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Person$collectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CollectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  compositions<T extends Prisma.Person$compositionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Person$compositionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PiecePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  contributions<T extends Prisma.Person$contributionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Person$contributionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContributionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  creator<T extends Prisma.Person$creatorArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Person$creatorArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Person model
 */
export interface PersonFieldRefs {
  readonly id: Prisma.FieldRef<"Person", 'String'>
  readonly firstName: Prisma.FieldRef<"Person", 'String'>
  readonly lastName: Prisma.FieldRef<"Person", 'String'>
  readonly birthYear: Prisma.FieldRef<"Person", 'Int'>
  readonly deathYear: Prisma.FieldRef<"Person", 'Int'>
  readonly creatorId: Prisma.FieldRef<"Person", 'String'>
  readonly createdAt: Prisma.FieldRef<"Person", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Person", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Person findUnique
 */
export type PersonFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter, which Person to fetch.
   */
  where: Prisma.PersonWhereUniqueInput
}

/**
 * Person findUniqueOrThrow
 */
export type PersonFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter, which Person to fetch.
   */
  where: Prisma.PersonWhereUniqueInput
}

/**
 * Person findFirst
 */
export type PersonFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter, which Person to fetch.
   */
  where?: Prisma.PersonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PersonOrderByWithRelationInput | Prisma.PersonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for People.
   */
  cursor?: Prisma.PersonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of People.
   */
  distinct?: Prisma.PersonScalarFieldEnum | Prisma.PersonScalarFieldEnum[]
}

/**
 * Person findFirstOrThrow
 */
export type PersonFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter, which Person to fetch.
   */
  where?: Prisma.PersonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PersonOrderByWithRelationInput | Prisma.PersonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for People.
   */
  cursor?: Prisma.PersonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of People.
   */
  distinct?: Prisma.PersonScalarFieldEnum | Prisma.PersonScalarFieldEnum[]
}

/**
 * Person findMany
 */
export type PersonFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter, which People to fetch.
   */
  where?: Prisma.PersonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PersonOrderByWithRelationInput | Prisma.PersonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing People.
   */
  cursor?: Prisma.PersonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  distinct?: Prisma.PersonScalarFieldEnum | Prisma.PersonScalarFieldEnum[]
}

/**
 * Person create
 */
export type PersonCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * The data needed to create a Person.
   */
  data: Prisma.XOR<Prisma.PersonCreateInput, Prisma.PersonUncheckedCreateInput>
}

/**
 * Person createMany
 */
export type PersonCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many People.
   */
  data: Prisma.PersonCreateManyInput | Prisma.PersonCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Person createManyAndReturn
 */
export type PersonCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * The data used to create many People.
   */
  data: Prisma.PersonCreateManyInput | Prisma.PersonCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Person update
 */
export type PersonUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * The data needed to update a Person.
   */
  data: Prisma.XOR<Prisma.PersonUpdateInput, Prisma.PersonUncheckedUpdateInput>
  /**
   * Choose, which Person to update.
   */
  where: Prisma.PersonWhereUniqueInput
}

/**
 * Person updateMany
 */
export type PersonUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update People.
   */
  data: Prisma.XOR<Prisma.PersonUpdateManyMutationInput, Prisma.PersonUncheckedUpdateManyInput>
  /**
   * Filter which People to update
   */
  where?: Prisma.PersonWhereInput
  /**
   * Limit how many People to update.
   */
  limit?: number
}

/**
 * Person updateManyAndReturn
 */
export type PersonUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * The data used to update People.
   */
  data: Prisma.XOR<Prisma.PersonUpdateManyMutationInput, Prisma.PersonUncheckedUpdateManyInput>
  /**
   * Filter which People to update
   */
  where?: Prisma.PersonWhereInput
  /**
   * Limit how many People to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Person upsert
 */
export type PersonUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * The filter to search for the Person to update in case it exists.
   */
  where: Prisma.PersonWhereUniqueInput
  /**
   * In case the Person found by the `where` argument doesn't exist, create a new Person with this data.
   */
  create: Prisma.XOR<Prisma.PersonCreateInput, Prisma.PersonUncheckedCreateInput>
  /**
   * In case the Person was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PersonUpdateInput, Prisma.PersonUncheckedUpdateInput>
}

/**
 * Person delete
 */
export type PersonDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter which Person to delete.
   */
  where: Prisma.PersonWhereUniqueInput
}

/**
 * Person deleteMany
 */
export type PersonDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which People to delete
   */
  where?: Prisma.PersonWhereInput
  /**
   * Limit how many People to delete.
   */
  limit?: number
}

/**
 * Person.collections
 */
export type Person$collectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Collection
   */
  select?: Prisma.CollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Collection
   */
  omit?: Prisma.CollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CollectionInclude<ExtArgs> | null
  where?: Prisma.CollectionWhereInput
  orderBy?: Prisma.CollectionOrderByWithRelationInput | Prisma.CollectionOrderByWithRelationInput[]
  cursor?: Prisma.CollectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CollectionScalarFieldEnum | Prisma.CollectionScalarFieldEnum[]
}

/**
 * Person.compositions
 */
export type Person$compositionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Piece
   */
  select?: Prisma.PieceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Piece
   */
  omit?: Prisma.PieceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PieceInclude<ExtArgs> | null
  where?: Prisma.PieceWhereInput
  orderBy?: Prisma.PieceOrderByWithRelationInput | Prisma.PieceOrderByWithRelationInput[]
  cursor?: Prisma.PieceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PieceScalarFieldEnum | Prisma.PieceScalarFieldEnum[]
}

/**
 * Person.contributions
 */
export type Person$contributionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contribution
   */
  select?: Prisma.ContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contribution
   */
  omit?: Prisma.ContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributionInclude<ExtArgs> | null
  where?: Prisma.ContributionWhereInput
  orderBy?: Prisma.ContributionOrderByWithRelationInput | Prisma.ContributionOrderByWithRelationInput[]
  cursor?: Prisma.ContributionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ContributionScalarFieldEnum | Prisma.ContributionScalarFieldEnum[]
}

/**
 * Person.creator
 */
export type Person$creatorArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Person without action
 */
export type PersonDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
}
