
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReviewedEntity` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ReviewedEntity
 * 
 */
export type ReviewedEntityModel = runtime.Types.Result.DefaultSelection<Prisma.$ReviewedEntityPayload>

export type AggregateReviewedEntity = {
  _count: ReviewedEntityCountAggregateOutputType | null
  _min: ReviewedEntityMinAggregateOutputType | null
  _max: ReviewedEntityMaxAggregateOutputType | null
}

export type ReviewedEntityMinAggregateOutputType = {
  id: string | null
  entityType: $Enums.REVIEWED_ENTITY_TYPE | null
  entityId: string | null
  reviewedAt: Date | null
  reviewedById: string | null
  reviewId: string | null
}

export type ReviewedEntityMaxAggregateOutputType = {
  id: string | null
  entityType: $Enums.REVIEWED_ENTITY_TYPE | null
  entityId: string | null
  reviewedAt: Date | null
  reviewedById: string | null
  reviewId: string | null
}

export type ReviewedEntityCountAggregateOutputType = {
  id: number
  entityType: number
  entityId: number
  reviewedAt: number
  reviewedById: number
  reviewId: number
  _all: number
}


export type ReviewedEntityMinAggregateInputType = {
  id?: true
  entityType?: true
  entityId?: true
  reviewedAt?: true
  reviewedById?: true
  reviewId?: true
}

export type ReviewedEntityMaxAggregateInputType = {
  id?: true
  entityType?: true
  entityId?: true
  reviewedAt?: true
  reviewedById?: true
  reviewId?: true
}

export type ReviewedEntityCountAggregateInputType = {
  id?: true
  entityType?: true
  entityId?: true
  reviewedAt?: true
  reviewedById?: true
  reviewId?: true
  _all?: true
}

export type ReviewedEntityAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReviewedEntity to aggregate.
   */
  where?: Prisma.ReviewedEntityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReviewedEntities to fetch.
   */
  orderBy?: Prisma.ReviewedEntityOrderByWithRelationInput | Prisma.ReviewedEntityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReviewedEntityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReviewedEntities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReviewedEntities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReviewedEntities
  **/
  _count?: true | ReviewedEntityCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReviewedEntityMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReviewedEntityMaxAggregateInputType
}

export type GetReviewedEntityAggregateType<T extends ReviewedEntityAggregateArgs> = {
      [P in keyof T & keyof AggregateReviewedEntity]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReviewedEntity[P]>
    : Prisma.GetScalarType<T[P], AggregateReviewedEntity[P]>
}




export type ReviewedEntityGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReviewedEntityWhereInput
  orderBy?: Prisma.ReviewedEntityOrderByWithAggregationInput | Prisma.ReviewedEntityOrderByWithAggregationInput[]
  by: Prisma.ReviewedEntityScalarFieldEnum[] | Prisma.ReviewedEntityScalarFieldEnum
  having?: Prisma.ReviewedEntityScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReviewedEntityCountAggregateInputType | true
  _min?: ReviewedEntityMinAggregateInputType
  _max?: ReviewedEntityMaxAggregateInputType
}

export type ReviewedEntityGroupByOutputType = {
  id: string
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
  reviewedAt: Date
  reviewedById: string
  reviewId: string
  _count: ReviewedEntityCountAggregateOutputType | null
  _min: ReviewedEntityMinAggregateOutputType | null
  _max: ReviewedEntityMaxAggregateOutputType | null
}

type GetReviewedEntityGroupByPayload<T extends ReviewedEntityGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReviewedEntityGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReviewedEntityGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReviewedEntityGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReviewedEntityGroupByOutputType[P]>
      }
    >
  >



export type ReviewedEntityWhereInput = {
  AND?: Prisma.ReviewedEntityWhereInput | Prisma.ReviewedEntityWhereInput[]
  OR?: Prisma.ReviewedEntityWhereInput[]
  NOT?: Prisma.ReviewedEntityWhereInput | Prisma.ReviewedEntityWhereInput[]
  id?: Prisma.UuidFilter<"ReviewedEntity"> | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFilter<"ReviewedEntity"> | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.UuidFilter<"ReviewedEntity"> | string
  reviewedAt?: Prisma.DateTimeFilter<"ReviewedEntity"> | Date | string
  reviewedById?: Prisma.UuidFilter<"ReviewedEntity"> | string
  reviewId?: Prisma.UuidFilter<"ReviewedEntity"> | string
  reviewer?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  review?: Prisma.XOR<Prisma.ReviewScalarRelationFilter, Prisma.ReviewWhereInput>
}

export type ReviewedEntityOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  reviewedById?: Prisma.SortOrder
  reviewId?: Prisma.SortOrder
  reviewer?: Prisma.UserOrderByWithRelationInput
  review?: Prisma.ReviewOrderByWithRelationInput
}

export type ReviewedEntityWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  entityType_entityId?: Prisma.ReviewedEntityEntityTypeEntityIdCompoundUniqueInput
  AND?: Prisma.ReviewedEntityWhereInput | Prisma.ReviewedEntityWhereInput[]
  OR?: Prisma.ReviewedEntityWhereInput[]
  NOT?: Prisma.ReviewedEntityWhereInput | Prisma.ReviewedEntityWhereInput[]
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFilter<"ReviewedEntity"> | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.UuidFilter<"ReviewedEntity"> | string
  reviewedAt?: Prisma.DateTimeFilter<"ReviewedEntity"> | Date | string
  reviewedById?: Prisma.UuidFilter<"ReviewedEntity"> | string
  reviewId?: Prisma.UuidFilter<"ReviewedEntity"> | string
  reviewer?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  review?: Prisma.XOR<Prisma.ReviewScalarRelationFilter, Prisma.ReviewWhereInput>
}, "id" | "entityType_entityId">

export type ReviewedEntityOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  reviewedById?: Prisma.SortOrder
  reviewId?: Prisma.SortOrder
  _count?: Prisma.ReviewedEntityCountOrderByAggregateInput
  _max?: Prisma.ReviewedEntityMaxOrderByAggregateInput
  _min?: Prisma.ReviewedEntityMinOrderByAggregateInput
}

export type ReviewedEntityScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReviewedEntityScalarWhereWithAggregatesInput | Prisma.ReviewedEntityScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReviewedEntityScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReviewedEntityScalarWhereWithAggregatesInput | Prisma.ReviewedEntityScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"ReviewedEntity"> | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEWithAggregatesFilter<"ReviewedEntity"> | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.UuidWithAggregatesFilter<"ReviewedEntity"> | string
  reviewedAt?: Prisma.DateTimeWithAggregatesFilter<"ReviewedEntity"> | Date | string
  reviewedById?: Prisma.UuidWithAggregatesFilter<"ReviewedEntity"> | string
  reviewId?: Prisma.UuidWithAggregatesFilter<"ReviewedEntity"> | string
}

export type ReviewedEntityCreateInput = {
  id?: string
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
  reviewedAt?: Date | string
  reviewer: Prisma.UserCreateNestedOneWithoutReviewedEntitiesInput
  review: Prisma.ReviewCreateNestedOneWithoutReviewedEntitiesInput
}

export type ReviewedEntityUncheckedCreateInput = {
  id?: string
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
  reviewedAt?: Date | string
  reviewedById: string
  reviewId: string
}

export type ReviewedEntityUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  reviewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewer?: Prisma.UserUpdateOneRequiredWithoutReviewedEntitiesNestedInput
  review?: Prisma.ReviewUpdateOneRequiredWithoutReviewedEntitiesNestedInput
}

export type ReviewedEntityUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  reviewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedById?: Prisma.StringFieldUpdateOperationsInput | string
  reviewId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ReviewedEntityCreateManyInput = {
  id?: string
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
  reviewedAt?: Date | string
  reviewedById: string
  reviewId: string
}

export type ReviewedEntityUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  reviewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReviewedEntityUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  reviewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedById?: Prisma.StringFieldUpdateOperationsInput | string
  reviewId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ReviewedEntityListRelationFilter = {
  every?: Prisma.ReviewedEntityWhereInput
  some?: Prisma.ReviewedEntityWhereInput
  none?: Prisma.ReviewedEntityWhereInput
}

export type ReviewedEntityOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ReviewedEntityEntityTypeEntityIdCompoundUniqueInput = {
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
}

export type ReviewedEntityCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  reviewedById?: Prisma.SortOrder
  reviewId?: Prisma.SortOrder
}

export type ReviewedEntityMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  reviewedById?: Prisma.SortOrder
  reviewId?: Prisma.SortOrder
}

export type ReviewedEntityMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  reviewedById?: Prisma.SortOrder
  reviewId?: Prisma.SortOrder
}

export type ReviewedEntityCreateNestedManyWithoutReviewerInput = {
  create?: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewerInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewerInput> | Prisma.ReviewedEntityCreateWithoutReviewerInput[] | Prisma.ReviewedEntityUncheckedCreateWithoutReviewerInput[]
  connectOrCreate?: Prisma.ReviewedEntityCreateOrConnectWithoutReviewerInput | Prisma.ReviewedEntityCreateOrConnectWithoutReviewerInput[]
  createMany?: Prisma.ReviewedEntityCreateManyReviewerInputEnvelope
  connect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
}

export type ReviewedEntityUncheckedCreateNestedManyWithoutReviewerInput = {
  create?: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewerInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewerInput> | Prisma.ReviewedEntityCreateWithoutReviewerInput[] | Prisma.ReviewedEntityUncheckedCreateWithoutReviewerInput[]
  connectOrCreate?: Prisma.ReviewedEntityCreateOrConnectWithoutReviewerInput | Prisma.ReviewedEntityCreateOrConnectWithoutReviewerInput[]
  createMany?: Prisma.ReviewedEntityCreateManyReviewerInputEnvelope
  connect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
}

export type ReviewedEntityUpdateManyWithoutReviewerNestedInput = {
  create?: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewerInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewerInput> | Prisma.ReviewedEntityCreateWithoutReviewerInput[] | Prisma.ReviewedEntityUncheckedCreateWithoutReviewerInput[]
  connectOrCreate?: Prisma.ReviewedEntityCreateOrConnectWithoutReviewerInput | Prisma.ReviewedEntityCreateOrConnectWithoutReviewerInput[]
  upsert?: Prisma.ReviewedEntityUpsertWithWhereUniqueWithoutReviewerInput | Prisma.ReviewedEntityUpsertWithWhereUniqueWithoutReviewerInput[]
  createMany?: Prisma.ReviewedEntityCreateManyReviewerInputEnvelope
  set?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  disconnect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  delete?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  connect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  update?: Prisma.ReviewedEntityUpdateWithWhereUniqueWithoutReviewerInput | Prisma.ReviewedEntityUpdateWithWhereUniqueWithoutReviewerInput[]
  updateMany?: Prisma.ReviewedEntityUpdateManyWithWhereWithoutReviewerInput | Prisma.ReviewedEntityUpdateManyWithWhereWithoutReviewerInput[]
  deleteMany?: Prisma.ReviewedEntityScalarWhereInput | Prisma.ReviewedEntityScalarWhereInput[]
}

export type ReviewedEntityUncheckedUpdateManyWithoutReviewerNestedInput = {
  create?: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewerInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewerInput> | Prisma.ReviewedEntityCreateWithoutReviewerInput[] | Prisma.ReviewedEntityUncheckedCreateWithoutReviewerInput[]
  connectOrCreate?: Prisma.ReviewedEntityCreateOrConnectWithoutReviewerInput | Prisma.ReviewedEntityCreateOrConnectWithoutReviewerInput[]
  upsert?: Prisma.ReviewedEntityUpsertWithWhereUniqueWithoutReviewerInput | Prisma.ReviewedEntityUpsertWithWhereUniqueWithoutReviewerInput[]
  createMany?: Prisma.ReviewedEntityCreateManyReviewerInputEnvelope
  set?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  disconnect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  delete?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  connect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  update?: Prisma.ReviewedEntityUpdateWithWhereUniqueWithoutReviewerInput | Prisma.ReviewedEntityUpdateWithWhereUniqueWithoutReviewerInput[]
  updateMany?: Prisma.ReviewedEntityUpdateManyWithWhereWithoutReviewerInput | Prisma.ReviewedEntityUpdateManyWithWhereWithoutReviewerInput[]
  deleteMany?: Prisma.ReviewedEntityScalarWhereInput | Prisma.ReviewedEntityScalarWhereInput[]
}

export type ReviewedEntityCreateNestedManyWithoutReviewInput = {
  create?: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewInput> | Prisma.ReviewedEntityCreateWithoutReviewInput[] | Prisma.ReviewedEntityUncheckedCreateWithoutReviewInput[]
  connectOrCreate?: Prisma.ReviewedEntityCreateOrConnectWithoutReviewInput | Prisma.ReviewedEntityCreateOrConnectWithoutReviewInput[]
  createMany?: Prisma.ReviewedEntityCreateManyReviewInputEnvelope
  connect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
}

export type ReviewedEntityUncheckedCreateNestedManyWithoutReviewInput = {
  create?: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewInput> | Prisma.ReviewedEntityCreateWithoutReviewInput[] | Prisma.ReviewedEntityUncheckedCreateWithoutReviewInput[]
  connectOrCreate?: Prisma.ReviewedEntityCreateOrConnectWithoutReviewInput | Prisma.ReviewedEntityCreateOrConnectWithoutReviewInput[]
  createMany?: Prisma.ReviewedEntityCreateManyReviewInputEnvelope
  connect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
}

export type ReviewedEntityUpdateManyWithoutReviewNestedInput = {
  create?: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewInput> | Prisma.ReviewedEntityCreateWithoutReviewInput[] | Prisma.ReviewedEntityUncheckedCreateWithoutReviewInput[]
  connectOrCreate?: Prisma.ReviewedEntityCreateOrConnectWithoutReviewInput | Prisma.ReviewedEntityCreateOrConnectWithoutReviewInput[]
  upsert?: Prisma.ReviewedEntityUpsertWithWhereUniqueWithoutReviewInput | Prisma.ReviewedEntityUpsertWithWhereUniqueWithoutReviewInput[]
  createMany?: Prisma.ReviewedEntityCreateManyReviewInputEnvelope
  set?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  disconnect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  delete?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  connect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  update?: Prisma.ReviewedEntityUpdateWithWhereUniqueWithoutReviewInput | Prisma.ReviewedEntityUpdateWithWhereUniqueWithoutReviewInput[]
  updateMany?: Prisma.ReviewedEntityUpdateManyWithWhereWithoutReviewInput | Prisma.ReviewedEntityUpdateManyWithWhereWithoutReviewInput[]
  deleteMany?: Prisma.ReviewedEntityScalarWhereInput | Prisma.ReviewedEntityScalarWhereInput[]
}

export type ReviewedEntityUncheckedUpdateManyWithoutReviewNestedInput = {
  create?: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewInput> | Prisma.ReviewedEntityCreateWithoutReviewInput[] | Prisma.ReviewedEntityUncheckedCreateWithoutReviewInput[]
  connectOrCreate?: Prisma.ReviewedEntityCreateOrConnectWithoutReviewInput | Prisma.ReviewedEntityCreateOrConnectWithoutReviewInput[]
  upsert?: Prisma.ReviewedEntityUpsertWithWhereUniqueWithoutReviewInput | Prisma.ReviewedEntityUpsertWithWhereUniqueWithoutReviewInput[]
  createMany?: Prisma.ReviewedEntityCreateManyReviewInputEnvelope
  set?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  disconnect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  delete?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  connect?: Prisma.ReviewedEntityWhereUniqueInput | Prisma.ReviewedEntityWhereUniqueInput[]
  update?: Prisma.ReviewedEntityUpdateWithWhereUniqueWithoutReviewInput | Prisma.ReviewedEntityUpdateWithWhereUniqueWithoutReviewInput[]
  updateMany?: Prisma.ReviewedEntityUpdateManyWithWhereWithoutReviewInput | Prisma.ReviewedEntityUpdateManyWithWhereWithoutReviewInput[]
  deleteMany?: Prisma.ReviewedEntityScalarWhereInput | Prisma.ReviewedEntityScalarWhereInput[]
}

export type EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput = {
  set?: $Enums.REVIEWED_ENTITY_TYPE
}

export type ReviewedEntityCreateWithoutReviewerInput = {
  id?: string
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
  reviewedAt?: Date | string
  review: Prisma.ReviewCreateNestedOneWithoutReviewedEntitiesInput
}

export type ReviewedEntityUncheckedCreateWithoutReviewerInput = {
  id?: string
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
  reviewedAt?: Date | string
  reviewId: string
}

export type ReviewedEntityCreateOrConnectWithoutReviewerInput = {
  where: Prisma.ReviewedEntityWhereUniqueInput
  create: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewerInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewerInput>
}

export type ReviewedEntityCreateManyReviewerInputEnvelope = {
  data: Prisma.ReviewedEntityCreateManyReviewerInput | Prisma.ReviewedEntityCreateManyReviewerInput[]
  skipDuplicates?: boolean
}

export type ReviewedEntityUpsertWithWhereUniqueWithoutReviewerInput = {
  where: Prisma.ReviewedEntityWhereUniqueInput
  update: Prisma.XOR<Prisma.ReviewedEntityUpdateWithoutReviewerInput, Prisma.ReviewedEntityUncheckedUpdateWithoutReviewerInput>
  create: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewerInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewerInput>
}

export type ReviewedEntityUpdateWithWhereUniqueWithoutReviewerInput = {
  where: Prisma.ReviewedEntityWhereUniqueInput
  data: Prisma.XOR<Prisma.ReviewedEntityUpdateWithoutReviewerInput, Prisma.ReviewedEntityUncheckedUpdateWithoutReviewerInput>
}

export type ReviewedEntityUpdateManyWithWhereWithoutReviewerInput = {
  where: Prisma.ReviewedEntityScalarWhereInput
  data: Prisma.XOR<Prisma.ReviewedEntityUpdateManyMutationInput, Prisma.ReviewedEntityUncheckedUpdateManyWithoutReviewerInput>
}

export type ReviewedEntityScalarWhereInput = {
  AND?: Prisma.ReviewedEntityScalarWhereInput | Prisma.ReviewedEntityScalarWhereInput[]
  OR?: Prisma.ReviewedEntityScalarWhereInput[]
  NOT?: Prisma.ReviewedEntityScalarWhereInput | Prisma.ReviewedEntityScalarWhereInput[]
  id?: Prisma.UuidFilter<"ReviewedEntity"> | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFilter<"ReviewedEntity"> | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.UuidFilter<"ReviewedEntity"> | string
  reviewedAt?: Prisma.DateTimeFilter<"ReviewedEntity"> | Date | string
  reviewedById?: Prisma.UuidFilter<"ReviewedEntity"> | string
  reviewId?: Prisma.UuidFilter<"ReviewedEntity"> | string
}

export type ReviewedEntityCreateWithoutReviewInput = {
  id?: string
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
  reviewedAt?: Date | string
  reviewer: Prisma.UserCreateNestedOneWithoutReviewedEntitiesInput
}

export type ReviewedEntityUncheckedCreateWithoutReviewInput = {
  id?: string
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
  reviewedAt?: Date | string
  reviewedById: string
}

export type ReviewedEntityCreateOrConnectWithoutReviewInput = {
  where: Prisma.ReviewedEntityWhereUniqueInput
  create: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewInput>
}

export type ReviewedEntityCreateManyReviewInputEnvelope = {
  data: Prisma.ReviewedEntityCreateManyReviewInput | Prisma.ReviewedEntityCreateManyReviewInput[]
  skipDuplicates?: boolean
}

export type ReviewedEntityUpsertWithWhereUniqueWithoutReviewInput = {
  where: Prisma.ReviewedEntityWhereUniqueInput
  update: Prisma.XOR<Prisma.ReviewedEntityUpdateWithoutReviewInput, Prisma.ReviewedEntityUncheckedUpdateWithoutReviewInput>
  create: Prisma.XOR<Prisma.ReviewedEntityCreateWithoutReviewInput, Prisma.ReviewedEntityUncheckedCreateWithoutReviewInput>
}

export type ReviewedEntityUpdateWithWhereUniqueWithoutReviewInput = {
  where: Prisma.ReviewedEntityWhereUniqueInput
  data: Prisma.XOR<Prisma.ReviewedEntityUpdateWithoutReviewInput, Prisma.ReviewedEntityUncheckedUpdateWithoutReviewInput>
}

export type ReviewedEntityUpdateManyWithWhereWithoutReviewInput = {
  where: Prisma.ReviewedEntityScalarWhereInput
  data: Prisma.XOR<Prisma.ReviewedEntityUpdateManyMutationInput, Prisma.ReviewedEntityUncheckedUpdateManyWithoutReviewInput>
}

export type ReviewedEntityCreateManyReviewerInput = {
  id?: string
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
  reviewedAt?: Date | string
  reviewId: string
}

export type ReviewedEntityUpdateWithoutReviewerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  reviewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  review?: Prisma.ReviewUpdateOneRequiredWithoutReviewedEntitiesNestedInput
}

export type ReviewedEntityUncheckedUpdateWithoutReviewerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  reviewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ReviewedEntityUncheckedUpdateManyWithoutReviewerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  reviewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ReviewedEntityCreateManyReviewInput = {
  id?: string
  entityType: $Enums.REVIEWED_ENTITY_TYPE
  entityId: string
  reviewedAt?: Date | string
  reviewedById: string
}

export type ReviewedEntityUpdateWithoutReviewInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  reviewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewer?: Prisma.UserUpdateOneRequiredWithoutReviewedEntitiesNestedInput
}

export type ReviewedEntityUncheckedUpdateWithoutReviewInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  reviewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ReviewedEntityUncheckedUpdateManyWithoutReviewInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.EnumREVIEWED_ENTITY_TYPEFieldUpdateOperationsInput | $Enums.REVIEWED_ENTITY_TYPE
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  reviewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reviewedById?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ReviewedEntitySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  entityType?: boolean
  entityId?: boolean
  reviewedAt?: boolean
  reviewedById?: boolean
  reviewId?: boolean
  reviewer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  review?: boolean | Prisma.ReviewDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reviewedEntity"]>

export type ReviewedEntitySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  entityType?: boolean
  entityId?: boolean
  reviewedAt?: boolean
  reviewedById?: boolean
  reviewId?: boolean
  reviewer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  review?: boolean | Prisma.ReviewDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reviewedEntity"]>

export type ReviewedEntitySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  entityType?: boolean
  entityId?: boolean
  reviewedAt?: boolean
  reviewedById?: boolean
  reviewId?: boolean
  reviewer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  review?: boolean | Prisma.ReviewDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reviewedEntity"]>

export type ReviewedEntitySelectScalar = {
  id?: boolean
  entityType?: boolean
  entityId?: boolean
  reviewedAt?: boolean
  reviewedById?: boolean
  reviewId?: boolean
}

export type ReviewedEntityOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "entityType" | "entityId" | "reviewedAt" | "reviewedById" | "reviewId", ExtArgs["result"]["reviewedEntity"]>
export type ReviewedEntityInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reviewer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  review?: boolean | Prisma.ReviewDefaultArgs<ExtArgs>
}
export type ReviewedEntityIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reviewer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  review?: boolean | Prisma.ReviewDefaultArgs<ExtArgs>
}
export type ReviewedEntityIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reviewer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  review?: boolean | Prisma.ReviewDefaultArgs<ExtArgs>
}

export type $ReviewedEntityPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReviewedEntity"
  objects: {
    reviewer: Prisma.$UserPayload<ExtArgs>
    review: Prisma.$ReviewPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    entityType: $Enums.REVIEWED_ENTITY_TYPE
    entityId: string
    reviewedAt: Date
    reviewedById: string
    reviewId: string
  }, ExtArgs["result"]["reviewedEntity"]>
  composites: {}
}

export type ReviewedEntityGetPayload<S extends boolean | null | undefined | ReviewedEntityDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload, S>

export type ReviewedEntityCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReviewedEntityFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReviewedEntityCountAggregateInputType | true
  }

export interface ReviewedEntityDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReviewedEntity'], meta: { name: 'ReviewedEntity' } }
  /**
   * Find zero or one ReviewedEntity that matches the filter.
   * @param {ReviewedEntityFindUniqueArgs} args - Arguments to find a ReviewedEntity
   * @example
   * // Get one ReviewedEntity
   * const reviewedEntity = await prisma.reviewedEntity.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReviewedEntityFindUniqueArgs>(args: Prisma.SelectSubset<T, ReviewedEntityFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReviewedEntityClient<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReviewedEntity that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReviewedEntityFindUniqueOrThrowArgs} args - Arguments to find a ReviewedEntity
   * @example
   * // Get one ReviewedEntity
   * const reviewedEntity = await prisma.reviewedEntity.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReviewedEntityFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReviewedEntityFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReviewedEntityClient<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReviewedEntity that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewedEntityFindFirstArgs} args - Arguments to find a ReviewedEntity
   * @example
   * // Get one ReviewedEntity
   * const reviewedEntity = await prisma.reviewedEntity.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReviewedEntityFindFirstArgs>(args?: Prisma.SelectSubset<T, ReviewedEntityFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReviewedEntityClient<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReviewedEntity that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewedEntityFindFirstOrThrowArgs} args - Arguments to find a ReviewedEntity
   * @example
   * // Get one ReviewedEntity
   * const reviewedEntity = await prisma.reviewedEntity.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReviewedEntityFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReviewedEntityFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReviewedEntityClient<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReviewedEntities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewedEntityFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReviewedEntities
   * const reviewedEntities = await prisma.reviewedEntity.findMany()
   * 
   * // Get first 10 ReviewedEntities
   * const reviewedEntities = await prisma.reviewedEntity.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reviewedEntityWithIdOnly = await prisma.reviewedEntity.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReviewedEntityFindManyArgs>(args?: Prisma.SelectSubset<T, ReviewedEntityFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReviewedEntity.
   * @param {ReviewedEntityCreateArgs} args - Arguments to create a ReviewedEntity.
   * @example
   * // Create one ReviewedEntity
   * const ReviewedEntity = await prisma.reviewedEntity.create({
   *   data: {
   *     // ... data to create a ReviewedEntity
   *   }
   * })
   * 
   */
  create<T extends ReviewedEntityCreateArgs>(args: Prisma.SelectSubset<T, ReviewedEntityCreateArgs<ExtArgs>>): Prisma.Prisma__ReviewedEntityClient<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReviewedEntities.
   * @param {ReviewedEntityCreateManyArgs} args - Arguments to create many ReviewedEntities.
   * @example
   * // Create many ReviewedEntities
   * const reviewedEntity = await prisma.reviewedEntity.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReviewedEntityCreateManyArgs>(args?: Prisma.SelectSubset<T, ReviewedEntityCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ReviewedEntities and returns the data saved in the database.
   * @param {ReviewedEntityCreateManyAndReturnArgs} args - Arguments to create many ReviewedEntities.
   * @example
   * // Create many ReviewedEntities
   * const reviewedEntity = await prisma.reviewedEntity.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ReviewedEntities and only return the `id`
   * const reviewedEntityWithIdOnly = await prisma.reviewedEntity.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReviewedEntityCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReviewedEntityCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ReviewedEntity.
   * @param {ReviewedEntityDeleteArgs} args - Arguments to delete one ReviewedEntity.
   * @example
   * // Delete one ReviewedEntity
   * const ReviewedEntity = await prisma.reviewedEntity.delete({
   *   where: {
   *     // ... filter to delete one ReviewedEntity
   *   }
   * })
   * 
   */
  delete<T extends ReviewedEntityDeleteArgs>(args: Prisma.SelectSubset<T, ReviewedEntityDeleteArgs<ExtArgs>>): Prisma.Prisma__ReviewedEntityClient<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReviewedEntity.
   * @param {ReviewedEntityUpdateArgs} args - Arguments to update one ReviewedEntity.
   * @example
   * // Update one ReviewedEntity
   * const reviewedEntity = await prisma.reviewedEntity.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReviewedEntityUpdateArgs>(args: Prisma.SelectSubset<T, ReviewedEntityUpdateArgs<ExtArgs>>): Prisma.Prisma__ReviewedEntityClient<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReviewedEntities.
   * @param {ReviewedEntityDeleteManyArgs} args - Arguments to filter ReviewedEntities to delete.
   * @example
   * // Delete a few ReviewedEntities
   * const { count } = await prisma.reviewedEntity.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReviewedEntityDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReviewedEntityDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReviewedEntities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewedEntityUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReviewedEntities
   * const reviewedEntity = await prisma.reviewedEntity.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReviewedEntityUpdateManyArgs>(args: Prisma.SelectSubset<T, ReviewedEntityUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReviewedEntities and returns the data updated in the database.
   * @param {ReviewedEntityUpdateManyAndReturnArgs} args - Arguments to update many ReviewedEntities.
   * @example
   * // Update many ReviewedEntities
   * const reviewedEntity = await prisma.reviewedEntity.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ReviewedEntities and only return the `id`
   * const reviewedEntityWithIdOnly = await prisma.reviewedEntity.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReviewedEntityUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReviewedEntityUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ReviewedEntity.
   * @param {ReviewedEntityUpsertArgs} args - Arguments to update or create a ReviewedEntity.
   * @example
   * // Update or create a ReviewedEntity
   * const reviewedEntity = await prisma.reviewedEntity.upsert({
   *   create: {
   *     // ... data to create a ReviewedEntity
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReviewedEntity we want to update
   *   }
   * })
   */
  upsert<T extends ReviewedEntityUpsertArgs>(args: Prisma.SelectSubset<T, ReviewedEntityUpsertArgs<ExtArgs>>): Prisma.Prisma__ReviewedEntityClient<runtime.Types.Result.GetResult<Prisma.$ReviewedEntityPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReviewedEntities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewedEntityCountArgs} args - Arguments to filter ReviewedEntities to count.
   * @example
   * // Count the number of ReviewedEntities
   * const count = await prisma.reviewedEntity.count({
   *   where: {
   *     // ... the filter for the ReviewedEntities we want to count
   *   }
   * })
  **/
  count<T extends ReviewedEntityCountArgs>(
    args?: Prisma.Subset<T, ReviewedEntityCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReviewedEntityCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReviewedEntity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewedEntityAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReviewedEntityAggregateArgs>(args: Prisma.Subset<T, ReviewedEntityAggregateArgs>): Prisma.PrismaPromise<GetReviewedEntityAggregateType<T>>

  /**
   * Group by ReviewedEntity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewedEntityGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReviewedEntityGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReviewedEntityGroupByArgs['orderBy'] }
      : { orderBy?: ReviewedEntityGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReviewedEntityGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReviewedEntityGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReviewedEntity model
 */
readonly fields: ReviewedEntityFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReviewedEntity.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReviewedEntityClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  reviewer<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  review<T extends Prisma.ReviewDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ReviewDefaultArgs<ExtArgs>>): Prisma.Prisma__ReviewClient<runtime.Types.Result.GetResult<Prisma.$ReviewPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReviewedEntity model
 */
export interface ReviewedEntityFieldRefs {
  readonly id: Prisma.FieldRef<"ReviewedEntity", 'String'>
  readonly entityType: Prisma.FieldRef<"ReviewedEntity", 'REVIEWED_ENTITY_TYPE'>
  readonly entityId: Prisma.FieldRef<"ReviewedEntity", 'String'>
  readonly reviewedAt: Prisma.FieldRef<"ReviewedEntity", 'DateTime'>
  readonly reviewedById: Prisma.FieldRef<"ReviewedEntity", 'String'>
  readonly reviewId: Prisma.FieldRef<"ReviewedEntity", 'String'>
}
    

// Custom InputTypes
/**
 * ReviewedEntity findUnique
 */
export type ReviewedEntityFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityInclude<ExtArgs> | null
  /**
   * Filter, which ReviewedEntity to fetch.
   */
  where: Prisma.ReviewedEntityWhereUniqueInput
}

/**
 * ReviewedEntity findUniqueOrThrow
 */
export type ReviewedEntityFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityInclude<ExtArgs> | null
  /**
   * Filter, which ReviewedEntity to fetch.
   */
  where: Prisma.ReviewedEntityWhereUniqueInput
}

/**
 * ReviewedEntity findFirst
 */
export type ReviewedEntityFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityInclude<ExtArgs> | null
  /**
   * Filter, which ReviewedEntity to fetch.
   */
  where?: Prisma.ReviewedEntityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReviewedEntities to fetch.
   */
  orderBy?: Prisma.ReviewedEntityOrderByWithRelationInput | Prisma.ReviewedEntityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReviewedEntities.
   */
  cursor?: Prisma.ReviewedEntityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReviewedEntities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReviewedEntities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReviewedEntities.
   */
  distinct?: Prisma.ReviewedEntityScalarFieldEnum | Prisma.ReviewedEntityScalarFieldEnum[]
}

/**
 * ReviewedEntity findFirstOrThrow
 */
export type ReviewedEntityFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityInclude<ExtArgs> | null
  /**
   * Filter, which ReviewedEntity to fetch.
   */
  where?: Prisma.ReviewedEntityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReviewedEntities to fetch.
   */
  orderBy?: Prisma.ReviewedEntityOrderByWithRelationInput | Prisma.ReviewedEntityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReviewedEntities.
   */
  cursor?: Prisma.ReviewedEntityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReviewedEntities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReviewedEntities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReviewedEntities.
   */
  distinct?: Prisma.ReviewedEntityScalarFieldEnum | Prisma.ReviewedEntityScalarFieldEnum[]
}

/**
 * ReviewedEntity findMany
 */
export type ReviewedEntityFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityInclude<ExtArgs> | null
  /**
   * Filter, which ReviewedEntities to fetch.
   */
  where?: Prisma.ReviewedEntityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReviewedEntities to fetch.
   */
  orderBy?: Prisma.ReviewedEntityOrderByWithRelationInput | Prisma.ReviewedEntityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReviewedEntities.
   */
  cursor?: Prisma.ReviewedEntityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReviewedEntities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReviewedEntities.
   */
  skip?: number
  distinct?: Prisma.ReviewedEntityScalarFieldEnum | Prisma.ReviewedEntityScalarFieldEnum[]
}

/**
 * ReviewedEntity create
 */
export type ReviewedEntityCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityInclude<ExtArgs> | null
  /**
   * The data needed to create a ReviewedEntity.
   */
  data: Prisma.XOR<Prisma.ReviewedEntityCreateInput, Prisma.ReviewedEntityUncheckedCreateInput>
}

/**
 * ReviewedEntity createMany
 */
export type ReviewedEntityCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReviewedEntities.
   */
  data: Prisma.ReviewedEntityCreateManyInput | Prisma.ReviewedEntityCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReviewedEntity createManyAndReturn
 */
export type ReviewedEntityCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * The data used to create many ReviewedEntities.
   */
  data: Prisma.ReviewedEntityCreateManyInput | Prisma.ReviewedEntityCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ReviewedEntity update
 */
export type ReviewedEntityUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityInclude<ExtArgs> | null
  /**
   * The data needed to update a ReviewedEntity.
   */
  data: Prisma.XOR<Prisma.ReviewedEntityUpdateInput, Prisma.ReviewedEntityUncheckedUpdateInput>
  /**
   * Choose, which ReviewedEntity to update.
   */
  where: Prisma.ReviewedEntityWhereUniqueInput
}

/**
 * ReviewedEntity updateMany
 */
export type ReviewedEntityUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReviewedEntities.
   */
  data: Prisma.XOR<Prisma.ReviewedEntityUpdateManyMutationInput, Prisma.ReviewedEntityUncheckedUpdateManyInput>
  /**
   * Filter which ReviewedEntities to update
   */
  where?: Prisma.ReviewedEntityWhereInput
  /**
   * Limit how many ReviewedEntities to update.
   */
  limit?: number
}

/**
 * ReviewedEntity updateManyAndReturn
 */
export type ReviewedEntityUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * The data used to update ReviewedEntities.
   */
  data: Prisma.XOR<Prisma.ReviewedEntityUpdateManyMutationInput, Prisma.ReviewedEntityUncheckedUpdateManyInput>
  /**
   * Filter which ReviewedEntities to update
   */
  where?: Prisma.ReviewedEntityWhereInput
  /**
   * Limit how many ReviewedEntities to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ReviewedEntity upsert
 */
export type ReviewedEntityUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityInclude<ExtArgs> | null
  /**
   * The filter to search for the ReviewedEntity to update in case it exists.
   */
  where: Prisma.ReviewedEntityWhereUniqueInput
  /**
   * In case the ReviewedEntity found by the `where` argument doesn't exist, create a new ReviewedEntity with this data.
   */
  create: Prisma.XOR<Prisma.ReviewedEntityCreateInput, Prisma.ReviewedEntityUncheckedCreateInput>
  /**
   * In case the ReviewedEntity was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReviewedEntityUpdateInput, Prisma.ReviewedEntityUncheckedUpdateInput>
}

/**
 * ReviewedEntity delete
 */
export type ReviewedEntityDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityInclude<ExtArgs> | null
  /**
   * Filter which ReviewedEntity to delete.
   */
  where: Prisma.ReviewedEntityWhereUniqueInput
}

/**
 * ReviewedEntity deleteMany
 */
export type ReviewedEntityDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReviewedEntities to delete
   */
  where?: Prisma.ReviewedEntityWhereInput
  /**
   * Limit how many ReviewedEntities to delete.
   */
  limit?: number
}

/**
 * ReviewedEntity without action
 */
export type ReviewedEntityDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewedEntity
   */
  select?: Prisma.ReviewedEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewedEntity
   */
  omit?: Prisma.ReviewedEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewedEntityInclude<ExtArgs> | null
}
