
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TempoIndication` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TempoIndication
 * 
 */
export type TempoIndicationModel = runtime.Types.Result.DefaultSelection<Prisma.$TempoIndicationPayload>

export type AggregateTempoIndication = {
  _count: TempoIndicationCountAggregateOutputType | null
  _min: TempoIndicationMinAggregateOutputType | null
  _max: TempoIndicationMaxAggregateOutputType | null
}

export type TempoIndicationMinAggregateOutputType = {
  id: string | null
  text: string | null
  creatorId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TempoIndicationMaxAggregateOutputType = {
  id: string | null
  text: string | null
  creatorId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TempoIndicationCountAggregateOutputType = {
  id: number
  text: number
  creatorId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TempoIndicationMinAggregateInputType = {
  id?: true
  text?: true
  creatorId?: true
  createdAt?: true
  updatedAt?: true
}

export type TempoIndicationMaxAggregateInputType = {
  id?: true
  text?: true
  creatorId?: true
  createdAt?: true
  updatedAt?: true
}

export type TempoIndicationCountAggregateInputType = {
  id?: true
  text?: true
  creatorId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TempoIndicationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempoIndication to aggregate.
   */
  where?: Prisma.TempoIndicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempoIndications to fetch.
   */
  orderBy?: Prisma.TempoIndicationOrderByWithRelationInput | Prisma.TempoIndicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TempoIndicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempoIndications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempoIndications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TempoIndications
  **/
  _count?: true | TempoIndicationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TempoIndicationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TempoIndicationMaxAggregateInputType
}

export type GetTempoIndicationAggregateType<T extends TempoIndicationAggregateArgs> = {
      [P in keyof T & keyof AggregateTempoIndication]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTempoIndication[P]>
    : Prisma.GetScalarType<T[P], AggregateTempoIndication[P]>
}




export type TempoIndicationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempoIndicationWhereInput
  orderBy?: Prisma.TempoIndicationOrderByWithAggregationInput | Prisma.TempoIndicationOrderByWithAggregationInput[]
  by: Prisma.TempoIndicationScalarFieldEnum[] | Prisma.TempoIndicationScalarFieldEnum
  having?: Prisma.TempoIndicationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TempoIndicationCountAggregateInputType | true
  _min?: TempoIndicationMinAggregateInputType
  _max?: TempoIndicationMaxAggregateInputType
}

export type TempoIndicationGroupByOutputType = {
  id: string
  text: string
  creatorId: string | null
  createdAt: Date
  updatedAt: Date
  _count: TempoIndicationCountAggregateOutputType | null
  _min: TempoIndicationMinAggregateOutputType | null
  _max: TempoIndicationMaxAggregateOutputType | null
}

type GetTempoIndicationGroupByPayload<T extends TempoIndicationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TempoIndicationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TempoIndicationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TempoIndicationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TempoIndicationGroupByOutputType[P]>
      }
    >
  >



export type TempoIndicationWhereInput = {
  AND?: Prisma.TempoIndicationWhereInput | Prisma.TempoIndicationWhereInput[]
  OR?: Prisma.TempoIndicationWhereInput[]
  NOT?: Prisma.TempoIndicationWhereInput | Prisma.TempoIndicationWhereInput[]
  id?: Prisma.UuidFilter<"TempoIndication"> | string
  text?: Prisma.StringFilter<"TempoIndication"> | string
  creatorId?: Prisma.UuidNullableFilter<"TempoIndication"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TempoIndication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempoIndication"> | Date | string
  sections?: Prisma.SectionListRelationFilter
  creator?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type TempoIndicationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  creatorId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  sections?: Prisma.SectionOrderByRelationAggregateInput
  creator?: Prisma.UserOrderByWithRelationInput
}

export type TempoIndicationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  text?: string
  AND?: Prisma.TempoIndicationWhereInput | Prisma.TempoIndicationWhereInput[]
  OR?: Prisma.TempoIndicationWhereInput[]
  NOT?: Prisma.TempoIndicationWhereInput | Prisma.TempoIndicationWhereInput[]
  creatorId?: Prisma.UuidNullableFilter<"TempoIndication"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TempoIndication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempoIndication"> | Date | string
  sections?: Prisma.SectionListRelationFilter
  creator?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "text">

export type TempoIndicationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  creatorId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TempoIndicationCountOrderByAggregateInput
  _max?: Prisma.TempoIndicationMaxOrderByAggregateInput
  _min?: Prisma.TempoIndicationMinOrderByAggregateInput
}

export type TempoIndicationScalarWhereWithAggregatesInput = {
  AND?: Prisma.TempoIndicationScalarWhereWithAggregatesInput | Prisma.TempoIndicationScalarWhereWithAggregatesInput[]
  OR?: Prisma.TempoIndicationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TempoIndicationScalarWhereWithAggregatesInput | Prisma.TempoIndicationScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"TempoIndication"> | string
  text?: Prisma.StringWithAggregatesFilter<"TempoIndication"> | string
  creatorId?: Prisma.UuidNullableWithAggregatesFilter<"TempoIndication"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TempoIndication"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TempoIndication"> | Date | string
}

export type TempoIndicationCreateInput = {
  id?: string
  text: string
  createdAt?: Date | string
  updatedAt?: Date | string
  sections?: Prisma.SectionCreateNestedManyWithoutTempoIndicationInput
  creator?: Prisma.UserCreateNestedOneWithoutTempoIndicationsInput
}

export type TempoIndicationUncheckedCreateInput = {
  id?: string
  text: string
  creatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sections?: Prisma.SectionUncheckedCreateNestedManyWithoutTempoIndicationInput
}

export type TempoIndicationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.SectionUpdateManyWithoutTempoIndicationNestedInput
  creator?: Prisma.UserUpdateOneWithoutTempoIndicationsNestedInput
}

export type TempoIndicationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  creatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.SectionUncheckedUpdateManyWithoutTempoIndicationNestedInput
}

export type TempoIndicationCreateManyInput = {
  id?: string
  text: string
  creatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempoIndicationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempoIndicationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  creatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempoIndicationScalarRelationFilter = {
  is?: Prisma.TempoIndicationWhereInput
  isNot?: Prisma.TempoIndicationWhereInput
}

export type TempoIndicationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TempoIndicationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TempoIndicationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TempoIndicationListRelationFilter = {
  every?: Prisma.TempoIndicationWhereInput
  some?: Prisma.TempoIndicationWhereInput
  none?: Prisma.TempoIndicationWhereInput
}

export type TempoIndicationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TempoIndicationCreateNestedOneWithoutSectionsInput = {
  create?: Prisma.XOR<Prisma.TempoIndicationCreateWithoutSectionsInput, Prisma.TempoIndicationUncheckedCreateWithoutSectionsInput>
  connectOrCreate?: Prisma.TempoIndicationCreateOrConnectWithoutSectionsInput
  connect?: Prisma.TempoIndicationWhereUniqueInput
}

export type TempoIndicationUpdateOneRequiredWithoutSectionsNestedInput = {
  create?: Prisma.XOR<Prisma.TempoIndicationCreateWithoutSectionsInput, Prisma.TempoIndicationUncheckedCreateWithoutSectionsInput>
  connectOrCreate?: Prisma.TempoIndicationCreateOrConnectWithoutSectionsInput
  upsert?: Prisma.TempoIndicationUpsertWithoutSectionsInput
  connect?: Prisma.TempoIndicationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TempoIndicationUpdateToOneWithWhereWithoutSectionsInput, Prisma.TempoIndicationUpdateWithoutSectionsInput>, Prisma.TempoIndicationUncheckedUpdateWithoutSectionsInput>
}

export type TempoIndicationCreateNestedManyWithoutCreatorInput = {
  create?: Prisma.XOR<Prisma.TempoIndicationCreateWithoutCreatorInput, Prisma.TempoIndicationUncheckedCreateWithoutCreatorInput> | Prisma.TempoIndicationCreateWithoutCreatorInput[] | Prisma.TempoIndicationUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.TempoIndicationCreateOrConnectWithoutCreatorInput | Prisma.TempoIndicationCreateOrConnectWithoutCreatorInput[]
  createMany?: Prisma.TempoIndicationCreateManyCreatorInputEnvelope
  connect?: Prisma.TempoIndicationWhereUniqueInput | Prisma.TempoIndicationWhereUniqueInput[]
}

export type TempoIndicationUncheckedCreateNestedManyWithoutCreatorInput = {
  create?: Prisma.XOR<Prisma.TempoIndicationCreateWithoutCreatorInput, Prisma.TempoIndicationUncheckedCreateWithoutCreatorInput> | Prisma.TempoIndicationCreateWithoutCreatorInput[] | Prisma.TempoIndicationUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.TempoIndicationCreateOrConnectWithoutCreatorInput | Prisma.TempoIndicationCreateOrConnectWithoutCreatorInput[]
  createMany?: Prisma.TempoIndicationCreateManyCreatorInputEnvelope
  connect?: Prisma.TempoIndicationWhereUniqueInput | Prisma.TempoIndicationWhereUniqueInput[]
}

export type TempoIndicationUpdateManyWithoutCreatorNestedInput = {
  create?: Prisma.XOR<Prisma.TempoIndicationCreateWithoutCreatorInput, Prisma.TempoIndicationUncheckedCreateWithoutCreatorInput> | Prisma.TempoIndicationCreateWithoutCreatorInput[] | Prisma.TempoIndicationUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.TempoIndicationCreateOrConnectWithoutCreatorInput | Prisma.TempoIndicationCreateOrConnectWithoutCreatorInput[]
  upsert?: Prisma.TempoIndicationUpsertWithWhereUniqueWithoutCreatorInput | Prisma.TempoIndicationUpsertWithWhereUniqueWithoutCreatorInput[]
  createMany?: Prisma.TempoIndicationCreateManyCreatorInputEnvelope
  set?: Prisma.TempoIndicationWhereUniqueInput | Prisma.TempoIndicationWhereUniqueInput[]
  disconnect?: Prisma.TempoIndicationWhereUniqueInput | Prisma.TempoIndicationWhereUniqueInput[]
  delete?: Prisma.TempoIndicationWhereUniqueInput | Prisma.TempoIndicationWhereUniqueInput[]
  connect?: Prisma.TempoIndicationWhereUniqueInput | Prisma.TempoIndicationWhereUniqueInput[]
  update?: Prisma.TempoIndicationUpdateWithWhereUniqueWithoutCreatorInput | Prisma.TempoIndicationUpdateWithWhereUniqueWithoutCreatorInput[]
  updateMany?: Prisma.TempoIndicationUpdateManyWithWhereWithoutCreatorInput | Prisma.TempoIndicationUpdateManyWithWhereWithoutCreatorInput[]
  deleteMany?: Prisma.TempoIndicationScalarWhereInput | Prisma.TempoIndicationScalarWhereInput[]
}

export type TempoIndicationUncheckedUpdateManyWithoutCreatorNestedInput = {
  create?: Prisma.XOR<Prisma.TempoIndicationCreateWithoutCreatorInput, Prisma.TempoIndicationUncheckedCreateWithoutCreatorInput> | Prisma.TempoIndicationCreateWithoutCreatorInput[] | Prisma.TempoIndicationUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.TempoIndicationCreateOrConnectWithoutCreatorInput | Prisma.TempoIndicationCreateOrConnectWithoutCreatorInput[]
  upsert?: Prisma.TempoIndicationUpsertWithWhereUniqueWithoutCreatorInput | Prisma.TempoIndicationUpsertWithWhereUniqueWithoutCreatorInput[]
  createMany?: Prisma.TempoIndicationCreateManyCreatorInputEnvelope
  set?: Prisma.TempoIndicationWhereUniqueInput | Prisma.TempoIndicationWhereUniqueInput[]
  disconnect?: Prisma.TempoIndicationWhereUniqueInput | Prisma.TempoIndicationWhereUniqueInput[]
  delete?: Prisma.TempoIndicationWhereUniqueInput | Prisma.TempoIndicationWhereUniqueInput[]
  connect?: Prisma.TempoIndicationWhereUniqueInput | Prisma.TempoIndicationWhereUniqueInput[]
  update?: Prisma.TempoIndicationUpdateWithWhereUniqueWithoutCreatorInput | Prisma.TempoIndicationUpdateWithWhereUniqueWithoutCreatorInput[]
  updateMany?: Prisma.TempoIndicationUpdateManyWithWhereWithoutCreatorInput | Prisma.TempoIndicationUpdateManyWithWhereWithoutCreatorInput[]
  deleteMany?: Prisma.TempoIndicationScalarWhereInput | Prisma.TempoIndicationScalarWhereInput[]
}

export type TempoIndicationCreateWithoutSectionsInput = {
  id?: string
  text: string
  createdAt?: Date | string
  updatedAt?: Date | string
  creator?: Prisma.UserCreateNestedOneWithoutTempoIndicationsInput
}

export type TempoIndicationUncheckedCreateWithoutSectionsInput = {
  id?: string
  text: string
  creatorId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempoIndicationCreateOrConnectWithoutSectionsInput = {
  where: Prisma.TempoIndicationWhereUniqueInput
  create: Prisma.XOR<Prisma.TempoIndicationCreateWithoutSectionsInput, Prisma.TempoIndicationUncheckedCreateWithoutSectionsInput>
}

export type TempoIndicationUpsertWithoutSectionsInput = {
  update: Prisma.XOR<Prisma.TempoIndicationUpdateWithoutSectionsInput, Prisma.TempoIndicationUncheckedUpdateWithoutSectionsInput>
  create: Prisma.XOR<Prisma.TempoIndicationCreateWithoutSectionsInput, Prisma.TempoIndicationUncheckedCreateWithoutSectionsInput>
  where?: Prisma.TempoIndicationWhereInput
}

export type TempoIndicationUpdateToOneWithWhereWithoutSectionsInput = {
  where?: Prisma.TempoIndicationWhereInput
  data: Prisma.XOR<Prisma.TempoIndicationUpdateWithoutSectionsInput, Prisma.TempoIndicationUncheckedUpdateWithoutSectionsInput>
}

export type TempoIndicationUpdateWithoutSectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  creator?: Prisma.UserUpdateOneWithoutTempoIndicationsNestedInput
}

export type TempoIndicationUncheckedUpdateWithoutSectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  creatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempoIndicationCreateWithoutCreatorInput = {
  id?: string
  text: string
  createdAt?: Date | string
  updatedAt?: Date | string
  sections?: Prisma.SectionCreateNestedManyWithoutTempoIndicationInput
}

export type TempoIndicationUncheckedCreateWithoutCreatorInput = {
  id?: string
  text: string
  createdAt?: Date | string
  updatedAt?: Date | string
  sections?: Prisma.SectionUncheckedCreateNestedManyWithoutTempoIndicationInput
}

export type TempoIndicationCreateOrConnectWithoutCreatorInput = {
  where: Prisma.TempoIndicationWhereUniqueInput
  create: Prisma.XOR<Prisma.TempoIndicationCreateWithoutCreatorInput, Prisma.TempoIndicationUncheckedCreateWithoutCreatorInput>
}

export type TempoIndicationCreateManyCreatorInputEnvelope = {
  data: Prisma.TempoIndicationCreateManyCreatorInput | Prisma.TempoIndicationCreateManyCreatorInput[]
  skipDuplicates?: boolean
}

export type TempoIndicationUpsertWithWhereUniqueWithoutCreatorInput = {
  where: Prisma.TempoIndicationWhereUniqueInput
  update: Prisma.XOR<Prisma.TempoIndicationUpdateWithoutCreatorInput, Prisma.TempoIndicationUncheckedUpdateWithoutCreatorInput>
  create: Prisma.XOR<Prisma.TempoIndicationCreateWithoutCreatorInput, Prisma.TempoIndicationUncheckedCreateWithoutCreatorInput>
}

export type TempoIndicationUpdateWithWhereUniqueWithoutCreatorInput = {
  where: Prisma.TempoIndicationWhereUniqueInput
  data: Prisma.XOR<Prisma.TempoIndicationUpdateWithoutCreatorInput, Prisma.TempoIndicationUncheckedUpdateWithoutCreatorInput>
}

export type TempoIndicationUpdateManyWithWhereWithoutCreatorInput = {
  where: Prisma.TempoIndicationScalarWhereInput
  data: Prisma.XOR<Prisma.TempoIndicationUpdateManyMutationInput, Prisma.TempoIndicationUncheckedUpdateManyWithoutCreatorInput>
}

export type TempoIndicationScalarWhereInput = {
  AND?: Prisma.TempoIndicationScalarWhereInput | Prisma.TempoIndicationScalarWhereInput[]
  OR?: Prisma.TempoIndicationScalarWhereInput[]
  NOT?: Prisma.TempoIndicationScalarWhereInput | Prisma.TempoIndicationScalarWhereInput[]
  id?: Prisma.UuidFilter<"TempoIndication"> | string
  text?: Prisma.StringFilter<"TempoIndication"> | string
  creatorId?: Prisma.UuidNullableFilter<"TempoIndication"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TempoIndication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempoIndication"> | Date | string
}

export type TempoIndicationCreateManyCreatorInput = {
  id?: string
  text: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempoIndicationUpdateWithoutCreatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.SectionUpdateManyWithoutTempoIndicationNestedInput
}

export type TempoIndicationUncheckedUpdateWithoutCreatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.SectionUncheckedUpdateManyWithoutTempoIndicationNestedInput
}

export type TempoIndicationUncheckedUpdateManyWithoutCreatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TempoIndicationCountOutputType
 */

export type TempoIndicationCountOutputType = {
  sections: number
}

export type TempoIndicationCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sections?: boolean | TempoIndicationCountOutputTypeCountSectionsArgs
}

/**
 * TempoIndicationCountOutputType without action
 */
export type TempoIndicationCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndicationCountOutputType
   */
  select?: Prisma.TempoIndicationCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TempoIndicationCountOutputType without action
 */
export type TempoIndicationCountOutputTypeCountSectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SectionWhereInput
}


export type TempoIndicationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  creatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sections?: boolean | Prisma.TempoIndication$sectionsArgs<ExtArgs>
  creator?: boolean | Prisma.TempoIndication$creatorArgs<ExtArgs>
  _count?: boolean | Prisma.TempoIndicationCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempoIndication"]>

export type TempoIndicationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  creatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  creator?: boolean | Prisma.TempoIndication$creatorArgs<ExtArgs>
}, ExtArgs["result"]["tempoIndication"]>

export type TempoIndicationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  creatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  creator?: boolean | Prisma.TempoIndication$creatorArgs<ExtArgs>
}, ExtArgs["result"]["tempoIndication"]>

export type TempoIndicationSelectScalar = {
  id?: boolean
  text?: boolean
  creatorId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TempoIndicationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "text" | "creatorId" | "createdAt" | "updatedAt", ExtArgs["result"]["tempoIndication"]>
export type TempoIndicationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sections?: boolean | Prisma.TempoIndication$sectionsArgs<ExtArgs>
  creator?: boolean | Prisma.TempoIndication$creatorArgs<ExtArgs>
  _count?: boolean | Prisma.TempoIndicationCountOutputTypeDefaultArgs<ExtArgs>
}
export type TempoIndicationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  creator?: boolean | Prisma.TempoIndication$creatorArgs<ExtArgs>
}
export type TempoIndicationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  creator?: boolean | Prisma.TempoIndication$creatorArgs<ExtArgs>
}

export type $TempoIndicationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TempoIndication"
  objects: {
    sections: Prisma.$SectionPayload<ExtArgs>[]
    creator: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    text: string
    creatorId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tempoIndication"]>
  composites: {}
}

export type TempoIndicationGetPayload<S extends boolean | null | undefined | TempoIndicationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload, S>

export type TempoIndicationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TempoIndicationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TempoIndicationCountAggregateInputType | true
  }

export interface TempoIndicationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TempoIndication'], meta: { name: 'TempoIndication' } }
  /**
   * Find zero or one TempoIndication that matches the filter.
   * @param {TempoIndicationFindUniqueArgs} args - Arguments to find a TempoIndication
   * @example
   * // Get one TempoIndication
   * const tempoIndication = await prisma.tempoIndication.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TempoIndicationFindUniqueArgs>(args: Prisma.SelectSubset<T, TempoIndicationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TempoIndicationClient<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TempoIndication that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TempoIndicationFindUniqueOrThrowArgs} args - Arguments to find a TempoIndication
   * @example
   * // Get one TempoIndication
   * const tempoIndication = await prisma.tempoIndication.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TempoIndicationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TempoIndicationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempoIndicationClient<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempoIndication that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempoIndicationFindFirstArgs} args - Arguments to find a TempoIndication
   * @example
   * // Get one TempoIndication
   * const tempoIndication = await prisma.tempoIndication.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TempoIndicationFindFirstArgs>(args?: Prisma.SelectSubset<T, TempoIndicationFindFirstArgs<ExtArgs>>): Prisma.Prisma__TempoIndicationClient<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempoIndication that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempoIndicationFindFirstOrThrowArgs} args - Arguments to find a TempoIndication
   * @example
   * // Get one TempoIndication
   * const tempoIndication = await prisma.tempoIndication.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TempoIndicationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TempoIndicationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempoIndicationClient<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TempoIndications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempoIndicationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TempoIndications
   * const tempoIndications = await prisma.tempoIndication.findMany()
   * 
   * // Get first 10 TempoIndications
   * const tempoIndications = await prisma.tempoIndication.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tempoIndicationWithIdOnly = await prisma.tempoIndication.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TempoIndicationFindManyArgs>(args?: Prisma.SelectSubset<T, TempoIndicationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TempoIndication.
   * @param {TempoIndicationCreateArgs} args - Arguments to create a TempoIndication.
   * @example
   * // Create one TempoIndication
   * const TempoIndication = await prisma.tempoIndication.create({
   *   data: {
   *     // ... data to create a TempoIndication
   *   }
   * })
   * 
   */
  create<T extends TempoIndicationCreateArgs>(args: Prisma.SelectSubset<T, TempoIndicationCreateArgs<ExtArgs>>): Prisma.Prisma__TempoIndicationClient<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TempoIndications.
   * @param {TempoIndicationCreateManyArgs} args - Arguments to create many TempoIndications.
   * @example
   * // Create many TempoIndications
   * const tempoIndication = await prisma.tempoIndication.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TempoIndicationCreateManyArgs>(args?: Prisma.SelectSubset<T, TempoIndicationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TempoIndications and returns the data saved in the database.
   * @param {TempoIndicationCreateManyAndReturnArgs} args - Arguments to create many TempoIndications.
   * @example
   * // Create many TempoIndications
   * const tempoIndication = await prisma.tempoIndication.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TempoIndications and only return the `id`
   * const tempoIndicationWithIdOnly = await prisma.tempoIndication.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TempoIndicationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TempoIndicationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TempoIndication.
   * @param {TempoIndicationDeleteArgs} args - Arguments to delete one TempoIndication.
   * @example
   * // Delete one TempoIndication
   * const TempoIndication = await prisma.tempoIndication.delete({
   *   where: {
   *     // ... filter to delete one TempoIndication
   *   }
   * })
   * 
   */
  delete<T extends TempoIndicationDeleteArgs>(args: Prisma.SelectSubset<T, TempoIndicationDeleteArgs<ExtArgs>>): Prisma.Prisma__TempoIndicationClient<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TempoIndication.
   * @param {TempoIndicationUpdateArgs} args - Arguments to update one TempoIndication.
   * @example
   * // Update one TempoIndication
   * const tempoIndication = await prisma.tempoIndication.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TempoIndicationUpdateArgs>(args: Prisma.SelectSubset<T, TempoIndicationUpdateArgs<ExtArgs>>): Prisma.Prisma__TempoIndicationClient<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TempoIndications.
   * @param {TempoIndicationDeleteManyArgs} args - Arguments to filter TempoIndications to delete.
   * @example
   * // Delete a few TempoIndications
   * const { count } = await prisma.tempoIndication.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TempoIndicationDeleteManyArgs>(args?: Prisma.SelectSubset<T, TempoIndicationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempoIndications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempoIndicationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TempoIndications
   * const tempoIndication = await prisma.tempoIndication.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TempoIndicationUpdateManyArgs>(args: Prisma.SelectSubset<T, TempoIndicationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempoIndications and returns the data updated in the database.
   * @param {TempoIndicationUpdateManyAndReturnArgs} args - Arguments to update many TempoIndications.
   * @example
   * // Update many TempoIndications
   * const tempoIndication = await prisma.tempoIndication.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TempoIndications and only return the `id`
   * const tempoIndicationWithIdOnly = await prisma.tempoIndication.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TempoIndicationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TempoIndicationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TempoIndication.
   * @param {TempoIndicationUpsertArgs} args - Arguments to update or create a TempoIndication.
   * @example
   * // Update or create a TempoIndication
   * const tempoIndication = await prisma.tempoIndication.upsert({
   *   create: {
   *     // ... data to create a TempoIndication
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TempoIndication we want to update
   *   }
   * })
   */
  upsert<T extends TempoIndicationUpsertArgs>(args: Prisma.SelectSubset<T, TempoIndicationUpsertArgs<ExtArgs>>): Prisma.Prisma__TempoIndicationClient<runtime.Types.Result.GetResult<Prisma.$TempoIndicationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TempoIndications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempoIndicationCountArgs} args - Arguments to filter TempoIndications to count.
   * @example
   * // Count the number of TempoIndications
   * const count = await prisma.tempoIndication.count({
   *   where: {
   *     // ... the filter for the TempoIndications we want to count
   *   }
   * })
  **/
  count<T extends TempoIndicationCountArgs>(
    args?: Prisma.Subset<T, TempoIndicationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TempoIndicationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TempoIndication.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempoIndicationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TempoIndicationAggregateArgs>(args: Prisma.Subset<T, TempoIndicationAggregateArgs>): Prisma.PrismaPromise<GetTempoIndicationAggregateType<T>>

  /**
   * Group by TempoIndication.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempoIndicationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TempoIndicationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TempoIndicationGroupByArgs['orderBy'] }
      : { orderBy?: TempoIndicationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TempoIndicationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTempoIndicationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TempoIndication model
 */
readonly fields: TempoIndicationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TempoIndication.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TempoIndicationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sections<T extends Prisma.TempoIndication$sectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempoIndication$sectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  creator<T extends Prisma.TempoIndication$creatorArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempoIndication$creatorArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TempoIndication model
 */
export interface TempoIndicationFieldRefs {
  readonly id: Prisma.FieldRef<"TempoIndication", 'String'>
  readonly text: Prisma.FieldRef<"TempoIndication", 'String'>
  readonly creatorId: Prisma.FieldRef<"TempoIndication", 'String'>
  readonly createdAt: Prisma.FieldRef<"TempoIndication", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TempoIndication", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TempoIndication findUnique
 */
export type TempoIndicationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationInclude<ExtArgs> | null
  /**
   * Filter, which TempoIndication to fetch.
   */
  where: Prisma.TempoIndicationWhereUniqueInput
}

/**
 * TempoIndication findUniqueOrThrow
 */
export type TempoIndicationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationInclude<ExtArgs> | null
  /**
   * Filter, which TempoIndication to fetch.
   */
  where: Prisma.TempoIndicationWhereUniqueInput
}

/**
 * TempoIndication findFirst
 */
export type TempoIndicationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationInclude<ExtArgs> | null
  /**
   * Filter, which TempoIndication to fetch.
   */
  where?: Prisma.TempoIndicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempoIndications to fetch.
   */
  orderBy?: Prisma.TempoIndicationOrderByWithRelationInput | Prisma.TempoIndicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempoIndications.
   */
  cursor?: Prisma.TempoIndicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempoIndications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempoIndications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempoIndications.
   */
  distinct?: Prisma.TempoIndicationScalarFieldEnum | Prisma.TempoIndicationScalarFieldEnum[]
}

/**
 * TempoIndication findFirstOrThrow
 */
export type TempoIndicationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationInclude<ExtArgs> | null
  /**
   * Filter, which TempoIndication to fetch.
   */
  where?: Prisma.TempoIndicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempoIndications to fetch.
   */
  orderBy?: Prisma.TempoIndicationOrderByWithRelationInput | Prisma.TempoIndicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempoIndications.
   */
  cursor?: Prisma.TempoIndicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempoIndications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempoIndications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempoIndications.
   */
  distinct?: Prisma.TempoIndicationScalarFieldEnum | Prisma.TempoIndicationScalarFieldEnum[]
}

/**
 * TempoIndication findMany
 */
export type TempoIndicationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationInclude<ExtArgs> | null
  /**
   * Filter, which TempoIndications to fetch.
   */
  where?: Prisma.TempoIndicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempoIndications to fetch.
   */
  orderBy?: Prisma.TempoIndicationOrderByWithRelationInput | Prisma.TempoIndicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TempoIndications.
   */
  cursor?: Prisma.TempoIndicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempoIndications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempoIndications.
   */
  skip?: number
  distinct?: Prisma.TempoIndicationScalarFieldEnum | Prisma.TempoIndicationScalarFieldEnum[]
}

/**
 * TempoIndication create
 */
export type TempoIndicationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationInclude<ExtArgs> | null
  /**
   * The data needed to create a TempoIndication.
   */
  data: Prisma.XOR<Prisma.TempoIndicationCreateInput, Prisma.TempoIndicationUncheckedCreateInput>
}

/**
 * TempoIndication createMany
 */
export type TempoIndicationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TempoIndications.
   */
  data: Prisma.TempoIndicationCreateManyInput | Prisma.TempoIndicationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TempoIndication createManyAndReturn
 */
export type TempoIndicationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * The data used to create many TempoIndications.
   */
  data: Prisma.TempoIndicationCreateManyInput | Prisma.TempoIndicationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TempoIndication update
 */
export type TempoIndicationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationInclude<ExtArgs> | null
  /**
   * The data needed to update a TempoIndication.
   */
  data: Prisma.XOR<Prisma.TempoIndicationUpdateInput, Prisma.TempoIndicationUncheckedUpdateInput>
  /**
   * Choose, which TempoIndication to update.
   */
  where: Prisma.TempoIndicationWhereUniqueInput
}

/**
 * TempoIndication updateMany
 */
export type TempoIndicationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TempoIndications.
   */
  data: Prisma.XOR<Prisma.TempoIndicationUpdateManyMutationInput, Prisma.TempoIndicationUncheckedUpdateManyInput>
  /**
   * Filter which TempoIndications to update
   */
  where?: Prisma.TempoIndicationWhereInput
  /**
   * Limit how many TempoIndications to update.
   */
  limit?: number
}

/**
 * TempoIndication updateManyAndReturn
 */
export type TempoIndicationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * The data used to update TempoIndications.
   */
  data: Prisma.XOR<Prisma.TempoIndicationUpdateManyMutationInput, Prisma.TempoIndicationUncheckedUpdateManyInput>
  /**
   * Filter which TempoIndications to update
   */
  where?: Prisma.TempoIndicationWhereInput
  /**
   * Limit how many TempoIndications to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TempoIndication upsert
 */
export type TempoIndicationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationInclude<ExtArgs> | null
  /**
   * The filter to search for the TempoIndication to update in case it exists.
   */
  where: Prisma.TempoIndicationWhereUniqueInput
  /**
   * In case the TempoIndication found by the `where` argument doesn't exist, create a new TempoIndication with this data.
   */
  create: Prisma.XOR<Prisma.TempoIndicationCreateInput, Prisma.TempoIndicationUncheckedCreateInput>
  /**
   * In case the TempoIndication was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TempoIndicationUpdateInput, Prisma.TempoIndicationUncheckedUpdateInput>
}

/**
 * TempoIndication delete
 */
export type TempoIndicationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationInclude<ExtArgs> | null
  /**
   * Filter which TempoIndication to delete.
   */
  where: Prisma.TempoIndicationWhereUniqueInput
}

/**
 * TempoIndication deleteMany
 */
export type TempoIndicationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempoIndications to delete
   */
  where?: Prisma.TempoIndicationWhereInput
  /**
   * Limit how many TempoIndications to delete.
   */
  limit?: number
}

/**
 * TempoIndication.sections
 */
export type TempoIndication$sectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Section
   */
  select?: Prisma.SectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Section
   */
  omit?: Prisma.SectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SectionInclude<ExtArgs> | null
  where?: Prisma.SectionWhereInput
  orderBy?: Prisma.SectionOrderByWithRelationInput | Prisma.SectionOrderByWithRelationInput[]
  cursor?: Prisma.SectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SectionScalarFieldEnum | Prisma.SectionScalarFieldEnum[]
}

/**
 * TempoIndication.creator
 */
export type TempoIndication$creatorArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * TempoIndication without action
 */
export type TempoIndicationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempoIndication
   */
  select?: Prisma.TempoIndicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempoIndication
   */
  omit?: Prisma.TempoIndicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempoIndicationInclude<ExtArgs> | null
}
