### POST feedForm submit
// @no-log
< {%
  import { getToken } from './getToken.js'
  const creatorId = request.environment.get("accountId_Johan");
  const payload = {
    id: creatorId
  }
  request.variables.set("jwt_token", getToken(payload));
%}
POST {{apiUrl}}/feedForm
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "formInfo": {
    "currentStepRank": 5,
    "introDone": true,
    "isSourceOnPieceVersionformOpen": false,
    "formType": "collection",
    "allSourceOnPieceVersionsDone": true
  },
  "mMSourceContributions": [
    {
      "person": {
        "id": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
        "firstName": "Hans",
        "lastName": "von Bülow",
        "birthYear": 1830,
        "deathYear": 1894
      },
      "role": "MM_PROVIDER"
    },
    {
      "organization": {
        "id": "7ef5aacf-7302-48a4-b858-60600aeaf71a",
        "name": "Jos. Aibl Verlag"
      },
      "role": "PUBLISHER"
    }
  ],
  "mMSourceOnPieceVersions": [
    {
      "pieceVersionId": "6c6b3e6e-1beb-410f-86c6-1f23e458905b",
      "rank": 1
    },
    {
      "pieceVersionId": "5a26930f-e924-4d09-81aa-a2ed254a2c65",
      "rank": 2
    },
    {
      "pieceVersionId": "0d993bf7-0de2-4389-b35e-4722834c009d",
      "rank": 3
    },
    {
      "pieceVersionId": "f4939150-4802-463c-9087-0bc134bc631f",
      "rank": 4
    },
    {
      "pieceVersionId": "8fd2680a-7bec-46b0-9005-b547a80d9f59",
      "rank": 5
    },
    {
      "pieceVersionId": "939790d7-93c5-4eca-a68d-e27eb113ca00",
      "rank": 6
    },
    {
      "pieceVersionId": "96c5ffa0-1a06-4588-aa22-ee46d6f1a77b",
      "rank": 7
    },
    {
      "pieceVersionId": "3a23a4be-84b7-463f-a5ce-47d6f018f8ec",
      "rank": 8
    },
    {
      "pieceVersionId": "07c24791-2029-4d60-bbd8-beeaa2525012",
      "rank": 9
    },
    {
      "pieceVersionId": "4fa21635-3e73-4994-a984-2fb5aec4d484",
      "rank": 10
    },
    {
      "pieceVersionId": "8288069f-4002-4fbe-9717-164c6c911d1f",
      "rank": 11
    },
    {
      "pieceVersionId": "bdfd8488-f53e-4d42-b30f-d7c8a3d727ea",
      "rank": 12
    },
    {
      "pieceVersionId": "9cc2435b-9a8f-43aa-ac56-cfa52187d0b9",
      "rank": 13
    },
    {
      "pieceVersionId": "f5fcea64-a606-448d-b0f4-94406cf0880f",
      "rank": 14
    },
    {
      "pieceVersionId": "eb66686d-bc63-43f3-aa74-c13ba2adaf36",
      "rank": 15
    },
    {
      "pieceVersionId": "3cc1496e-a244-413a-a97c-d24bbdef1fb0",
      "rank": 16
    },
    {
      "pieceVersionId": "6872eca0-227b-456e-aeec-102d12e44277",
      "rank": 17
    },
    {
      "pieceVersionId": "7e6ef633-4a9f-4106-832e-585a1f62e934",
      "rank": 18
    },
    {
      "pieceVersionId": "148e943a-ad1e-40ad-8e70-e83b82a93438",
      "rank": 19
    },
    {
      "pieceVersionId": "dc446936-f669-4be6-a0c7-c8d1da9bbe2c",
      "rank": 20
    },
    {
      "pieceVersionId": "9bccc087-d93c-41d9-beb9-f24b07ce70fc",
      "rank": 21
    },
    {
      "pieceVersionId": "0ee6e262-e213-4b28-8204-896c6a3941d1",
      "rank": 22
    },
    {
      "pieceVersionId": "faffd47b-2ea9-4b61-a17c-509ee129fbf3",
      "rank": 23
    },
    {
      "pieceVersionId": "22d1874e-d368-4ce6-a5b9-74886deae328",
      "rank": 24
    },
    {
      "pieceVersionId": "e12ad86b-3743-423c-b0dc-508f49bdea4b",
      "rank": 25
    },
    {
      "pieceVersionId": "07c9d82a-b195-454c-ac2d-e298938f0762",
      "rank": 26
    },
    {
      "pieceVersionId": "7524098e-b1ef-4b37-946d-79d1da088e94",
      "rank": 27
    },
    {
      "pieceVersionId": "49058499-5ee5-4fa0-9668-182181e4f783",
      "rank": 28
    },
    {
      "pieceVersionId": "e4685096-ab28-4ccc-8789-83e41cc6de07",
      "rank": 29
    },
    {
      "pieceVersionId": "9789a09f-9f2d-4929-866d-a77c2916c5ac",
      "rank": 30
    },
    {
      "pieceVersionId": "cdcc1a8c-8b12-4bb6-8b2f-01e021794eda",
      "rank": 31
    },
    {
      "pieceVersionId": "00b287a6-a80f-4f31-b69c-de9ead97ce23",
      "rank": 32
    },
    {
      "pieceVersionId": "67feeb40-48a8-4c49-a5f2-9cedc198dfed",
      "rank": 33
    },
    {
      "pieceVersionId": "0ce0ef09-63ef-4076-9646-a34b21d9246a",
      "rank": 34
    },
    {
      "pieceVersionId": "1197ead5-e674-4ef7-a772-a61e1242e1e3",
      "rank": 35
    },
    {
      "pieceVersionId": "7ed1bb26-8620-4240-aaa4-0a7be615fb40",
      "rank": 36
    },
    {
      "pieceVersionId": "d6517928-16e1-4fea-b73c-884480a3f92a",
      "rank": 37
    },
    {
      "pieceVersionId": "065c6ad3-5648-49ea-b57d-658495a7a161",
      "rank": 38
    }
  ],
  "collections": [
    {
      "id": "a8b37563-4812-4c73-b6b5-e0ec15ce1b8a",
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "title": "Orpheus (Gluck/von Bülow)",
      "isNew": true,
      "pieceCount": 9
    },
    {
      "id": "4e559a73-0822-4196-995a-0ea60922edfb",
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "title": "Alceste (Gluck/von Bülow)",
      "isNew": true,
      "pieceCount": 7
    },
    {
      "id": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "title": "Iphigenie in Aulis (Gluck/von Bülow)",
      "isNew": true,
      "pieceCount": 11
    },
    {
      "id": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "title": "Armide (Gluck/von Bülow)",
      "isNew": true,
      "pieceCount": 11
    }
  ],
  "metronomeMarks": [
    {
      "sectionId": "256a219f-278e-4ed8-b6dd-67ff861b1849",
      "bpm": 92,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "6c6b3e6e-1beb-410f-86c6-1f23e458905b"
    },
    {
      "sectionId": "d02368f6-b504-4815-91e2-7262d45c89cf",
      "bpm": 96,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "5a26930f-e924-4d09-81aa-a2ed254a2c65"
    },
    {
      "sectionId": "27e35ab4-e2f3-4619-94da-4c54aeaa06c2",
      "bpm": 92,
      "comment": "",
      "beatUnit": "EIGHTH",
      "noMM": false,
      "pieceVersionId": "0d993bf7-0de2-4389-b35e-4722834c009d"
    },
    {
      "sectionId": "29961b5d-6bd9-4dee-ad29-be9503a8c9e2",
      "bpm": 80,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "f4939150-4802-463c-9087-0bc134bc631f"
    },
    {
      "sectionId": "e97231ba-cfea-43f6-ba24-531bed2e5347",
      "bpm": 88,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "f4939150-4802-463c-9087-0bc134bc631f"
    },
    {
      "sectionId": "f5ca8643-db49-4dea-951c-de3fe5942231",
      "bpm": 104,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "8fd2680a-7bec-46b0-9005-b547a80d9f59"
    },
    {
      "sectionId": "e346448c-5a2a-4550-ba61-06730692a0bb",
      "bpm": 116,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "939790d7-93c5-4eca-a68d-e27eb113ca00"
    },
    {
      "sectionId": "e2234afd-d33d-4382-b157-f958682af16a",
      "bpm": 84,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "96c5ffa0-1a06-4588-aa22-ee46d6f1a77b"
    },
    {
      "sectionId": "d1dc2df0-dc04-496f-83b2-f43dc47b876e",
      "bpm": 76,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "96c5ffa0-1a06-4588-aa22-ee46d6f1a77b"
    },
    {
      "sectionId": "839f73cc-2025-4efb-8643-992374131b87",
      "bpm": 84,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "96c5ffa0-1a06-4588-aa22-ee46d6f1a77b"
    },
    {
      "sectionId": "38cc879a-044a-43c0-9c03-066e96cb1810",
      "bpm": 76,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "96c5ffa0-1a06-4588-aa22-ee46d6f1a77b"
    },
    {
      "sectionId": "f8c369f9-fc13-436c-81d3-7fc384d59188",
      "bpm": 116,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "3a23a4be-84b7-463f-a5ce-47d6f018f8ec"
    },
    {
      "sectionId": "96b54b86-f753-4323-9ee9-456dd15902ca",
      "bpm": 138,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "07c24791-2029-4d60-bbd8-beeaa2525012"
    },
    {
      "sectionId": "5f6028a3-e63a-4e8f-8a5c-3958590b22ca",
      "bpm": 76,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "4fa21635-3e73-4994-a984-2fb5aec4d484"
    },
    {
      "sectionId": "bc88b1dc-fa3e-4807-bdcc-b58294b2118f",
      "bpm": 72,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "8288069f-4002-4fbe-9717-164c6c911d1f"
    },
    {
      "sectionId": "eb5607fc-8dd3-4922-9bcd-b677d63cd126",
      "bpm": 96,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "bdfd8488-f53e-4d42-b30f-d7c8a3d727ea"
    },
    {
      "sectionId": "e719a427-5b7e-4cd7-96d3-80fca607bb12",
      "bpm": 100,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "bdfd8488-f53e-4d42-b30f-d7c8a3d727ea"
    },
    {
      "sectionId": "201e4016-538e-4f68-a55d-7cde3a80d13d",
      "bpm": 84,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "bdfd8488-f53e-4d42-b30f-d7c8a3d727ea"
    },
    {
      "sectionId": "500f35bd-c36c-4aa5-ab08-5c5be9e89d4f",
      "bpm": 66,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "bdfd8488-f53e-4d42-b30f-d7c8a3d727ea"
    },
    {
      "sectionId": "64b6dfbd-7c14-4dc5-bd0c-5598e0f1df92",
      "bpm": 80,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "9cc2435b-9a8f-43aa-ac56-cfa52187d0b9"
    },
    {
      "sectionId": "1847584b-80d2-4e39-b3f2-ca5076dcdd8e",
      "bpm": 88,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "f5fcea64-a606-448d-b0f4-94406cf0880f"
    },
    {
      "sectionId": "46295889-1c03-4344-b15f-7b632145f14a",
      "bpm": 66,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "eb66686d-bc63-43f3-aa74-c13ba2adaf36"
    },
    {
      "sectionId": "f3ec8f08-970b-4998-b67a-4c3d24e3fe9d",
      "bpm": 84,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "3cc1496e-a244-413a-a97c-d24bbdef1fb0"
    },
    {
      "sectionId": "bdd82a93-8636-4d93-83a3-4d34d1ae6315",
      "bpm": 92,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "3cc1496e-a244-413a-a97c-d24bbdef1fb0"
    },
    {
      "sectionId": "788579ae-d4fd-453b-9544-99e4a5cf30bb",
      "bpm": 84,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "3cc1496e-a244-413a-a97c-d24bbdef1fb0"
    },
    {
      "sectionId": "d5538d3d-1a99-401e-b32d-583f9fda47d0",
      "bpm": 152,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "6872eca0-227b-456e-aeec-102d12e44277"
    },
    {
      "sectionId": "66fb30e3-34fc-44d0-9ce7-ff849947d0df",
      "bpm": 92,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "7e6ef633-4a9f-4106-832e-585a1f62e934"
    },
    {
      "sectionId": "f82ef879-e76e-4c07-bc10-bffa54176c89",
      "bpm": 52,
      "comment": "",
      "beatUnit": "DOTTED_HALF",
      "noMM": false,
      "pieceVersionId": "148e943a-ad1e-40ad-8e70-e83b82a93438"
    },
    {
      "sectionId": "0b03fc83-01a2-4af9-91e1-42986a205c27",
      "bpm": 96,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "dc446936-f669-4be6-a0c7-c8d1da9bbe2c"
    },
    {
      "sectionId": "31289a07-de15-4be6-a820-c857327fee75",
      "bpm": 116,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "9bccc087-d93c-41d9-beb9-f24b07ce70fc"
    },
    {
      "sectionId": "66ffb47b-1fd8-455c-ac29-59d3f25beff4",
      "bpm": 76,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "0ee6e262-e213-4b28-8204-896c6a3941d1"
    },
    {
      "sectionId": "73b6567f-a430-4620-b600-0754496c22cb",
      "bpm": 132,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "faffd47b-2ea9-4b61-a17c-509ee129fbf3"
    },
    {
      "sectionId": "f850ccff-2890-4e49-ba23-0e0f9b1c1505",
      "bpm": 69,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "22d1874e-d368-4ce6-a5b9-74886deae328"
    },
    {
      "sectionId": "c9d952a2-bb59-490e-82cc-1bd1a03ca183",
      "bpm": 92,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "e12ad86b-3743-423c-b0dc-508f49bdea4b"
    },
    {
      "sectionId": "3839fccd-4110-4ed7-a342-06d926ff3e63",
      "bpm": 120,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "07c9d82a-b195-454c-ac2d-e298938f0762"
    },
    {
      "sectionId": "75fa943d-d744-4c56-8e50-874da74a8572",
      "noMM": true,
      "pieceVersionId": "07c9d82a-b195-454c-ac2d-e298938f0762"
    },
    {
      "sectionId": "08b3bd3f-a111-4bac-b05d-ab2d9705ca84",
      "bpm": 132,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "7524098e-b1ef-4b37-946d-79d1da088e94"
    },
    {
      "sectionId": "1a765776-009a-45a2-8a93-acbeb8f299d4",
      "noMM": true,
      "pieceVersionId": "7524098e-b1ef-4b37-946d-79d1da088e94"
    },
    {
      "sectionId": "24a4d931-be09-4d39-9fc2-e668041a20ce",
      "bpm": 72,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "49058499-5ee5-4fa0-9668-182181e4f783"
    },
    {
      "sectionId": "84ba768e-b321-4d2a-ada2-7272df60f832",
      "bpm": 112,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "49058499-5ee5-4fa0-9668-182181e4f783"
    },
    {
      "sectionId": "5601cecc-9b0d-4573-955a-647d61eb2097",
      "bpm": 96,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "e4685096-ab28-4ccc-8789-83e41cc6de07"
    },
    {
      "sectionId": "7644e93c-eff4-4b2b-998f-37c63dac2b40",
      "bpm": 104,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "9789a09f-9f2d-4929-866d-a77c2916c5ac"
    },
    {
      "sectionId": "348f9d2d-4c3f-4852-8728-2df4c2a00d7a",
      "bpm": 108,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "cdcc1a8c-8b12-4bb6-8b2f-01e021794eda"
    },
    {
      "sectionId": "d8ccec26-2b65-4f54-b78a-b23d3622e6a5",
      "bpm": 88,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "00b287a6-a80f-4f31-b69c-de9ead97ce23"
    },
    {
      "sectionId": "60be35fd-909d-47d9-8e73-77109b676030",
      "bpm": 80,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "67feeb40-48a8-4c49-a5f2-9cedc198dfed"
    },
    {
      "sectionId": "a8215409-6b86-4238-93d6-6d2d9451b5a6",
      "noMM": true,
      "pieceVersionId": "67feeb40-48a8-4c49-a5f2-9cedc198dfed"
    },
    {
      "sectionId": "6cad1dd7-6fa8-4b36-a7b3-660381a758bb",
      "bpm": 72,
      "comment": "",
      "beatUnit": "HALF",
      "noMM": false,
      "pieceVersionId": "0ce0ef09-63ef-4076-9646-a34b21d9246a"
    },
    {
      "sectionId": "d63a6cdd-5c9c-4a3e-bab8-cc8487d4ab21",
      "bpm": 100,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "1197ead5-e674-4ef7-a772-a61e1242e1e3"
    },
    {
      "sectionId": "615936e4-9472-4f1f-8f09-3db0ff12b2eb",
      "bpm": 96,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "7ed1bb26-8620-4240-aaa4-0a7be615fb40"
    },
    {
      "sectionId": "34232553-baac-4b47-be11-103d194bc93d",
      "bpm": 63,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "d6517928-16e1-4fea-b73c-884480a3f92a"
    },
    {
      "sectionId": "de5085d2-3acd-42b2-8050-c6e76f875e8e",
      "bpm": 69,
      "comment": "",
      "beatUnit": "QUARTER",
      "noMM": false,
      "pieceVersionId": "065c6ad3-5648-49ea-b57d-658495a7a161"
    }
  ],
  "organizations": [
    {
      "id": "7ef5aacf-7302-48a4-b858-60600aeaf71a",
      "name": "Jos. Aibl Verlag"
    }
  ],
  "persons": [
    {
      "id": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "firstName": "Hans",
      "lastName": "von Bülow",
      "birthYear": 1830,
      "deathYear": 1894
    }
  ],
  "pieces": [
    {
      "title": "Pantomime",
      "nickname": "Todtenopfer",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "5b35b0e3-496e-482d-9714-a9c32acb0d67",
      "isNew": true,
      "collectionId": "a8b37563-4812-4c73-b6b5-e0ec15ce1b8a",
      "collectionRank": 1
    },
    {
      "title": "Sarabande",
      "nickname": "Reigen der Seligen",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "687134b2-4a59-452b-8809-901bfcbcf193",
      "isNew": true,
      "collectionId": "a8b37563-4812-4c73-b6b5-e0ec15ce1b8a",
      "collectionRank": 2
    },
    {
      "title": "Arie",
      "nickname": "Eurydikes Schattenwandlung",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "1ec790d7-1e0f-4daa-b02b-668b84b9d0a7",
      "isNew": true,
      "collectionId": "a8b37563-4812-4c73-b6b5-e0ec15ce1b8a",
      "collectionRank": 3
    },
    {
      "title": "Bourrée",
      "nickname": "Chortanz",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "3237c86e-b8e5-47d9-a356-31eceddcfe91",
      "isNew": true,
      "collectionId": "a8b37563-4812-4c73-b6b5-e0ec15ce1b8a",
      "collectionRank": 4
    },
    {
      "title": "Menuetto",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "bfdef6d9-2c5b-4971-9887-ad84b5dc7607",
      "isNew": true,
      "collectionId": "a8b37563-4812-4c73-b6b5-e0ec15ce1b8a",
      "collectionRank": 5
    },
    {
      "title": "Gigue",
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "yearOfComposition": null,
      "id": "8874cd37-29ee-405c-80b4-dfdab2537751",
      "isNew": true,
      "collectionId": "a8b37563-4812-4c73-b6b5-e0ec15ce1b8a",
      "collectionRank": 6
    },
    {
      "title": "Gavotte",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "e7d23ff1-4f92-436e-baf7-7d9fe0903cd6",
      "isNew": true,
      "collectionId": "a8b37563-4812-4c73-b6b5-e0ec15ce1b8a",
      "collectionRank": 7
    },
    {
      "title": "Hirtentanz",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "c9ec44c0-7ceb-498d-a5ed-6db279e875c5",
      "isNew": true,
      "collectionId": "a8b37563-4812-4c73-b6b5-e0ec15ce1b8a",
      "collectionRank": 8
    },
    {
      "title": "Chaconne",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "0622ab61-eb28-4528-ae9f-130113676113",
      "isNew": true,
      "collectionId": "a8b37563-4812-4c73-b6b5-e0ec15ce1b8a",
      "collectionRank": 9
    },
    {
      "title": "Priestermarsch",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "efb7346a-db1c-401e-ad39-c65e3f854582",
      "isNew": true,
      "collectionId": "4e559a73-0822-4196-995a-0ea60922edfb",
      "collectionRank": 1
    },
    {
      "title": "Opferhandlung",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "d2d3a936-95b9-48b0-88b2-ee004f3fdeb5",
      "isNew": true,
      "collectionId": "4e559a73-0822-4196-995a-0ea60922edfb",
      "collectionRank": 2
    },
    {
      "title": "Divertissement",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "329a4774-8a4d-4ecf-9b60-ef405a85b0d9",
      "isNew": true,
      "collectionId": "4e559a73-0822-4196-995a-0ea60922edfb",
      "collectionRank": 3
    },
    {
      "title": "Gigue",
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "yearOfComposition": 1879,
      "id": "daefd9fc-56a7-4f88-8454-d223062b9766",
      "isNew": true,
      "collectionId": "4e559a73-0822-4196-995a-0ea60922edfb",
      "collectionRank": 4
    },
    {
      "title": "Festmarsch",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "ea47e2af-65fd-4e8e-b7bf-0574eadb4228",
      "isNew": true,
      "collectionId": "4e559a73-0822-4196-995a-0ea60922edfb",
      "collectionRank": 5
    },
    {
      "title": "Sarabande",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "3844a4ce-ea85-46ae-89f7-2746415f6af8",
      "isNew": true,
      "collectionId": "4e559a73-0822-4196-995a-0ea60922edfb",
      "collectionRank": 6
    },
    {
      "title": "Gavotte",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "df0a2b56-651c-45a4-8fc8-8a013aba84ff",
      "isNew": true,
      "collectionId": "4e559a73-0822-4196-995a-0ea60922edfb",
      "collectionRank": 7
    },
    {
      "title": "Waffentanz",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "eeba7d36-e6db-49a1-ba66-1a5c4c4e5905",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 1
    },
    {
      "title": "Sarabande",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "b0213468-25ca-498f-b193-f65cc4225daf",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 2
    },
    {
      "title": "Menuetto",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "edae7e47-0a4b-4670-83ae-f59105a9da4a",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 3
    },
    {
      "title": "Anglaise",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "5dc771f3-ecc2-4bc6-bbb1-14787379d5c4",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 4
    },
    {
      "title": "Passepied",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "0132f30d-b8f9-4623-b3cd-8fbc6edd0730",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 5
    },
    {
      "title": "Marsch",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "306a325c-c049-44db-93b7-00f7334ca2a5",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 6
    },
    {
      "title": "Passepied",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "d287a665-a3c4-480d-91ab-d4f931300f29",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 7
    },
    {
      "title": "Gavotte",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "12a2aeab-531f-44a2-90d8-0719f4a1c784",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 8
    },
    {
      "title": "Tambourin",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "65605845-ae61-4a76-8049-04ea75505a52",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 9
    },
    {
      "title": "Menuetto",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "a9ba77e8-8d15-4937-a2c4-ace8e3a103f3",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 10
    },
    {
      "title": "Sklaventanz",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "8c08f786-e2d0-408e-8efd-37673abb98c6",
      "isNew": true,
      "collectionId": "60ac6fb4-df24-416f-a007-febf3718e4ca",
      "collectionRank": 11
    },
    {
      "title": "Huldigungsmarsch",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "5068e008-75ef-48ed-a7b4-5a7e0ae6d0d6",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 1
    },
    {
      "title": "Pavane",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "d6acf428-be06-4a31-beaf-965e02d058df",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 2
    },
    {
      "title": "Tanz mit Chor",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "1f05e5c3-dfd3-4d66-af07-0f959f681c85",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 3
    },
    {
      "title": "Menuetto pastorale",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "1d2ef055-878a-43d2-893d-fc82586b26d3",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 4
    },
    {
      "title": "Gavotte",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "b654c07c-748e-431e-a5e4-61f3c4306d64",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 5
    },
    {
      "title": "Furientanz",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "f5ed1e1a-855d-411c-84ca-e86fed66d75c",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 6
    },
    {
      "title": "Bourrée",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "3b1a77da-e9ac-4d3c-bcd4-81871b5519fb",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 7
    },
    {
      "title": "Tanz mit Chor",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "fa1183b2-0517-40bc-8961-6fd2999d8ea5",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 8
    },
    {
      "title": "Pavane",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "9917a454-6a24-4e4b-b5c3-a36069e09e8e",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 9
    },
    {
      "title": "Sicilienne",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "5eefb47f-b664-489d-a633-50b12c0ff48c",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 10
    },
    {
      "title": "Sarabande",
      "yearOfComposition": 1879,
      "composerId": "63833d92-8c49-4ef6-ae87-f8c3d3e2f6a2",
      "id": "890e4497-d47a-4480-bdf8-3c2c7a78242e",
      "isNew": true,
      "collectionId": "2d66b87e-fb24-465d-bb4c-6482193c3080",
      "collectionRank": 11
    }
  ],
  "pieceVersions": [
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "72e932d4-3870-4882-a92b-50f07a3565ef",
          "rank": 1,
          "key": "B_FLAT_MINOR",
          "sections": [
            {
              "id": "256a219f-278e-4ed8-b6dd-67ff861b1849",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 3,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 18,
              "comment": "Ornamental: final bar 3rd to last system, trill requires min 6 notes",
              "tempoIndication": {
                "id": "aae24898-c465-496c-aac7-fcf8c15e78c2",
                "text": "Andante maestoso"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "5b35b0e3-496e-482d-9714-a9c32acb0d67",
      "id": "6c6b3e6e-1beb-410f-86c6-1f23e458905b",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "87b5215a-6cd9-45b3-9a1a-0099843a8302",
          "rank": 1,
          "key": "F_MAJOR",
          "sections": [
            {
              "id": "d02368f6-b504-4815-91e2-7262d45c89cf",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 3,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 18,
              "comment": "Ornamental: second bar in 2nd to last system, trill required min 6 notes",
              "tempoIndication": {
                "id": "8cd8f2c3-9c72-4a9b-861f-b18bf77c5574",
                "text": "Andante espressivo"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "687134b2-4a59-452b-8809-901bfcbcf193",
      "id": "5a26930f-e924-4d09-81aa-a2ed254a2c65",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "01e283ea-f7ed-4e83-a9c1-ce2aeec6aa4e",
          "rank": 1,
          "key": "D_MINOR",
          "sections": [
            {
              "id": "27e35ab4-e2f3-4619-94da-4c54aeaa06c2",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 12,
              "isFastestStructuralNoteBelCanto": false,
              "fastestRepeatedNotesPerBar": 12,
              "fastestOrnamentalNotesPerBar": 36,
              "tempoIndication": {
                "id": "9b4691ea-431a-4bd8-9388-3717b389049c",
                "text": "Lento"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "1ec790d7-1e0f-4daa-b02b-668b84b9d0a7",
      "id": "0d993bf7-0de2-4389-b35e-4722834c009d",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "8c6b3282-5712-482d-a5be-d347e388e811",
          "rank": 1,
          "key": "D_MAJOR",
          "sections": [
            {
              "id": "29961b5d-6bd9-4dee-ad29-be9503a8c9e2",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 4,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "666db109-0966-4d55-99f1-162ac94c11f5",
                "text": "Allegretto grazioso"
              },
              "rank": 1
            },
            {
              "id": "e97231ba-cfea-43f6-ba24-531bed2e5347",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 8,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "8fb50b67-1e67-49c0-8bbc-146fb4189735",
                "text": "Poco più mosso"
              },
              "rank": 2
            }
          ]
        }
      ],
      "pieceId": "3237c86e-b8e5-47d9-a356-31eceddcfe91",
      "id": "f4939150-4802-463c-9087-0bc134bc631f",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "c90330df-5743-4090-9d76-16c907ea3fa6",
          "rank": 1,
          "key": "B_FLAT_MAJOR",
          "sections": [
            {
              "id": "f5ca8643-db49-4dea-951c-de3fe5942231",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 12,
              "tempoIndication": {
                "id": "69d0e06a-dba1-4b4c-9944-cfd69d861ac8",
                "text": "Andante grazioso"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "bfdef6d9-2c5b-4971-9887-ad84b5dc7607",
      "id": "8fd2680a-7bec-46b0-9005-b547a80d9f59",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "7ff7dcce-56a5-4e73-a332-91d8226a9e41",
          "rank": 1,
          "key": "A_MAJOR",
          "sections": [
            {
              "id": "e346448c-5a2a-4550-ba61-06730692a0bb",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 3,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 12,
              "tempoIndication": {
                "id": "2fadca09-f577-430a-840e-25f9b5ce16e4",
                "text": "Allegro"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "8874cd37-29ee-405c-80b4-dfdab2537751",
      "id": "939790d7-93c5-4eca-a68d-e27eb113ca00",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "27bc2afd-70d0-4eee-9f50-ceed16dfb086",
          "rank": 1,
          "key": "A_MINOR",
          "sections": [
            {
              "id": "e2234afd-d33d-4382-b157-f958682af16a",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 8,
              "tempoIndication": {
                "id": "2fadca09-f577-430a-840e-25f9b5ce16e4",
                "text": "Allegro"
              },
              "rank": 1
            },
            {
              "id": "d1dc2df0-dc04-496f-83b2-f43dc47b876e",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 8,
              "tempoIndication": {
                "id": "6a16e457-6aeb-4802-a59e-4ce3b91cafa2",
                "text": "-- None --"
              },
              "rank": 2
            },
            {
              "id": "839f73cc-2025-4efb-8643-992374131b87",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 8,
              "tempoIndication": {
                "id": "6a16e457-6aeb-4802-a59e-4ce3b91cafa2",
                "text": "-- None --"
              },
              "rank": 3
            },
            {
              "id": "38cc879a-044a-43c0-9c03-066e96cb1810",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 8,
              "tempoIndication": {
                "id": "6a16e457-6aeb-4802-a59e-4ce3b91cafa2",
                "text": "-- None --"
              },
              "rank": 4
            }
          ]
        }
      ],
      "pieceId": "e7d23ff1-4f92-436e-baf7-7d9fe0903cd6",
      "id": "96c5ffa0-1a06-4588-aa22-ee46d6f1a77b",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "23b5e1e3-45b1-49e0-871a-bc5847d35eb1",
          "rank": 1,
          "key": "D_MAJOR",
          "sections": [
            {
              "id": "f8c369f9-fc13-436c-81d3-7fc384d59188",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 12,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 6,
              "tempoIndication": {
                "id": "2f0a179e-bc46-4b8f-a4e6-be3f64e7935b",
                "text": "Moderato"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "c9ec44c0-7ceb-498d-a5ed-6db279e875c5",
      "id": "3a23a4be-84b7-463f-a5ce-47d6f018f8ec",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "113a6f7a-4deb-41cc-8000-bc051bded1f5",
          "rank": 1,
          "key": "D_MAJOR",
          "sections": [
            {
              "id": "96b54b86-f753-4323-9ee9-456dd15902ca",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 12,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 12,
              "fastestOrnamentalNotesPerBar": 24,
              "comment": "Ornamental: 2 note arpeggios on 16th note",
              "tempoIndication": {
                "id": "5465034c-b59d-4553-93bc-eebd40500ddf",
                "text": "Allegro vivace"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "0622ab61-eb28-4528-ae9f-130113676113",
      "id": "07c24791-2029-4d60-bbd8-beeaa2525012",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "3973f5c1-06f5-4086-ae82-a459c87ca78c",
          "rank": 1,
          "key": "G_MAJOR",
          "sections": [
            {
              "id": "5f6028a3-e63a-4e8f-8a5c-3958590b22ca",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 4,
              "isFastestStructuralNoteBelCanto": false,
              "fastestRepeatedNotesPerBar": 4,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "1bfdf7ab-fe50-4c6d-bffc-b0e240644da3",
                "text": "Moderato dolce"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "efb7346a-db1c-401e-ad39-c65e3f854582",
      "id": "4fa21635-3e73-4994-a984-2fb5aec4d484",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "0f21f3b8-d659-49e2-a101-a877f9924bc1",
          "rank": 1,
          "key": "C_MINOR",
          "sections": [
            {
              "id": "bc88b1dc-fa3e-4807-bdcc-b58294b2118f",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 12,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 12,
              "fastestOrnamentalNotesPerBar": 24,
              "tempoIndication": {
                "id": "2f0a179e-bc46-4b8f-a4e6-be3f64e7935b",
                "text": "Moderato"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "d2d3a936-95b9-48b0-88b2-ee004f3fdeb5",
      "id": "8288069f-4002-4fbe-9717-164c6c911d1f",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "2f80e739-d9dd-48d2-bf93-22215d25ecd4",
          "rank": 1,
          "key": "E_MINOR",
          "sections": [
            {
              "id": "eb5607fc-8dd3-4922-9bcd-b677d63cd126",
              "metreNumerator": 2,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 8,
              "fastestOrnamentalNotesPerBar": 16,
              "comment": "Ornamental: 2 note arpeggios on 16th note",
              "tempoIndication": {
                "id": "666db109-0966-4d55-99f1-162ac94c11f5",
                "text": "Allegretto grazioso"
              },
              "rank": 1
            }
          ]
        },
        {
          "id": "c0f8b612-44bd-49f2-874f-3c8325e2ebe6",
          "rank": 2,
          "key": "G_MAJOR",
          "sections": [
            {
              "id": "e719a427-5b7e-4cd7-96d3-80fca607bb12",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 4,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "581e9953-9703-44e7-a3fc-ddeb83374620",
                "text": "Allegro con brio"
              },
              "rank": 1
            }
          ]
        },
        {
          "id": "429ef5fb-c03c-43ee-a4c0-be47c8c647dc",
          "rank": 3,
          "key": "G_MINOR",
          "sections": [
            {
              "id": "201e4016-538e-4f68-a55d-7cde3a80d13d",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 12,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 12,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 18,
              "comment": "Ornamental: 3 note arpeggios on 8th note",
              "tempoIndication": {
                "id": "91908a41-27aa-4509-9419-cb2d1fbcc01e",
                "text": "Andante moderato"
              },
              "rank": 1
            }
          ]
        },
        {
          "id": "53ce0510-badc-4147-ab94-7a02ffbc9653",
          "rank": 4,
          "key": "G_MAJOR",
          "sections": [
            {
              "id": "500f35bd-c36c-4aa5-ab08-5c5be9e89d4f",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 12,
              "tempoIndication": {
                "id": "5465034c-b59d-4553-93bc-eebd40500ddf",
                "text": "Allegro vivace"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "329a4774-8a4d-4ecf-9b60-ef405a85b0d9",
      "id": "bdfd8488-f53e-4d42-b30f-d7c8a3d727ea",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "f5facf40-4a29-4ed4-9e41-9c7ca123a0df",
          "rank": 1,
          "key": "G_MAJOR",
          "sections": [
            {
              "id": "64b6dfbd-7c14-4dc5-bd0c-5598e0f1df92",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 12,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 12,
              "fastestRepeatedNotesPerBar": 4,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "93c69550-ab3f-40dd-b39c-77e91bf858b0",
                "text": "Andante con moto"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "daefd9fc-56a7-4f88-8454-d223062b9766",
      "id": "9cc2435b-9a8f-43aa-ac56-cfa52187d0b9",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "ae8e3af5-8333-439f-81ed-db23fb102a68",
          "rank": 1,
          "key": "D_MAJOR",
          "sections": [
            {
              "id": "1847584b-80d2-4e39-b3f2-ca5076dcdd8e",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestRepeatedNotesPerBar": 8,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "3d9f7a22-b600-40e1-8d99-d68edb065f00",
                "text": "Allegro brillante"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "ea47e2af-65fd-4e8e-b7bf-0574eadb4228",
      "id": "f5fcea64-a606-448d-b0f4-94406cf0880f",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "5b58d524-675b-4d2d-9cb2-218c0234782b",
          "rank": 1,
          "key": "A_MAJOR",
          "sections": [
            {
              "id": "46295889-1c03-4344-b15f-7b632145f14a",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 12,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 12,
              "fastestRepeatedNotesPerBar": 12,
              "fastestOrnamentalNotesPerBar": 36,
              "tempoIndication": {
                "id": "fb18cfa3-a2c2-4eba-81ec-0bb9c55ebfe6",
                "text": "Andantino grazioso"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "3844a4ce-ea85-46ae-89f7-2746415f6af8",
      "id": "eb66686d-bc63-43f3-aa74-c13ba2adaf36",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "0bf836e0-881b-48f9-9c69-ff4312be74ee",
          "rank": 1,
          "key": "A_MAJOR",
          "sections": [
            {
              "id": "f3ec8f08-970b-4998-b67a-4c3d24e3fe9d",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 4,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "550e960f-3540-43a1-b34b-1f82d2e06273",
                "text": "Allegro leggiero"
              },
              "rank": 1
            },
            {
              "id": "bdd82a93-8636-4d93-83a3-4d34d1ae6315",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "6a16e457-6aeb-4802-a59e-4ce3b91cafa2",
                "text": "-- None --"
              },
              "rank": 2
            },
            {
              "id": "788579ae-d4fd-453b-9544-99e4a5cf30bb",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 4,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "6a16e457-6aeb-4802-a59e-4ce3b91cafa2",
                "text": "-- None --"
              },
              "rank": 3
            }
          ]
        }
      ],
      "pieceId": "df0a2b56-651c-45a4-8fc8-8a013aba84ff",
      "id": "3cc1496e-a244-413a-a97c-d24bbdef1fb0",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "8c9882b2-b003-4915-a915-407d3aca75a8",
          "rank": 1,
          "key": "D_MAJOR",
          "sections": [
            {
              "id": "d5538d3d-1a99-401e-b32d-583f9fda47d0",
              "metreNumerator": 2,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 4,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 4,
              "fastestOrnamentalNotesPerBar": 12,
              "comment": "Italian tempo misprint? (Allegro giocoso?)",
              "tempoIndication": {
                "id": "59c9d6a1-a900-4892-887f-46a49a34e7fd",
                "text": "Allegro giojoso"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "eeba7d36-e6db-49a1-ba66-1a5c4c4e5905",
      "id": "6872eca0-227b-456e-aeec-102d12e44277",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "1db40051-def2-41ab-a86b-b918960fe2dc",
          "rank": 1,
          "key": "D_MINOR",
          "sections": [
            {
              "id": "66fb30e3-34fc-44d0-9ce7-ff849947d0df",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestRepeatedNotesPerBar": 12,
              "fastestOrnamentalNotesPerBar": 18,
              "comment": "Ornamental: penultimate bar",
              "tempoIndication": {
                "id": "1891528c-091e-4d2e-903f-b895bfe5d4f1",
                "text": "Grave sostenuto"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "b0213468-25ca-498f-b193-f65cc4225daf",
      "id": "7e6ef633-4a9f-4106-832e-585a1f62e934",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "88eba44b-0e3f-4a2d-9155-e818f5dedc61",
          "rank": 1,
          "key": "D_MAJOR",
          "sections": [
            {
              "id": "f82ef879-e76e-4c07-bc10-bffa54176c89",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 12,
              "tempoIndication": {
                "id": "68b97adb-f73f-40ab-8aac-6eb184e3adfc",
                "text": "Allegretto"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "edae7e47-0a4b-4670-83ae-f59105a9da4a",
      "id": "148e943a-ad1e-40ad-8e70-e83b82a93438",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "78274c01-555c-4a5f-8cb4-bb494c97d2a8",
          "rank": 1,
          "key": "A_MAJOR",
          "sections": [
            {
              "id": "0b03fc83-01a2-4af9-91e1-42986a205c27",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 8,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "5465034c-b59d-4553-93bc-eebd40500ddf",
                "text": "Allegro vivace"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "5dc771f3-ecc2-4bc6-bbb1-14787379d5c4",
      "id": "dc446936-f669-4be6-a0c7-c8d1da9bbe2c",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "46bfeda5-5a97-43e9-b1d1-89438996f6bc",
          "rank": 1,
          "key": "D_MAJOR",
          "sections": [
            {
              "id": "31289a07-de15-4be6-a820-c857327fee75",
              "metreNumerator": 3,
              "metreDenominator": 8,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 12,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 18,
              "comment": "Time signature in score is wrong (correct one entered); Ornamental: 3 note arpeggios on 8th note",
              "tempoIndication": {
                "id": "68b97adb-f73f-40ab-8aac-6eb184e3adfc",
                "text": "Allegretto"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "0132f30d-b8f9-4623-b3cd-8fbc6edd0730",
      "id": "9bccc087-d93c-41d9-beb9-f24b07ce70fc",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "68cd046e-23cf-4b2f-880c-0846dd182c1a",
          "rank": 1,
          "key": "G_MAJOR",
          "sections": [
            {
              "id": "66ffb47b-1fd8-455c-ac29-59d3f25beff4",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 4,
              "isFastestStructuralNoteBelCanto": false,
              "fastestRepeatedNotesPerBar": 8,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "89e21c7b-da93-466d-9b98-1f477c2fd83c",
                "text": "Maestoso"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "306a325c-c049-44db-93b7-00f7334ca2a5",
      "id": "0ee6e262-e213-4b28-8204-896c6a3941d1",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "e533b426-af53-43d0-aa9c-4f2cf207ffc4",
          "rank": 1,
          "key": "C_MAJOR",
          "sections": [
            {
              "id": "73b6567f-a430-4620-b600-0754496c22cb",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 12,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 6,
              "comment": "Structural: 2nd page, 2nd system has 10 note scale in 16th notes",
              "tempoIndication": {
                "id": "bd52695e-1bff-47e6-9dcb-30b8d0d9c30a",
                "text": "Moderato grazioso"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "d287a665-a3c4-480d-91ab-d4f931300f29",
      "id": "faffd47b-2ea9-4b61-a17c-509ee129fbf3",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "5af9fa84-e0c9-46ec-991f-6d323b973fb9",
          "rank": 1,
          "key": "C_MAJOR",
          "sections": [
            {
              "id": "f850ccff-2890-4e49-ba23-0e0f9b1c1505",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 8,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "87677e1b-3ed5-435c-b4c2-6b8f2479d375",
                "text": "Andantino cantabile"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "12a2aeab-531f-44a2-90d8-0719f4a1c784",
      "id": "22d1874e-d368-4ce6-a5b9-74886deae328",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "a6345218-edf3-4451-9e74-55f2a3527247",
          "rank": 1,
          "key": "D_MAJOR",
          "sections": [
            {
              "id": "c9d952a2-bb59-490e-82cc-1bd1a03ca183",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 8,
              "tempoIndication": {
                "id": "61dc44d6-1b3b-4e5d-9440-9d59e45516ce",
                "text": "Vivace"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "65605845-ae61-4a76-8049-04ea75505a52",
      "id": "e12ad86b-3743-423c-b0dc-508f49bdea4b",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "9843042b-a64d-4e7e-883d-d75cebc635d5",
          "rank": 1,
          "key": "G_MAJOR",
          "sections": [
            {
              "id": "3839fccd-4110-4ed7-a342-06d926ff3e63",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 12,
              "fastestOrnamentalNotesPerBar": 12,
              "tempoIndication": {
                "id": "68b97adb-f73f-40ab-8aac-6eb184e3adfc",
                "text": "Allegretto"
              },
              "rank": 1
            },
            {
              "id": "75fa943d-d744-4c56-8e50-874da74a8572",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 12,
              "fastestOrnamentalNotesPerBar": 12,
              "tempoIndication": {
                "id": "1ad5d3da-1cf7-467c-8925-2085c1033871",
                "text": "Poco piu lento"
              },
              "rank": 2
            }
          ]
        }
      ],
      "pieceId": "a9ba77e8-8d15-4937-a2c4-ace8e3a103f3",
      "id": "07c9d82a-b195-454c-ac2d-e298938f0762",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "43fb255c-8fc6-49a5-b9c7-f7926fc1b221",
          "rank": 1,
          "key": "F_MAJOR",
          "sections": [
            {
              "id": "08b3bd3f-a111-4bac-b05d-ab2d9705ca84",
              "metreNumerator": 2,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 4,
              "tempoIndication": {
                "id": "3ecc1cb7-5000-405d-ac02-37071647ff0e",
                "text": "Presto"
              },
              "rank": 1
            },
            {
              "id": "1a765776-009a-45a2-8a93-acbeb8f299d4",
              "metreNumerator": 2,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 4,
              "fastestRepeatedNotesPerBar": 4,
              "tempoIndication": {
                "id": "d9e2458c-3ab9-4905-b289-24402c7492af",
                "text": "Piu Presto"
              },
              "rank": 2
            }
          ]
        }
      ],
      "pieceId": "8c08f786-e2d0-408e-8efd-37673abb98c6",
      "id": "7524098e-b1ef-4b37-946d-79d1da088e94",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "609fd780-ac0d-4ccd-88bd-cd57e7ed45a8",
          "rank": 1,
          "key": "C_MAJOR",
          "sections": [
            {
              "id": "24a4d931-be09-4d39-9fc2-e668041a20ce",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 4,
              "tempoIndication": {
                "id": "89e21c7b-da93-466d-9b98-1f477c2fd83c",
                "text": "Maestoso"
              },
              "rank": 1
            },
            {
              "id": "84ba768e-b321-4d2a-ada2-7272df60f832",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 6,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 12,
              "comment": "Ornamental: 2 note arpeggios on 8th note",
              "tempoIndication": {
                "id": "2f0a179e-bc46-4b8f-a4e6-be3f64e7935b",
                "text": "Moderato"
              },
              "rank": 2
            }
          ]
        }
      ],
      "pieceId": "5068e008-75ef-48ed-a7b4-5a7e0ae6d0d6",
      "id": "49058499-5ee5-4fa0-9668-182181e4f783",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "c451cb29-e3b2-4cac-9eab-163401c012e8",
          "rank": 1,
          "key": "F_MAJOR",
          "sections": [
            {
              "id": "5601cecc-9b0d-4573-955a-647d61eb2097",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 16,
              "fastestOrnamentalNotesPerBar": 16,
              "tempoIndication": {
                "id": "89e21c7b-da93-466d-9b98-1f477c2fd83c",
                "text": "Maestoso"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "d6acf428-be06-4a31-beaf-965e02d058df",
      "id": "e4685096-ab28-4ccc-8789-83e41cc6de07",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "8f164470-02e3-4b09-85c9-e967b288eccb",
          "rank": 1,
          "key": "B_FLAT_MAJOR",
          "sections": [
            {
              "id": "7644e93c-eff4-4b2b-998f-37c63dac2b40",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 16,
              "isFastestStructuralNoteBelCanto": false,
              "fastestRepeatedNotesPerBar": 16,
              "tempoIndication": {
                "id": "68b97adb-f73f-40ab-8aac-6eb184e3adfc",
                "text": "Allegretto"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "1f05e5c3-dfd3-4d66-af07-0f959f681c85",
      "id": "9789a09f-9f2d-4929-866d-a77c2916c5ac",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "6a98a1d4-3ceb-4a9b-abd1-5081063b69a2",
          "rank": 1,
          "key": "C_MAJOR",
          "sections": [
            {
              "id": "348f9d2d-4c3f-4852-8728-2df4c2a00d7a",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 3,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 9,
              "comment": "Ornamental: 3 note arpeggios on quarter note",
              "tempoIndication": {
                "id": "2f8c16fc-f22a-4c67-be52-bdfd65b6793e",
                "text": "Moderato assai"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "1d2ef055-878a-43d2-893d-fc82586b26d3",
      "id": "cdcc1a8c-8b12-4bb6-8b2f-01e021794eda",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "f0d65d0d-a40c-44d5-81b3-cec86e021974",
          "rank": 1,
          "key": "C_MAJOR",
          "sections": [
            {
              "id": "d8ccec26-2b65-4f54-b78a-b23d3622e6a5",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 8,
              "tempoIndication": {
                "id": "581e9953-9703-44e7-a3fc-ddeb83374620",
                "text": "Allegro con brio"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "b654c07c-748e-431e-a5e4-61f3c4306d64",
      "id": "00b287a6-a80f-4f31-b69c-de9ead97ce23",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "e3eebd23-fd46-466a-8973-4d495b2efe64",
          "rank": 1,
          "key": "D_MAJOR",
          "sections": [
            {
              "id": "60be35fd-909d-47d9-8e73-77109b676030",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 16,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 16,
              "fastestOrnamentalNotesPerBar": 32,
              "commentForReview": "",
              "tempoIndication": {
                "id": "40e99953-ea31-4f2c-a742-0fc7428d8c76",
                "text": "Allegro con fuoco"
              },
              "rank": 1
            },
            {
              "id": "a8215409-6b86-4238-93d6-6d2d9451b5a6",
              "metreNumerator": 2,
              "metreDenominator": 2,
              "isCommonTime": false,
              "isCutTime": true,
              "fastestStructuralNotesPerBar": 16,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 16,
              "fastestOrnamentalNotesPerBar": 32,
              "tempoIndication": {
                "id": "5e4eca5b-1cd7-4109-886f-3bb84b308489",
                "text": "Piu mosso"
              },
              "rank": 2
            }
          ]
        }
      ],
      "pieceId": "f5ed1e1a-855d-411c-84ca-e86fed66d75c",
      "id": "67feeb40-48a8-4c49-a5f2-9cedc198dfed",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "ae5c9a28-3bb3-44f8-b5a5-b36a68806c80",
          "rank": 1,
          "key": "F_MAJOR",
          "sections": [
            {
              "id": "6cad1dd7-6fa8-4b36-a7b3-660381a758bb",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 8,
              "fastestOrnamentalNotesPerBar": 16,
              "comment": "Ornamental: 2 note arpeggios on 8th note",
              "tempoIndication": {
                "id": "666db109-0966-4d55-99f1-162ac94c11f5",
                "text": "Allegretto grazioso"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "3b1a77da-e9ac-4d3c-bcd4-81871b5519fb",
      "id": "0ce0ef09-63ef-4076-9646-a34b21d9246a",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "f44b0656-ad4f-473e-927c-3b4182749044",
          "rank": 1,
          "key": "B_FLAT_MAJOR",
          "sections": [
            {
              "id": "d63a6cdd-5c9c-4a3e-bab8-cc8487d4ab21",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 8,
              "isFastestStructuralNoteBelCanto": false,
              "fastestRepeatedNotesPerBar": 8,
              "fastestOrnamentalNotesPerBar": 24,
              "comment": "Ornamental: 3 note arpeggios on 8th note",
              "tempoIndication": {
                "id": "68b97adb-f73f-40ab-8aac-6eb184e3adfc",
                "text": "Allegretto"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "fa1183b2-0517-40bc-8961-6fd2999d8ea5",
      "id": "1197ead5-e674-4ef7-a772-a61e1242e1e3",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "afab50b4-d897-4b56-9694-c57df53cba4a",
          "rank": 1,
          "key": "B_FLAT_MAJOR",
          "sections": [
            {
              "id": "615936e4-9472-4f1f-8f09-3db0ff12b2eb",
              "metreNumerator": 4,
              "metreDenominator": 4,
              "isCommonTime": true,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 16,
              "isFastestStructuralNoteBelCanto": false,
              "fastestStaccatoNotesPerBar": 8,
              "fastestRepeatedNotesPerBar": 8,
              "fastestOrnamentalNotesPerBar": 32,
              "tempoIndication": {
                "id": "bbe31fd3-4468-414a-ad50-cfa7767852fd",
                "text": "Andante"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "9917a454-6a24-4e4b-b5c3-a36069e09e8e",
      "id": "7ed1bb26-8620-4240-aaa4-0a7be615fb40",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "3c6e903f-51ab-4895-9819-fe797c6411fd",
          "rank": 1,
          "key": "G_MINOR",
          "sections": [
            {
              "id": "34232553-baac-4b47-be11-103d194bc93d",
              "metreNumerator": 6,
              "metreDenominator": 8,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 6,
              "isFastestStructuralNoteBelCanto": false,
              "fastestRepeatedNotesPerBar": 6,
              "fastestOrnamentalNotesPerBar": 18,
              "comment": "Ornamental: 3 note appogiatura on dotted 8th note",
              "tempoIndication": {
                "id": "30c2b791-dd74-46d5-8e46-813f856f1f16",
                "text": "Andantino piacevole"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "5eefb47f-b664-489d-a633-50b12c0ff48c",
      "id": "d6517928-16e1-4fea-b73c-884480a3f92a",
      "isNew": true
    },
    {
      "category": "KEYBOARD",
      "movements": [
        {
          "id": "3b7886bc-d4fa-40ac-9c1c-a92584e816b6",
          "rank": 1,
          "key": "G_MINOR",
          "sections": [
            {
              "id": "de5085d2-3acd-42b2-8050-c6e76f875e8e",
              "metreNumerator": 3,
              "metreDenominator": 4,
              "isCommonTime": false,
              "isCutTime": false,
              "fastestStructuralNotesPerBar": 12,
              "isFastestStructuralNoteBelCanto": false,
              "fastestRepeatedNotesPerBar": 12,
              "tempoIndication": {
                "id": "3cdbb31b-7f96-4f54-b25e-5b7d4c578a16",
                "text": "Molto moderato e sostenuto"
              },
              "rank": 1
            }
          ]
        }
      ],
      "pieceId": "890e4497-d47a-4480-bdf8-3c2c7a78242e",
      "id": "065c6ad3-5648-49ea-b57d-658495a7a161",
      "isNew": true
    }
  ],
  "tempoIndications": [
    {
      "id": "8fb50b67-1e67-49c0-8bbc-146fb4189735",
      "text": "Poco più mosso",
      "isNew": true
    },
    {
      "id": "1bfdf7ab-fe50-4c6d-bffc-b0e240644da3",
      "text": "Moderato dolce",
      "isNew": true
    },
    {
      "id": "59c9d6a1-a900-4892-887f-46a49a34e7fd",
      "text": "Allegro giojoso",
      "isNew": true
    },
    {
      "id": "1891528c-091e-4d2e-903f-b895bfe5d4f1",
      "text": "Grave sostenuto",
      "isNew": true
    },
    {
      "id": "bd52695e-1bff-47e6-9dcb-30b8d0d9c30a",
      "text": "Moderato grazioso",
      "isNew": true
    },
    {
      "id": "30c2b791-dd74-46d5-8e46-813f856f1f16",
      "text": "Andantino piacevole",
      "isNew": true
    },
    {
      "id": "3cdbb31b-7f96-4f54-b25e-5b7d4c578a16",
      "text": "Molto moderato e sostenuto",
      "isNew": true
    }
  ],
  "mMSourceDescription": {
    "title": "Tanzweisen aus Opern von Gluck",
    "year": 1880,
    "isYearEstimated": false,
    "type": "EDITION",
    "link": "https://ks15.imslp.org/files/imglnks/usimg/1/17/IMSLP678658-PMLP970329-GluckBuelow_Tanzweisen.pdf",
    "comment": "",
    "references": [
      {
        "type": "PLATE_NUMBER",
        "reference": "R. 2373"
      },
      {
        "type": "PLATE_NUMBER",
        "reference": "R. 2376"
      },
      {
        "type": "PLATE_NUMBER",
        "reference": "R. 2377"
      },
      {
        "type": "PLATE_NUMBER",
        "reference": "R. 2378"
      }
    ],
    "isNew": true
  }
}

###